(function(z){
var Nk=function(a){this.M=window.document;this.h=this.Wd=window;this.K=a;new z.yd;this.da=!1;this.fc=this.rb=null;this.V=[];this.wc=!1;this.r={};this.r.ia=0;this.r.Hj="";this.r.Gj="";this.r.Wb=null;this.qd=this.pd=0;this.Nc=/\w/i;this.o={};this.o.parentId="WACDocumentPanelContent";this.o.positionId="Selected";this.o.seq="1";this.o.words=[];this.o.words.push("The");this.o.words.push("In");this.o.words.push("I");this.o.words.push("It");this.o.words.push("He");this.o.words.push("This");this.o.words.push("A");
this.o.words.push("But");this.o.words.push("As");this.o.words.push("For");this.ce=z.S.a().bind(this,this.ke);this.sd=z.S.a().bind(this,this.Mf);this.va=this.T=null};var Ok=function(){this.wb="rwGooglePredictionDictionaryDetails";this.jc="rwGooglePredictionResponseDetails";this.cl();this.n={};this.fa=this.qa=null;var a=[];a.push("Web");a.push(window.location.href);window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"BarShown",parameters:a},"*")};z.f=Nk.prototype;
z.f.Lb=function(a){null!==this.va&&((0,window.clearTimeout)(this.va),this.va=null);var b=this;this.va=(0,window.setTimeout)(function(){b.ce(a)},300)};z.f.play=function(){z.T.a().k("onWRPlay",!0)};
z.f.$d=function(a){try{var b=this;this.K.Fl(a,function(){b.play()});-1==a.target.className.indexOf("texthelp-toolbarbutton")&&-1==a.target.parentNode.className.indexOf("texthelp-toolbarbutton")&&-1==a.target.className.indexOf("th-RW4GC-toolbar")&&-1==a.target.parentNode.className.indexOf("th-RW4GC-toolbar")||this.K.ok()}catch(c){}};
z.f.Kb=function(a){if(a.ctrlKey&&47<a.keyCode&&58>a.keyCode)if("text"!==a.target.type&&"textarea"!==a.target.type)a.preventDefault(),a.stopPropagation(),window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{var b=[];b.push(a);null!==this.Ja&&((0,window.clearTimeout)(this.Ja),this.Ja=null);this.Ja=(0,window.setTimeout)(function(){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionKeyDown(b)}.bind(this),10);z.Xj()&&(a.preventDefault(),a.stopPropagation());this.K.Kb(a);this.Mb();
this.da&&this.xa("")}};z.f.Pc=function(a){var b=[];b.push(a.keyCode);z.T.a().k("onKeyUpEvent",b);null!==this.T&&((0,window.clearTimeout)(this.T),this.T=null);this.Be=17===a.keyCode?this.zg?!1:!0:!1;this.T=(0,window.setTimeout)(this.sd,100);this.K.Vf(a.key)};z.f.Nl=function(a){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionKeyDown(a)};z.f.xa=function(){null!==this.T&&((0,window.clearTimeout)(this.T),this.T=null);this.T=(0,window.setTimeout)(this.sd,0)};
z.f.Mf=function(){this.T=null;if(this.da)if("text"!==window.document.activeElement.type&&"textarea"!==window.document.activeElement.type)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{var a=this.K.pc();if(null==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{var b=a.context.substr(a.context.length-1);if(0==a.context.length||" "==b||-1!==".?!".indexOf(b)){var b=z.S.a().nb(),c=z.V.a().I().prediction.predictahead;if(!b["Predict Ahead"]||!c){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();
return}}b=z.V.a().I().prediction.results;c=z.V.a().I().language.services;this.r.ia++;999<this.r.ia&&(this.r.ia=0);var d='"'+z.S.a().Pf(a.context)+'","'+b+'","en_US"',e='{ "parent":"document.body", "position":"'+this.K.wb+'","addSpace":false,"seq":"'+this.r.ia+'"}';z.S.a().wg(this.r.ia);this.r.Wb=a;e=z.pd(e);d=[];d[0]=a.context;d[1]=b;d[2]=c;if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else e.context=d,window.thPostMessage({method:"thPrediction",
type:"1757FROM_PAGERW4G",payload:e},"*")}}};z.f.ae=function(){var a=window.document.getElementById("th-RW4GC-picture-dictionary"),b=window.document.getElementById("th-RW4GC-translator");if(null!=window.document.getElementById("th-RW4GC-dictionary")||null!=a||null!=b)a=this.K.ab(),null!=a&&""!=a&&(a[0]=a[0].replace(/[;().,*+?^${}"\u201c\u201d<>|[\]\\]/g,""),z.T.a().k("onWordChanged",[]))};z.f.Mb=function(){this.hm()};
z.f.hm=function(){if(null!=window.document.querySelector(".th-RW4GC-prediction")){var a=this.K.ya();a.x+=2;if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,"document.body")}};z.f.ke=function(a){if("text"!==a.target.type&&"textarea"!==a.target.type)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else this.K.Lb(a),this.Mb(),this.da&&this.xa("")};
z.f.be=function(a){try{this.K.em(a[0]);var b=window.document.activeElement.closest(".freebirdFormviewerViewItemsItemItem");null==b&&(b=window.document.activeElement.closest(".freebirdFormeditorViewItemActive"));if(null!==b){var c=b.querySelector(".isFocused");null===c||c.classList.contains("hasValue")||(c.classList.add("hasValue"),b.classList.contains("HasError")&&b.classList.remove("HasError"))}}catch(d){z.S.a().b(d)}try{var e=z.S.a().Ma();a=[];a.push("prediction insert");a.push(e.Email);a.push(e.Email.split("@")[1]);
window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"SendEvent",parameters:a},"*");this.xa("")}catch(g){z.S.a().b(g)}};
z.f.Qc=function(a){try{a[0]?(window.addEventListener("scroll",this.Mb.bind(this),!0),window.addEventListener("resize",this.Mb.bind(this),!0)):(window.removeEventListener("scroll",this.Mb.bind(this),!0),window.removeEventListener("resize",this.Mb.bind(this)),!0);var b=window.document.getElementById("rwGooglePredictionDictionaryDetails");if(!b){var c=window.document.body,b=window.document.createElement("div");b.setAttribute("id","rwGooglePredictionDictionaryDetails");b.className="rwGooglePredictionDictionaryDetails";
b.style.position="absolute";c.appendChild(b);var d=window.document.createElement("div");d.setAttribute("id","rwGooglePredictionResponseDetails");d.className="rwGooglePredictionResponseDetails";c.appendChild(d)}this.da=a[0];if(this.K.An())this.Mb(),this.da&&(a=[],a.push("kix-appview-editor"),this.xa(""),z.T.a().k("onOpenPredictionWindow",a));else window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose()}catch(e){z.S.a().b(e)}};
z.f.Hh=function(){try{var a=z.J("kix-cursor-caret",this.h);null!==a&&(z.S.a().fireEvent(a,"click"),a.focus())}catch(b){z.S.a().b(b)}};z.f.sk=function(a){a=a[0];this.K.Xk(a);a||z.T.a().k("onWRStop",!0)};
z.f.Gg=function(a){var b=window.document;void 0!==a&&(b=a.contentDocument);a=z.S.a().bind(this,this.Lb);b.addEventListener("mousedown",a,!0);a=z.S.a().bind(this,this.$d);b.addEventListener("mousemove",a,!0);b.addEventListener("keydown",this.Kb.bind(this),!0);b.addEventListener("keyup",this.Pc.bind(this),!0);a=z.S.a().bind(this,this.ae);b.addEventListener("mouseup",a,!0)};z.f.ik=function(a){if(0<a.length)for(var b=0;b<a.length;b++)try{this.Gg(a[b])}catch(c){}};z.ek.Mh="GoogleFormsParser";z.B(Ok,z.Uj);z.f=Ok.prototype;z.f.cl=function(){window.m_webReaderElem=window.document.getElementById("webReaderModule");window.m_extensionPath=window.m_webReaderElem.getAttribute("data-root");this.Kd(window.m_extensionPath+"assets/distiller/domdistiller.js");this.Kd(window.m_extensionPath+"assets/HTMLParser/HTMLParser.js",this.ek.bind(this))};
z.f.Kd=function(a,b){var c=window.document.documentElement.getElementsByTagName("body")[0];if(null==c||void 0==c)c=window.document.body;var d=window.document.createElement("script");d.src=a;d.async=!0;d.onload=d.onreadystatechange=function(){this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(d.onload=d.onreadystatechange=null,c.removeChild(d),void 0!=b&&b())};c.appendChild(d)};
z.f.qm=function(a){this.vm=a;this.Hl=new window.MutationObserver(this.Il.bind(this));this.Hl.observe(this.vm,{childList:!0,subtree:!0})};z.f.Il=function(a){var b=[];a.forEach(function(a){a.addedNodes.forEach(function(a){if("IFRAME"==a.nodeName)b.push(a);else if(0<a.childNodes.length)for(var c=0;c<a.childNodes.length;c++)"IFRAME"==a.childNodes[c].nodeName&&b.push(a.childNodes[c])}.bind(this))}.bind(this));for(a=0;a<b.length;a++)this.gk(b[a])};
z.f.gk=function(a){a.addEventListener("load",function(){this.n.stop();this.n.addEventsToFrame(a);this.fa.Gg(a)}.bind(this))};
z.f.ek=function(){var a=window.document.querySelector("#thSpeechStreamTBPlaceHolder").getAttribute("data-root"),b=window.document.querySelector("#thWebReaderPlaceHolder").getAttribute("dynamic-frames");this.n=new window.textHelp.parsers.HTMLParserAPI(!0,a+"assets/HTMLParser/");a=this.fa=new Nk(this);a.ik(window.frames);var c=z.S.a().bind(a,a.Lb);a.M.addEventListener("mousedown",c,!0);c=z.S.a().bind(a,a.$d);a.M.addEventListener("mousemove",c,!0);a.M.addEventListener("keydown",a.Kb.bind(a),!0);a.M.addEventListener("keyup",
a.Pc.bind(a),!0);c=z.S.a().bind(a,a.ae);a.M.addEventListener("mouseup",c,!0);z.T.a().i("onclicktospeak",a.sk,a);z.T.a().i("onPredictionChange",a.be,a);z.T.a().i("onWRPredictionStateChanged",a.Qc,a);"true"==b&&this.qm(window.document.body)};z.f.bg=function(){return this.n.hiliteSelection()};z.f.Xk=function(a){this.n.hoverSpeakEnabled(a)};z.f.Fl=function(a,b){this.n.mouseOverEvent(a,b)};z.f.ok=function(){this.n.clearHoverSpeak()};z.f.Gc=function(a){this.n.highlightSelection(a)};z.f.hf=function(){return this.n.hasSelection()};
z.f.Qo=function(){if(!(-1<window.location.href.indexOf(".texthelp.com/simplify/"))){var a=window.textHelp.webreader.UserSettingsSingleton.getInst().getUserSettings().language.services;window.open("https://rw.texthelp.com/simplify/home/simplify?locale\x3d"+(0,window.encodeURIComponent)(a)+"\x26simplify\x3d"+window.location.href,"_newtab")}};z.f.ab=function(){return this.n.getWord()};z.f.getSelection=function(){return this.n.getSelection()};z.f.pb=function(a){try{this.n.hiliteWord(a)}catch(b){}};
z.f.Sf=function(){this.n.clearBrowserSelection()};
z.f.Ac=function(a,b,c){a=this.n.collectHighlights(b,c);b=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("ch_documentTitle");a={highlights:a,title:window.document.getElementsByTagName("title")[0].innerHTML,url:window.location.href,docTitle:b};this.Vg=window.textHelp.webreaderapi.EventBusSingleton.getInst().subscribe("onCollectHighlightsWeb",this.Fh,this);window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"CollectHighlights",parameters:a},"*")};
z.f.Fh=function(){try{window.textHelp.webreaderapi.EventBusSingleton.getInst().unsubscribe(this.Vg),this.op.focus()}catch(a){window.console.error(a.stack)}};z.f.stop=function(){this.n.stop()};z.f.Jd=function(a,b){var c=window.textHelp.webreader.UserSettingsSingleton.getInst().getUserSettings().speechoptions.continousreading;b(this.n.hiliteNextSentence(c))};z.f.mc=function(){this.n.clearHighlights()};
z.f.Xe=function(a,b,c){a=this.n.collectVocabs(a,b,c);b=window.textHelp.webreader.ConfigurationSingleton.getInst().getConfiguration();c={};c.words=a;c.locale=b.locale;c.user=b.serversettings.user;c.translations={};c.translations.docTitle=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_document_title");c.translations.title=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_title");c.translations.heading=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_heading");
c.translations.symbol=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_symbol");c.translations.notes=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_notes");c.translations.meaning=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_meaning");c.locale=window.textHelp.webreader.UserSettingsSingleton.getInst().getUserSettings().language.services;window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",
method:"Vocab",parameters:c},"*")};z.f.qc=function(a){a(this.n.getSelectionLocal())};z.f.bh=function(a){this.Ik().then(this.Jk).then(function(b){window.title=b.title;window.html=b.html;a({documentTitle:window.title,html:window.html})})};z.f.Ik=function(){return new window.Promise(function(a){window.result=window.org.chromium.distiller.DomDistiller.applyWithOptions({});a({title:window.result[1],html:window.result[2][1]})})};
z.f.Jk=function(a){var b=window.document.createElement("body");b.innerHTML=a.html;for(var c=b.querySelectorAll("img"),d=0;d<c.length;d++){var e=c[d];"https:"!==e.getAttribute("src").substr(0,6).toLowerCase()&&b.removeChild(e)}return Object.assign({},a,{html:b.innerHTML})};z.f.la=function(){this.n.clearSelection_()};z.f.Zc=function(){throw Error("Not implemented");};z.f.Xc=function(){throw Error("Not implemented");};z.f.qc=function(a){a(this.n.getSelectionLocal())};z.f.ih=function(a){this.n.predictionInsertText(a)};
z.f.pc=function(){try{var a=[];a.context="";a.word="";a.cursorindex="";a.spaceatstart=!1;a.spaceatend=!1;a.prepunc="";a.postpunc="";a.selectRight=0;a.selectLeft=0;a.prechar="";a.currentchar="";a.postchar="";a.context=this.n.getPredictionSentence()}catch(b){}return a};z.f.em=function(a){this.n.predictionInsertText(a)};z.f.An=function(){return this.n.isEditable()};z.f.ae=function(a){this.n.onMouseUp(a)};z.f.Lb=function(a){this.n.onMouseDown(a)};z.f.Kb=function(a){this.n.onKeyDown(a)};z.f.$d=function(a){try{this.n.onMouseOver(a)}catch(b){}};
z.f.Gf=function(a){try{this.qa=a}catch(b){z.S.a().b(b)}};z.f.Cb=function(){try{return this.qa.name}catch(a){z.S.a().b(a)}};z.f.Ab=function(){try{return this.qa.bar}catch(a){z.S.a().b(a)}};z.f.ya=function(){try{var a=this.n.getPredictionCoordinates(),b={x:10,y:10};b.x=(0,window.parseInt)(a.left.substring(0,a.left.length-2))-32;b.y=(0,window.parseInt)(a.top.substring(0,a.top.length-2))+2;return b}catch(c){z.S.a().b(c)}};
z.f.jd=function(){try{var a=this.n.predictionManager.predictionManager.currentChar.trim(),b=this.n.getPredictionSentence(),b=b.trim();if(1>a.length)return b;-1<".?!".indexOf(a)&&(b+=a);return b}catch(c){z.S.a().b(c)}};z.t("textHelp.parsers.GoogleFormsParser",Ok);Ok.prototype.getParserName=Ok.prototype.Cb;Ok.prototype.getBarConfigFromParser=Ok.prototype.Ab;Ok.prototype.setParserConfig=Ok.prototype.Gf;Ok.prototype.getPredictionPosition=Ok.prototype.ya;Ok.prototype.getSentenceText=Ok.prototype.jd;z.Of("GoogleFormsParser");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_GoogleFormsParser.js