(function(z){
z.Oj=function(a,b){var c=a.style[z.Oa(b)];return"undefined"!==typeof c?c:a.style[z.bg(a,b)]||""};var Pj=function(a){if(1==a.nodeType)return z.mg(a);var b=z.la(a.ln),c=a;a.targetTouches&&a.targetTouches.length?c=a.targetTouches[0]:b&&a.Za.targetTouches&&a.Za.targetTouches.length&&(c=a.Za.targetTouches[0]);return new z.H(c.clientX,c.clientY)};z.Qj=function(a,b){var c=Pj(a),d=Pj(b);return new z.H(c.x-d.x,c.y-d.y)};
z.X=function(a,b){var c=b||window.document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):z.fe(window.document,"*",a,b)};z.W=function(){try{this.Vd=new Rj,null==z.I("thSpeechStreamTBPlaceHolder")&&(this.B=new Sj),this.Ee=null}catch(a){z.S.a().b(a)}};var Tj=function(a){try{if(null===a.B.A())throw Error("Could not get a reference to the current parser.");a.B.A().stop();a.Vd.stop()}catch(b){z.S.a().b(b)}};z.Uj=function(){};
z.T=function(){this.Oe={};this.gp=[];this.tm=[];this.uf=z.S.a().bind(this,this.Zd);window.addEventListener("message",this.uf,!1)};z.S=function(){this.mp="thWebReaderPlaceHolder";this.bo=this.Ua=null;this.Kn=!1;this.Wn=this.nd=null;this.eo="";this.fo=!1};z.Vj=function(a,b){for(var c=a.length;c--;)if(a[c]===b)return!0;return!1};z.Wj=function(a,b){function c(a){if(3==a.nodeType)d.push(a);else for(var b=0,h=a.childNodes.length;b<h;++b)c(a.childNodes[b])}var d=[];c(b);return d};
z.Xj=function(){var a=z.S.a();try{return a.fo}catch(b){z.S.a().b(b)}};var Yj=function(a,b){return"en_US"==b||"en-US"==b||"ENGLISH_US"==b||"en-GB"==b||"en_GB"==b||"ENGLISH_GB"==b?"en":"FRENCH"==b||"fr"==b||"FRAN"==b.substr(0,4)?"fr":"PORTUGUESE"==b||"pt"==b||"PORT"==b.substr(0,4)||"pt-BR"==b||"pt_BR"==b?"pt":"MALAYSIAN"==b||"ms"==b?"ms":"SPANISH"==b||"es"==b||"ESPA"==b.substr(0,4)?"es":"DUTCH"==b||"nl"==b||"NEDERLANDS"==b?"nl":b};
var Sj=function(){try{this.qa=null;var a=z.oj.a().Fd().highlighterSiteMap,b;for(b in a){if("default"==b)break;var c=window.location.toString().substring(0,b.length);if(c===b){this.qa=a[b];var d=z.Ff.a();z.Sf(d,a[b].parser,this.Tl,this);return}var c=window.location.toString(),e=b.split("*");if(1<e.length){var g=!0,h;for(h in e){var l=c.indexOf(e[h]);if(-1==l){g=!1;break}c=c.substr(l+e[h].length)}if(g&&(c=window.location.toString(),this.qa=a[b],g=!0,void 0!==this.qa.ot&&null==window.document.querySelector(this.qa.ot)&&
(g=!1),g)){d=z.Ff.a();z.Sf(d,a[b].parser,this.Tl,this);return}}}this.qa=a["default"];d=z.Ff.a();z.Sf(d,a["default"].parser,this.Tl,this)}catch(m){z.S.a().b(m)}};z.Zj=function(){this.Sn="Ava?"};var Rj=function(){try{this.vh=!1,this.Yd=[],this.nd=null}catch(a){z.S.a().b(a)}};var ak=function(){try{this.Lc=null,this.nj=!1,this.il=null,this.vh=!1}catch(a){z.S.a().b(a)}};
z.pj=function(a,b,c,d,e){try{this.path=b;this.fv=c;this.so;this.Vm;this.Eo;this.filename;this.speed=e;this.Ot="Allison? Ava? Samantha? Tom? Karen? Lee? Tessa? Veena? Moira? Fiona? Daniel? Serena? Miren? Montserrat? Carlos? Soledad? Juan? Paulina? Jorge? Monica? Amelie? Audrey? Thomas? Magnus? Sara? Satu? Henrik? Nora? Alva? Oskar? Tarik? Felipe? Luciana? Zuzana? Claire? Xander? Ellen? Carmela? Anna? Petra? Yannick? Melina? Nikos? Lekha? Mariska? Damayanti? Alice? Federica? Luca? Paola? Ichiro? Sakura? Sora? Tian-Tian? Mei-Jia? Ewa? Zosia? Catarina? Joana? Ioana? Milena? Yuri? Laura? Kanya? Cem? Yelda? Geraint? Gwyneth?".split(" ");this.jp=
!1;"%3F"==d.substring(d.length-3)?d=(0,window.decodeURIComponent)(d):(0,window.decodeURIComponent)(d)===d&&(d=(0,window.encodeURIComponent)(d));this.gv=d;this.jp=-1<this.Ot.indexOf(d);if(!this.jp){var g=z.V.a().I().language.services,g=Yj(z.S.a(),g),h=z.oj.a().Li().filter(function(a){return a.lC==g});d=(0,window.encodeURIComponent)(h[0].v)}try{"/"!=a.charAt(a.length-1)&&(a+="/"),"/"!=b.charAt(b.length-1)&&(b+="/")}catch(l){}this.tp=a+b+"?userName\x3d"+c+"\x26voiceName\x3d"+d+"\x26speedValue\x3d"+e}catch(m){window.console.log(m)}};
var bk=function(a,b,c){return new window.Promise(function(d,e){var g=new window.XMLHttpRequest;c=(0,window.encodeURIComponent)(c);var h="filename\x3d"+b+"\x26text\x3d"+c;g.open("POST",a);g.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset\x3dUTF-8");g.send(h);g.onload=function(){if(200==this.status){var a=JSON.parse(this.response);null==a?e(Error("Mp3 Request response is empty.")):d(a)}else e(Error(this.statusText))};g.onerror=function(){e(Error("Error converting text.\r\n"+
g.statusText))}})};var ck=function(a,b){window.console.log("statusChecker - "+b);var c=dk(b);try{c.then(function(c){window.console.log("File Status: "+c);100==c?a.Vm(a.so):(a.Eo(Math.round(c)),(0,window.setTimeout)(function(){try{ck(a,b)}catch(c){a.xk(c)}},1E3))},function(b){a.xk(Error("StatusFile Error: "+b.message))})}catch(d){a.xk(d)}};
var dk=function(a){return new window.Promise(function(b,c){var d=new window.XMLHttpRequest;window.console.log("requestStatusFile - "+a);d.open("GET",a,!0);d.send();d.onload=function(){if(200==this.status){var a=JSON.parse(this.response);window.console.log(a);null==a?c(Error("Response is empty.")):""!=a.error&&" "!=a.error?c(Error(a.error)):b(a.progress)}else window.console.log("Error - "+this.status),c(Error(this.statusText))};d.onerror=function(){window.console.log("Error - "+this.status);c(Error("Error converting text.\r\n"+
d.statusText))}})};z.Wf.prototype.Cb=z.ca(9,function(){try{if(null===this.F)throw Error("The WebReaderAPI has not been created");return this.F.Cb()}catch(a){z.S.a().b(a)}});z.Wf.prototype.Zi=z.ca(8,function(){try{if(null===this.F)throw Error("The WebReaderAPI has not been created");return this.F.Zi()}catch(a){z.S.a().b(a)}});z.Wf.prototype.kd=z.ca(3,function(a){try{if(null===this.F)throw Error("The WebReaderAPI has not been created");void 0==a&&(a=!1);return this.F.kd(a)}catch(b){window.console.error(b.stack)}});
z.Wf.prototype.Zd=z.ca(2,function(){});z.$b.prototype.ln=z.ca(0,function(){return this.Za});z.ek={};z.jb(function(a,b){this.type=a;this.currentTarget=this.target=b;this.io=null;this.og=0;this.Ah=!1}.prototype,z.Xb.prototype);z.f=z.W.prototype;
z.f.Eb=function(){try{this.Vd.Eb();var a=z.I(z.S.a().ah());null!==a&&"true"!==a.installed&&(window.document.documentElement.setAttribute("xmlns:thRWGDns",""),a.setAttribute("installed","true"),z.T.a().i("onthAPIWord",this.Fs,this),z.T.a().i("onthAPIStop",this.as,this),this.io=new ak)}catch(b){z.S.a().b(b)}};z.f.yc=function(a,b){try{Tj(this);if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().yc(a,b)}catch(c){z.S.a().b(c)}};
z.f.yg=function(){try{if(null===this.B.A())throw Error("Could not get a reference to the current parser.");Tj(this);z.S.a();this.Ee=this.B.A().bg();if(null===this.Ee)window.texthelp.RW4GC.thToolbarStoreInstance.onSpeechStopped();else if(0===this.Ee.length)window.texthelp.RW4GC.thToolbarStoreInstance.onSpeechStopped();else this.Vd.yg(this.Ee,1),window.texthelp.RW4GC.thToolbarStoreInstance.onSpeech()}catch(a){z.S.a().b(a)}};z.f.td=function(a){try{Tj(this),this.Ah=!0,this.Vd.yg(a,1,!1)}catch(b){z.S.a().b(b)}};
z.f.stop=function(){try{if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().stop();this.Vd.stop()}catch(a){z.S.a().b(a)}};z.f.yo=function(a){this.Ee=a;if(null===this.Ee)window.texthelp.RW4GC.thToolbarStoreInstance.onSpeechStopped();else if(0===this.Ee.length)window.texthelp.RW4GC.thToolbarStoreInstance.onSpeechStopped();else this.Vd.yg(this.Ee,1)};
z.f.forward=function(){try{if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().stop();this.Vd.stop();this.Ah?this.Ah=!1:this.B.A().Jd(!1,this.yo.bind(this))}catch(a){z.S.a().b(a)}};z.f.tt=function(){try{if(null===this.B.A())throw Error("Could not get a reference to the current parser.");}catch(a){z.S.a().b(a)}};z.f.pause=function(){try{if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.Vd.pause()}catch(a){z.S.a().b(a)}};
z.f.Op=function(a){0!==a.length&&(this.B.A().la(),100<a.length&&(a.length=100),window.open("http://google.com/search?q\x3d"+(0,window.encodeURIComponent)(a.join(" "))))};z.f.Np=function(){try{Tj(this);if(null===this.B.A())throw Error("Could not get a reference to the current parser.");var a=null;this.B.A().hf()?this.B.A().qc(this.Op.bind(this)):(a=this.B.A().ab(),0!==a.length&&(this.B.A().la(),window.open("http://google.com/search?q\x3d"+(0,window.encodeURIComponent)(a.join(" ")))))}catch(b){z.S.a().b(b)}};
z.f.yt=function(){try{Tj(this);if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().Qo()}catch(a){z.S.a().b(a)}};z.f.Bt=function(a){try{Tj(this);if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().hf()&&this.B.A().qc(a)}catch(b){z.S.a().b(b)}};z.f.gt=function(a){try{Tj(this);if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().bh(a)}catch(b){z.S.a().b(b)}};
z.f.ih=function(a){try{this.stop();if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().ih(a)}catch(b){z.S.a().b(b)}};z.f.Ac=function(a,b,c,d){try{this.stop();if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().Ac(a,b,c,d)}catch(e){z.S.a().b(e)}};z.f.Xe=function(a,b,c){try{this.stop();if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().Xe(a,b,c)}catch(d){z.S.a().b(d)}};
z.f.kd=function(a){try{return void 0==a&&(a=!1),this.Vd.kd(a)}catch(b){z.S.a().b(b)}};z.f.Fs=function(a){try{if(null===this.B.A())throw Error("Could not get a reference to the current parser.");"start"!==a[0]&&this.B.A().pb(a[0])}catch(b){z.S.a().b(b)}};z.f.as=function(){try{this.B.A().stop(),this.Ah?this.Ah=!1:this.B.A().Jd(!0,this.yo.bind(this))}catch(a){this.B.A().Sf(),window.texthelp.RW4GC.thToolbarStoreInstance.onSpeechStopped(),z.S.a().b(a)}};
z.f.ck=function(){try{Tj(this);if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().Gc("#FFFF00")}catch(a){z.S.a().b(a)}};z.f.ii=function(){try{Tj(this);if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().Gc("#00FFFF")}catch(a){z.S.a().b(a)}};z.f.Ni=function(){try{Tj(this);if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().Gc("#ADFF2F")}catch(a){z.S.a().b(a)}};
z.f.Dj=function(){try{Tj(this);if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().Gc("#FF00FF")}catch(a){z.S.a().b(a)}};z.f.mc=function(){try{Tj(this);if(null===this.B.A())throw Error("Could not get a reference to the current parser.");this.B.A().mc()}catch(a){z.S.a().b(a)}};z.f.Yp=function(){try{return z.S.a().$g()}catch(a){z.S.a().b(a)}};z.f.Zp=function(){try{return z.S.a().Ua.kd()}catch(a){z.S.a().b(a)}};z.f.Xc=function(){try{Tj(this),this.B.A().Xc()}catch(a){z.S.a().b(a)}};
z.f.Zc=function(){try{Tj(this),this.B.A().Zc()}catch(a){z.S.a().b(a)}};z.f.Zi=function(){try{return this.io.isEnabled()}catch(a){z.S.a().b(a)}};z.f.ab=function(){try{var a=this.B.A().ab();return null===a||0===a.length?"":3>a.length?a.join(" "):a[0]}catch(b){z.S.a().b(b)}};z.f.Cb=function(){try{if(null===this.B.A())throw Error("Could not get a reference to the current parser.");return this.B.A().Cb()}catch(a){z.S.a().b(a)}};
z.f.Ab=function(){try{if(null===this.B.A())throw Error("Could not get a reference to the current parser.");return this.B.A().Ab()}catch(a){z.S.a().b(a)}};z.f.ya=function(){try{if(null===this.B.A())throw Error("Could not get a reference to the current parser.");return this.B.A().ya()}catch(a){z.S.a().b(a)}};z.t("textHelp.webreaderapi.WebReaderAPI",z.W);z.W.prototype.initialise=z.W.prototype.Eb;z.W.prototype.addVoiceNote=z.W.prototype.yc;z.W.prototype.speakSelection=z.W.prototype.yg;
z.W.prototype.speakWord=z.W.prototype.td;z.W.prototype.stop=z.W.prototype.stop;z.W.prototype.getVoices=z.W.prototype.kd;z.W.prototype.yellowHighlighter=z.W.prototype.ck;z.W.prototype.getStaticOptionsDialog=z.W.prototype.Yp;z.W.prototype.getStaticVoices=z.W.prototype.Zp;z.W.prototype.startSpeechRecognition=z.W.prototype.Xc;z.W.prototype.stopSpeechRecognition=z.W.prototype.Zc;z.W.prototype.isSpeechRecognitionRunning=z.W.prototype.Zi;z.W.prototype.getWord=z.W.prototype.ab;
z.W.prototype.getParserName=z.W.prototype.Cb;z.W.prototype.getBarConfigFromParser=z.W.prototype.Ab;z.W.prototype.getPredictionPosition=z.W.prototype.ya;z.f=z.Uj.prototype;z.f.bg=function(){throw Error("Not implemented");};z.f.hf=function(){throw Error("Not implemented");};z.f.ab=function(){throw Error("Not implemented");};z.f.getSelection=function(){throw Error("Not implemented");};z.f.pb=function(){throw Error("Not implemented");};z.f.Sf=function(){throw Error("Not implemented");};z.f.Ac=function(){throw Error("Not implemented");};z.f.yc=function(){throw Error("Not implemented");};z.f.stop=function(){throw Error("Not implemented");};
z.f.Q=function(a,b){z.S.a().Q(a,b)};z.f.wa=function(a,b){z.S.a().wa(a,b)};z.f.S=function(a,b){return z.S.a().S(a,b)};z.f.dd=function(a){return z.S.a().dd(a)};z.f.zd=function(a,b,c){z.S.a().zd(a,b,c)};
z.f.Vf=function(a){if(-1!=" ?!.".indexOf(a)){var b=z.V.a().I().speechoptions.speakoneachword,c=z.V.a().I().speechoptions.speakoneachsentence;if(b||c){var d=this.jd(a).split(" "),e=d[d.length-1],g=e[e.length-1];-1<" .?!".indexOf(g)||void 0==g||0==g.trim().length||(g=[],g.push(e),b&&c?(" "!==a&&(this.sl=z.T.a().i("onthAPIStop",function(){z.S.a().Ua.td(d);z.T.a().Qe(this.sl)},this)),z.S.a().Ua.td(g)):b?z.S.a().Ua.td(g):c&&" "!==a&&z.S.a().Ua.td(d))}}};z.ga(z.T);z.f=z.T.prototype;
z.f.Zd=function(a){try{if(void 0!=a.source&&void 0!=a.data&&a.source==window&&"1757FROM_BGRW4G"==a.data.type){"thSetVisibility"==a.data.method&&z.T.a().k("onBarVisibilityChanged",a.data.visibility);"thFocusBar"==a.data.method&&z.T.a().k("onFocusBar",{});"thOnBrowserAction"==a.data.method&&z.T.a().k("onBrowserAction",a.data.payload);"trialValidation"==a.data.method&&(z.S.a().Ff(a.data.payload),z.T.a().k("onLicenseReceived",a.data.payload));"msgReceived"==a.data.method&&(z.S.a().Ff(a.data.payload),
z.T.a().k("onLicenseReceived",a.data.payload));"thPrediction"==a.data.method&&z.T.a().k("onPredictionChanged",a.data.payload);"onGetthRWFGSettings"==a.data.method&&z.T.a().k("onGetSettingsChanged",a.data.payload);"onGetthRWFGMessage"==a.data.method&&z.T.a().k("onMessageReceived",a.data.payload);"onthRWFGPopup"==a.data.method&&z.T.a().k("onMessagePopup",a.data.payload);"thGetVoices"==a.data.method&&z.T.a().k("onVoices",a.data.payload);"thGetChromeVoices"==a.data.method&&z.T.a().k("onChromeVoices",
a.data.payload);"thChromeSpeechEvent"==a.data.method&&z.T.a().k("onChromeSpeechEvent",a.data.payload);"thChromeSpeechEventWord"==a.data.method&&z.T.a().k("onChromeSpeechWordEvent",a.data.payload);"onCommand"==a.data.method&&(0,window.alert)(a.data.payload);if("onGetOAuthToken"==a.data.method){var b=[];null!=a.data.payload&&(b=a.data.payload,z.S.a().Ff(a.data.payload));z.T.a().k("onGetOAuthToken",b)}"onAddVoiceNoteToken"==a.data.method&&z.T.a().k("onAddVoiceNoteToken",a.data.parameters.token);"onCheckIt"==
a.data.method&&z.T.a().k("onCheckIt",a.data.payload);"onSpellingSuggestions"==a.data.method&&z.T.a().k("onSpellingSuggestions",a.data.payload);"onGetOAuthTokenSilent"==a.data.method&&(b=[],null!=a.data.payload&&(b=a.data.payload,z.S.a().Ff(a.data.payload)),z.T.a().k("onGetOAuthTokenSilent",b));"onCollectHighlightsWeb"==a.data.method&&z.T.a().k("onCollectHighlightsWeb",a.data.payload);"onVocabWeb"==a.data.method&&z.T.a().k("onVocabWeb",a.data.payload);"onAuthenticate"==a.data.method&&z.T.a().k("onAuthenticate",
a.data.payload);"onGetLocaleDate"==a.data.method&&z.T.a().k("onGetLocaleDate",a.data.payload);"onGetLinks"==a.data.method&&z.T.a().k("onGetLinks",a.data.payload);"onRefreshLicense"==a.data.method&&z.T.a().k("onRefreshLicense",a.data.payload)}}catch(c){z.S.a().b(c)}};
z.f.i=function(a,b,c){try{if("string"!==typeof a)throw Error("textHelp.webreaderapi.EventBusSingleton.subscribe's  first parameter 'eventName' should be a string");if("function"!==typeof b)throw Error("textHelp.webreaderapi.EventBusSingleton.subscribe's  first parameter 'callback' should be a function");this.Oe[a]||(this.Oe[a]=[]);var d=b;null!==c&&(d=z.S.a().bind(c,b));this.Oe[a].push(d);this.Et={Mp:a,xp:this.Oe[a].length-1};var e=this.tm.length;this.fp={};this.tm[e]=this.Et;return this.gp[e]=this.fp}catch(g){z.S.a().b(g)}};
z.f.k=function(a,b){try{if("string"!==typeof a)throw Error("textHelp.webreaderapi.EventBusSingleton.publish's first parameter 'eventName' should be a string");if(!b)throw Error("textHelp.webreaderapi.EventBusSingleton.publish requires a second argument 'data'");var c,d;if(this.Oe[a])for(c=0;c<this.Oe[a].length;c++)(d=this.Oe[a][c])&&d(b)}catch(e){z.S.a().b(e)}};z.f.Qe=function(a){try{var b=this.tm[this.gp.indexOf(a)];this.Oe[b.Mp][b.xp]=null}catch(c){z.S.a().b(c)}};z.f.Sb=function(){try{return this.a()}catch(a){z.S.a().b(a)}};
z.t("textHelp.webreaderapi.EventBusSingleton",z.T);z.T.prototype.unsubscribe=z.T.prototype.Qe;z.T.prototype.subscribe=z.T.prototype.i;z.T.prototype.publish=z.T.prototype.k;z.T.getInst=z.T.prototype.Sb;z.ga(z.S);z.f=z.S.prototype;z.f.Sb=function(){return z.S.a()};z.f.zq=function(){try{return this.Kn}catch(a){z.S.a().b(a)}};z.f.Vp=function(){try{var a=this.ua();return null==a?null:a.split("@")[1]}catch(b){z.S.a().b(b)}};z.f.Dt=function(a){try{return Object.keys(a).toString()===Object.keys([]).toString()?0:Object.keys(a).length}catch(b){return z.S.a().b(b),0}};
z.f.rt=function(a,b){try{void 0==b?window.thPostMessage({type:"1757FROM_PAGERW4G",method:"trialValidation",user:a},"*"):window.thPostMessage({type:"1757FROM_PAGERW4G",method:"trialValidation",user:a,screenScraped:b},"*")}catch(c){z.S.a().b(c)}};z.f.ah=function(){try{return this.mp}catch(a){z.S.a().b(a)}};
z.f.Ff=function(a){try{for(var b in a.pfs)a.features.hasOwnProperty(b)&&0==a.pfs[b]&&(a.features[b]=!1);var c=!1;if(a.hasOwnProperty("thdd")){if("unlimited"==a.thdd.timetype)c=!0;else if("timed"==a.thdd.timetype&&Number.isInteger(a.thdd.time))try{var d=new Date;d.setTime((new Date(a.thdd.timestamp)).getTime()+36E5*a.thdd.time);new Date<=d&&(c=!0)}catch(e){}if(c)for(b in a.thdd.features)a.features.hasOwnProperty(b)&&0==a.thdd.features[b]&&(a.features[b]=!1)}this.nd=a;this.Wn=a.features}catch(g){z.S.a().b(g)}};
z.f.Ma=function(){try{return this.nd}catch(a){z.S.a().b(a)}};z.f.nb=function(){try{return this.Wn}catch(a){z.S.a().b(a)}};z.f.Zf=function(){try{var a=z.I("thSpeechStreamTBPlaceHolder");if(null!==a)return z.I("thSpeechStreamTBPlaceHolder").getAttribute("data-root");a=z.I("thWebReaderPlaceHolder");return null!==a?z.I("thWebReaderPlaceHolder").getAttribute("data-root"):null}catch(b){z.S.a().b(b)}};
z.f.Yf=function(){try{var a=z.I("webReaderModule").getAttribute("lang");null==a&&(a=z.I("thSpeechStreamTBPlaceHolder").getAttribute("lang"));var b=z.oj.a().Fd();"undefined"!==typeof b[a]&&(b.locale=a);return b.locale}catch(c){z.S.a().b(c)}};z.f.fd=function(){try{return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a,c){return c=16*Math.random(),("y"==a?c&3|8:c|0).toString(16)})}catch(a){z.S.a().b(a)}};z.f.Wj=function(a){return Array.prototype.slice.call(a)};
z.f.bind=function(a,b){return function(){return b.apply(a,z.S.a().Wj(arguments))}};z.f.b=function(a){window.console.error(a.stack)};
z.f.Q=function(a,b){try{if("string"==typeof a&&(a=z.I(a)),a){var c=a.className;if(c&&0<c.length){var d=b.split(" ");if(1===d.length&&-1===(" "+c+" ").lastIndexOf(" "+b+" "))a.className=a.className+" "+b;else{for(var e=c.split(" "),g=d.length,h,c=[],l=0;l<g;l++)h=d[l],-1===e.indexOf(h)&&c.push(h);a.className=a.className+" "+(1<c.length?c.join(" "):c[0])}}else a.className=b}}catch(m){z.S.a().b(m)}};
z.f.wa=function(a,b){try{if("string"==typeof a&&(a=z.I(a)),a){var c=a.className;if(c&&0<c.length){for(var d=c.split(" "),e=b.split(" "),g=d.length,h,c=[],l=0;l<g;l++)h=d[l],-1===e.indexOf(h)&&c.push(h);switch(!0){case 1<c.length:a.className=c.join(" ");break;case 1==c.length:a.className=c[0];break;case 0==c.length:a.className=""}}}}catch(m){z.S.a().b(m)}};
z.f.S=function(a,b){try{if(null===a||void 0==a)return!1;if(a.className)for(var c=a.className.split(" "),d=b.toUpperCase(),e=0;e<c.length;e++)if(c[e].toUpperCase()==d)return!0;return!1}catch(g){z.S.a().b(g)}};z.f.dd=function(a){try{if(null===a)return!1;var b=[];a.className&&(b=a.className.split(" "));return b}catch(c){z.S.a().b(c)}};z.f.zd=function(a,b,c){try{this.wa(a,b.toString()),this.Q(a,c.toString())}catch(d){z.S.a().b(d)}};z.f.trim=function(a){return a.replace(/^\s*([\S\s]*?)\s*$/,"$1")};
z.f.Kt=function(a){var b=/\w/i,c=a.match(b),c=a.indexOf(c);0<c&&(a=a.substring(c).replace(/[\u200B]/g,""));a=a.split("").reverse().join("");c=a.match(b);c=a.indexOf(c);0<c&&(a=a.substring(c));return a.split("").reverse().join("")};z.f.Sp=function(){return this.Ua};z.f.Lo=function(a){this.Ua=a};z.f.No=function(a){this.bo=a};z.f.$g=function(){return this.bo};z.f.wg=function(a){try{this.eo=a}catch(b){z.S.a().b(b)}};z.f.Xp=function(){try{return this.eo}catch(a){z.S.a().b(a)}};
z.f.Kp=function(a){try{return a=a.replace(/\u2019/g,"'"),(0,window.encodeURIComponent)(a).replace(/\-/g,"%2D").replace(/\_/g,"%5F").replace(/\./g,"%2E").replace(/\!/g,"%21").replace(/\~/g,"%7E").replace(/\*/g,"%2A").replace(/\'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29")}catch(b){z.S.a().b(b)}};
z.f.Fp=function(a){try{return(0,window.decodeURIComponent)(a.replace(/\%2D/g,"-").replace(/\%5F/g,"_").replace(/\%2E/g,".").replace(/\%21/g,"!").replace(/\%7E/g,"~").replace(/\%2A/g,"*").replace(/\%27/g,"'").replace(/\%28/g,"(").replace(/\%29/g,")"))}catch(b){z.S.a().b(b)}};z.f.np=function(a){try{var b=window.document.createElement("div");b.appendChild(window.document.createTextNode(a));return b.innerHTML}catch(c){z.S.a().b(c)}};
z.f.Pf=function(a){try{return a.replace(/[\\]/g,"\\\\").replace(/[\/]/g,"\\/").replace(/[\b]/g,"\\b").replace(/[\f]/g,"\\f").replace(/[\n]/g,"\\n").replace(/[\r]/g,"\\r").replace(/[\t]/g,"\\t").replace(/[\"]/g,'\\"').replace(/\\'/g,"\\'")}catch(b){z.S.a().b(b)}};z.f.Ra=function(a,b){try{var c=z.S.a().Ma();return void 0!==c.lt?!0:z.S.a().nb()[a]?!0:(null!==c.upgrade_link&&b&&window.open(c.upgrade_link,"_exthtb").focus(),!1)}catch(d){z.S.a().b(d)}};z.f.nm=function(a){try{this.fo=a}catch(b){z.S.a().b(b)}};
z.f.Sb=function(){try{return this.a()}catch(a){z.S.a().b(a)}};z.f.ua=function(){try{return null==this.nd?null:this.nd.Email}catch(a){z.S.a().b(a)}};
z.f.fireEvent=function(a,b){var c;if(a.ownerDocument)c=a.ownerDocument;else if(9==a.nodeType)c=a;else throw Error("Invalid node passed to fireEvent: "+a.id);if(a.dispatchEvent){switch(b){case "click":case "mousedown":case "mouseup":break;case "focus":case "change":case "blur":case "select":break;default:throw"fireEvent: Couldn't find an event class for event '"+b+"'.";}c=new window.MouseEvent(b,{view:window,bubbles:"change"==b?!1:!0,cancelable:!1});a.dispatchEvent(c)}else a.fireEvent&&(c=c.createEventObject(),
c.Yu=!0,a.fireEvent("on"+b,c))};z.f.Jt=function(a,b){b=b.replace(/[\[\](){}?*+\^$\\.|\-]/g,"\\$\x26");return a.replace(new RegExp("^["+b+"]+|["+b+"]+$","g"),"")};z.f.Bn=function(a){var b=a.getBoundingClientRect().top;a=a.getBoundingClientRect().bottom;return 0<=b&&a<=window.innerHeight};
z.f.Zo=function(a){return"en_US"==a||"en-US"==a||"ENGLISH_US"==a?"en-US":"en-GB"==a||"en_GB"==a||"ENGLISH_GB"==a?"en-GB":"FRENCH"==a||"fr"==a||"FRAN\ufffdAIS"==a?"fr":"fr-CA"==a||"fr_CA"==a?"fr-CA":"PORTUGUESE"==a||"pt"==a?"pt":"PORTUGU\ufffdS (BRASILEIRA)"==a||"pt-BR"==a||"pt_BR"==a?"pt-BR":"MALAYSIAN"==a||"ms"==a?"ms":"SPANISH"==a||"es"==a||"ESPA\ufffdOL"==a?"es":"nl"};z.f.Wf=z.aa(19);
z.f.Hp=function(){var a="none";-1!=window.navigator.userAgent.indexOf("CrOS")?a="chromeos":-1!=window.navigator.userAgent.indexOf("Windows")?a="windows":-1!=window.navigator.userAgent.indexOf("Mac")&&(a="macos");return a};z.t("textHelp.webreaderapi.HelpersSingleton",z.S);z.S.prototype.isAuthenticated=z.S.prototype.zq;z.S.prototype.getPlaceHolder=z.S.prototype.ah;z.S.prototype.getRootLocation=z.S.prototype.Zf;z.S.prototype.setPredictionVisible=z.S.prototype.nm;z.S.prototype.getGuid=z.S.prototype.fd;
z.S.prototype.logError=z.S.prototype.b;z.S.prototype.toArray=z.S.prototype.Wj;z.S.prototype.bind=z.S.prototype.bind;z.S.prototype.addClassName=z.S.prototype.Q;z.S.prototype.removeClassName=z.S.prototype.wa;z.S.prototype.hasClassName=z.S.prototype.S;z.S.prototype.getClassName=z.S.prototype.su;z.S.prototype.changeClassName=z.S.prototype.zd;z.S.prototype.trim=z.S.prototype.trim;z.S.prototype.trimPunctuation=z.S.prototype.Kt;z.S.prototype.trimChars=z.S.prototype.Jt;z.S.prototype.getAPI=z.S.prototype.Sp;
z.S.prototype.setAPI=z.S.prototype.Lo;z.S.prototype.getOptionsDialog=z.S.prototype.$g;z.S.prototype.setOptionsDialog=z.S.prototype.No;z.S.prototype.getLicense=z.S.prototype.Ma;z.S.prototype.setLicense=z.S.prototype.Ff;z.S.prototype.getFeatures=z.S.prototype.nb;z.S.prototype.retrieveLicense=z.S.prototype.rt;z.S.prototype.CheckLicense=z.S.prototype.Ra;z.S.prototype.setPredictionSequence=z.S.prototype.wg;z.S.prototype.getPredictionSequence=z.S.prototype.Xp;z.S.prototype.encodeString=z.S.prototype.Kp;
z.S.prototype.HTMLEscape=z.S.prototype.np;z.S.prototype.JSONEscape=z.S.prototype.Pf;z.S.prototype.decodeString=z.S.prototype.Fp;z.S.getInst=z.S.prototype.Sb;z.S.prototype.getIDFromDoc=z.S.prototype.ua;z.S.prototype.getDomainFromDoc=z.S.prototype.Vp;z.S.prototype.sturdyArrayLength=z.S.prototype.Dt;z.S.prototype.fireEvent=z.S.prototype.fireEvent;z.S.prototype.isScrolledIntoView=z.S.prototype.Bn;z.S.prototype.toLang=z.S.prototype.Zo;z.S.prototype.detectOS=z.S.prototype.Hp;Sj.prototype.A=function(){try{if(null===this.cm)throw Error("The parser is currently null.");return this.cm}catch(a){z.S.a().b(a)}};Sj.prototype.Tl=function(){try{this.cm=new window.textHelp.parsers[z.ek.Mh],this.cm.Gf(this.qa)}catch(a){z.S.a().b(a)}};z.t("textHelp.webreaderapi.ParserFactory",Sj);Sj.prototype.getParser=Sj.prototype.A;z.ga(z.Zj);z.f=z.Zj.prototype;z.f.aq=function(){try{return this.Sn}catch(a){z.S.a().b(a)}};z.f.Po=function(a){try{this.Sn=a}catch(b){z.S.a().b(b)}};z.f.$g=function(){try{return z.S.a().$g()}catch(a){z.S.a().b(a)}};z.f.kd=function(){try{return z.S.a().Ua.kd()}catch(a){z.S.a().b(a)}};z.f.Sb=function(){try{return z.Zj.a()}catch(a){z.S.a().b(a)}};z.t("textHelp.webreaderapi.SettingsSingleton",z.Zj);z.Zj.prototype.get_Voice=z.Zj.prototype.aq;z.Zj.prototype.set_Voice=z.Zj.prototype.Po;
z.Zj.prototype.getOptionsDialog=z.Zj.prototype.$g;z.Zj.prototype.getVoices=z.Zj.prototype.kd;z.Zj.getInst=z.Zj.prototype.Sb;z.f=Rj.prototype;
z.f.Eb=function(){try{if(!this.vh){var a=this;window.addEventListener("message",function(b){if(void 0!=b&&void 0!=b.data&&void 0!=b.data.detail&&void 0!=b.data.detail.type&&"th-SpeechManagerEvent-38697BG"===b.data.detail.type&&"undefined"!==typeof b.data.detail.request&&"ca753d9d-f8c8-47dd-bd00-8033cd620939"==b.data.detail.request.origin){var d=b.data.detail.method;try{if(void 0!==a[d]&&"stop"!==d)a[d](b.data.detail)}catch(e){window.console.log(e)}}});window.postMessage({type:"th-SpeechManagerEvent-38697CS",detail:{method:"getVoices",
type:"SP_M_1342_CK"}},"*");this.vh=!0}}catch(b){z.S.a().b(b)}};z.f.kd=function(){try{return this.vh?this.Yd:null}catch(a){z.S.a().b(a)}};
z.f.yg=function(a){try{z.T.a().k("onthAPIWord",["start"]);var b={method:"play",type:"SP_M_1342_CK"};b.words=a;b.origin="ca753d9d-f8c8-47dd-bd00-8033cd620939";b.voice=z.V.a().I().speechoptions.voice;b.speed=z.V.a().I().speechoptions.speed;window.postMessage({type:"th-SpeechManagerEvent-38697CS",detail:b},"*");null===this.nd&&(this.nd=z.S.a().Ma());b=[];b.push("on speech");b.push(this.nd.Email);b.push(this.nd.Email.split("@")[1]);window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"SendEvent",
parameters:b},"*")}catch(c){z.S.a().b(c)}};z.f.stop=function(){try{window.postMessage({type:"th-SpeechManagerEvent-38697CS",detail:{method:"stop",type:"SP_M_1342_CK",origin:"ca753d9d-f8c8-47dd-bd00-8033cd620939"}},"*")}catch(a){z.S.a().b(a)}};z.f.pause=function(){try{window.postMessage({type:"th-SpeechManagerEvent-38697CS",detail:{method:"pause",type:"SP_M_1342_CK",origin:"ca753d9d-f8c8-47dd-bd00-8033cd620939"}},"*")}catch(a){z.S.a().b(a)}};
Rj.prototype.onVoicesResponse=function(a){try{var b=a.data.voicelist;for(a=0;a<b.length;a++)this.Yd[b[a].voice]=b[a].description}catch(c){z.S.a().b(c)}};Rj.prototype.onWord=function(a){try{var b=[];b.push(a.word);z.T.a().k("onthAPIWord",b)}catch(c){z.S.a().b(c)}};Rj.prototype.onStop=function(){try{z.T.a().k("onthAPIStop",[])}catch(a){z.S.a().b(a)}};Rj.prototype.onForceStop=function(){try{window.texthelp.RW4GC.toolbarHandlerInstance.onstop()}catch(a){z.S.a().b(a)}};
Rj.prototype.onStart=function(){try{z.T.a().k("onthAPIWord",["start"])}catch(a){z.S.a().b(a)}};ak.prototype.isEnabled=function(){try{return this.nj}catch(a){z.S.a().b(a)}};
ak.prototype.start=function(){try{var a=this;this.Lc=new window.webkitSpeechRecognition;this.Lc.iu=!0;this.Lc.Au=!0;var b=z.V.a().I().language.services;this.Lc.lang=z.S.a().Zo(b);this.Lc.onstart=function(){};this.Lc.onresult=function(a){for(var b="",c="",h=a.resultIndex;h<a.results.length;++h)a.results[h].isFinal?b+=a.results[h][0].transcript:c+=a.results[h][0].transcript;0<b.length?(a=[],a.push(b+" "),z.T.a().k("onSpeechRecognitionResponse",a)):0<c.length&&(a=[],a.push(c+" "),z.T.a().k("onSpeechRecognitionInterimResponse",
a))};this.Lc.onerror=function(){};this.Lc.onend=function(){a.nj&&a.Lc.start()};this.nj=this.vh=!0;this.Lc.start()}catch(c){z.S.a().b(c)}};ak.prototype.stop=function(){try{this.nj=!1,this.Lc.stop()}catch(a){z.S.a().b(a)}};z.t("textHelp.webreaderapi.SpeechRecognition",ak);ak.prototype.isEnabled=ak.prototype.isEnabled;ak.prototype.start=ak.prototype.start;ak.prototype.stop=ak.prototype.stop;z.pj.prototype.Um=function(a,b,c,d,e){var g=this.tp;this.Vm=c;this.Eo=d;this.xk=e;this.filename=a;var h=this;bk(g,a,b).then(function(a){var b=a.statusFileLocation;""!=b?(h.so=a.mp3Location,(0,window.setTimeout)(function(){try{ck(h,b)}catch(a){e(a)}},1E3)):e(Error("Status file returned empty."))},function(a){e(a)})};z.t("textHelp.RW4GC.AudioMaker",z.pj);z.pj.prototype.convert=z.pj.prototype.Um;z.Of("WebReaderAPI");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_WebReaderAPI.js