(function(z){
var dm=function(a,b){z.Hc.call(this);this.jh=a||1;this.Ag=b||z.k;this.lk=(0,z.ta)(this.Gt,this);this.fl=(0,z.Vi)()};var em=function(a,b){var c=0;(0,z.Pc)(a,function(a,e,g){b.call(void 0,a,e,g)&&++c},void 0);return c};
var fm=function(){this.Xd=!1;this.Td=z.J("kix-thprediction-popup");this.rj=null;this.lg=this.yh=this.ho=!1;this.jt=z.S.a().bind(this,this.Fr);this.mg=this.qj=null;this.oj=!1;this.co=null;z.T.a().i("onClosePredictionWindow",this.cr,this);z.T.a().i("onOpenPredictionWindow",this.Ir,this);z.T.a().i("onClearPredictionWindow",this.br,this);z.T.a().i("onPredictionKeyDownEvent",this.Mr,this)};
var gm=function(a){var b={},c=window,d="undefined"!=typeof a.href?a.href:String(a);a=b.target||a.target;var e=[],g;for(g in b)switch(g){case "width":case "height":case "top":case "left":e.push(g+"\x3d"+b[g]);break;case "target":case "noreferrer":break;default:e.push(g+"\x3d"+(b[g]?1:0))}g=e.join(",");if(b.noreferrer){if(b=c.open("",a,g))z.D&&-1!=d.indexOf(";")&&(d="'"+d.replace(/'/g,"%27")+"'"),b.opener=null,d=z.Da(d),b.document.write('\x3cMETA HTTP-EQUIV\x3d"refresh" content\x3d"0; url\x3d'+d+'"\x3e'),
b.document.close()}else c.open(d,a,g)};var hm=function(){return(0,z.Nj)("")};var im=function(){return(0,z.Nj)("")};var jm=function(){return(0,z.Nj)('\x3cdiv\x3e\x3cdiv class\x3d"thchitems"\x3e\x3cdiv class\x3d"sortLabel"\x3e\x3cspan data-collecthighlights-dialog\x3d"collecthighlights_sort"\x3eSort highlights by\x3c/span\x3e\x3c/div\x3e\x3cselect id\x3d"sortSelect" class\x3d"thSelect"\x3e\x3coption value\x3d"0" data-collecthighlights-dialog\x3d"collecthighlights_color"\x3ecolor\x3c/option\x3e\x3coption value\x3d"1" data-collecthighlights-dialog\x3d"collecthighlights_position"\x3eposition\x3c/option\x3e\x3c/select\x3e\x3cdiv class\x3d"thchcolors"\x3e\x3cspan data-collecthighlights-dialog\x3d"collecthighlights_to_collect"\x3eColors to collect\x3c/span\x3e\x3cdiv\x3e\x3cdiv id\x3d"thYellowChk" class\x3d"thCollectChks thYellowChk goog-checkbox-checked goog-checkbox" tabindex\x3d"0"\x3e\x3cdiv class\x3d"thRects thYellowRect"\x3e\x3c/div\x3e\x3c/div\x3e\x3cbr/\x3e\x3cdiv id\x3d"thBlueChk" class\x3d"thCollectChks thBlueChk goog-checkbox-checked goog-checkbox" tabindex\x3d"0"\x3e\x3cdiv class\x3d"thRects thBlueRect"\x3e\x3c/div\x3e\x3c/div\x3e\x3cbr/\x3e\x3cdiv id\x3d"thGreenChk" class\x3d"thCollectChks thGreenChk goog-checkbox-checked goog-checkbox" tabindex\x3d"0"\x3e\x3cdiv class\x3d"thRects thGreenRect"\x3e\x3c/div\x3e\x3c/div\x3e\x3cbr/\x3e\x3cdiv id\x3d"thPinkChk" class\x3d"thCollectChks thPinkChk goog-checkbox-checked goog-checkbox" tabindex\x3d"0"\x3e\x3cdiv class\x3d"thRects thPinkRect"\x3e\x3c/div\x3e\x3c/div\x3e\x3cbr/\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"gdwr-modal-dialog-buttons gdwr-collect-dialog-buttons"/\x3e\x3c/div\x3e')};
var km=function(){return(0,z.Nj)('\x3cdiv\x3e\x3cdiv class\x3d"gdwr-voicenote-dialog-content"\x3e\x3cscript id\x3d\'thRecordWorker\' type\x3d\'javascript/worker\'\x3e\x3c/script\x3e\x3cdiv class\x3d"round-mic-record"\x3e\x3cdiv id\x3d"thRecorderPH" class\x3d"thRecorderPH"\x3e\x3c/div\x3e\x3ccanvas class\x3d"thMicLevelCanvas" width\x3d"134px" height\x3d"134px"\x3e\x3c/canvas\x3e\x3cdiv class\x3d"round-mic-record-circle"\x3e\x3cdiv class\x3d"round-mic-record-circle-img"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"voicenote-message-spacer"\x3e\x3c/div\x3e\x3cdiv class\x3d"round-playback"\x3e\x3cdiv class\x3d"round-playback-circle"\x3e\x3ccanvas class\x3d"round-playback-canvas"\x3e\x3c/canvas\x3e\x3cdiv class\x3d"round-micplayback-circle-img play"\x3e\x3c/div\x3e\x3cdiv class\x3d"round-countdownclock"\x3e1:00\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cspan class\x3d"gdwr-dialog-title-close gdwr-voicenote-dialog-close" role\x3d"button" tabindex\x3d"0" aria-label\x3d"Close"\x3e\x3c/span\x3e\x3cdiv class\x3d"gdwr-voicenote-add-button" role\x3d"button" tabindex\x3d"0" aria-label\x3d"Add voice note"\x3e\x3cdiv class\x3d"gdwr-dialog-title-add gdwr-voicenote-add"\x3e\x3c/div\x3e\x3cdiv class\x3d"gdwr-voicenote-add-image" data-voicenote-dialog\x3d\'voicenote_insert\'\x3eInsert\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"thVNload-bar"\x3e\x3cdiv class\x3d"thVNbar"\x3e\x3c/div\x3e\x3cdiv class\x3d"thVNbar"\x3e\x3c/div\x3e\x3cdiv class\x3d"thVNbar"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv\x3e')};
var lm=function(){return(0,z.Nj)('\x3cdiv\x3e\x3cdiv class\x3d"ch-notification"\x3e\x3cdiv class\x3d"ch-notification-content"\x3e\x3cdiv class\x3d"ch-notification-heading" data-collect-highlights-notification\x3d\'collect_highlights_notification\'\x3eCollecting highlights\x3c/div\x3e\x3cdiv class\x3d"ch-notification-msg" data-collect-highlights-notification\x3d\'collect_highlights_notification_text\'\x3eA new document containing your highlights is being created.\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};
var mm=function(){return(0,z.Nj)('\x3cdiv\x3e\x3cdiv class\x3d"vl-notification"\x3e\x3cdiv class\x3d"vl-notification-content"\x3e\x3cdiv class\x3d"vl-notification-heading" data-vocab-notification\x3d\'vocab_notification\'\x3eVocabulary List\x3c/div\x3e\x3cdiv class\x3d"vl-notification-msg" data-vocab-notification\x3d\'vocab_notification_text\'\x3eA new document containing your vocabulary list is being created.\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var nm=function(){return(0,z.Nj)('\x3cdiv\x3e\x3cdiv class\x3d"mn-notification"\x3e\x3cdiv class\x3d"mn-notification-content"\x3e\x3cdiv class\x3d"mn-notification-heading"\x3eNotification\x3c/div\x3e\x3cdiv class\x3d"mn-notification-msg"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};
var om=function(){return(0,z.Nj)('\x3cthRWGDns:thUIPred id\x3d"kix-thprediction-popup" class\x3d"kix-thprediction-popup" style\x3d "display: block; left: 0px; top: 0px;"\x3e\x3cdiv class\x3d"kix-thPredictions"\x3e\x3c/div\x3e\x3cdiv class\x3d"thPredictionArrow thPredictionArrowup" style\x3d"left: 20px; "\x3e\x3cdiv class\x3d"thPredictionArrowimplBefore"\x3e\x3c/div\x3e\x3cdiv class\x3d"thPredictionArrowimplAfter"\x3e\x3c/div\x3e\x3c/thRWGDns:thUIPred\x3e')};z.Kk=function(){return(0,z.Nj)('\x3cthRWGDns:thVoiceNoteOverlay class\x3d"kix-thvoicenote-overlay" style\x3d "visibility: hidden; left: 0px; top: 0px; width:0px; height:0px; background: ; position: absolute;"\x3e\x3cdiv class\x3d"thVNPlayback" id\x3d"thVNPlayback" data-percent\x3d"0" data-line\x3d"4"\x3e\x3caudio source class\x3d"thVNAudio" type\x3d"audio/wav"\x3e\x3c/audio\x3e\x3cdiv class\x3d"thVNButton"\x3e\x3cdiv class\x3d"thVNIcon thVNPlay"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/thRWGDns:thVoiceNoteOverlay\x3e')};
z.mj=function(a){z.Mg.call(this,a);z.U.a();this.gc=this.Yd=null;this.vj=this.tj=this.da=!1;this.V={};this.On=new pm;this.mo=new qm;this.lo=this.uj=null;this.Kn=!1;this.pj=null;this.Yn="";this.nd=null;z.T.a().i("onBarVisibilityChanged",this.ls,this);z.T.a().i("onWordChanged",this.Gs,this);z.T.a().i("onPredictionChanged",this.Lr,this);z.T.a().i("onPredictionManualClose",this.Nr,this);z.T.a().i("onMessagePopup",this.zr,this);z.T.a().i("onUILanguageChanged",this.Lh,this);z.T.a().i("onShowDocsOAuthDialog",
this.Yr,this);z.T.a().i("onCollectStudySkills",this.Js,this);z.T.a().i("onVoiceNotes",this.at,this);z.T.a().i("onVocabTool",this.$s,this);z.T.a().i("onPlay",this.Ss,this);z.T.a().i("onStop",this.Ys,this);z.T.a().i("onPause",this.Ps,this);z.T.a().i("onBlueHighlighter",this.Hs,this);z.T.a().i("onPinkHighlighter",this.Rs,this);z.T.a().i("onYellowHighlighter",this.bt,this);z.T.a().i("onGreenHighlighter",this.Ms,this);z.T.a().i("onClear",this.Is,this);z.T.a().i("onHelp",this.Ns,this);z.T.a().i("onLogo",
this.Os,this);z.T.a().i("onSpeechInput",this.Xs,this);z.T.a().i("onPictureDictionary",this.Qs,this);z.T.a().i("onDictionary",this.Ks,this);z.T.a().i("onTranslator",this.Zs,this);z.T.a().i("onScreenshotReader",this.Vs,this);z.T.a().i("onScreenMasking",this.Us,this);z.T.a().i("onFactFinder",this.Ls,this);z.T.a().i("onSimplify",this.Ws,this);z.T.a().i("onPracticeReadingAloud",this.Ts,this)};var rm=function(){this.Xd=!1;this.jo=z.J("thTooltip");z.J("thTooltipContentId");z.J("thTooltipArrow")};
var sm=function(){this.R=null;this.Xd=!1};var tm=function(){};var um=function(a,b){if(a)for(var c=b?a.firstChild:a.lastChild,d;c&&c.parentNode==a;){d=b?c.nextSibling:c.previousSibling;if(3==c.nodeType){var e=c.nodeValue;if(""==(0,z.Tb)(e))a.removeChild(c);else{c.nodeValue=b?e.replace(/^[\s\xa0]+/,""):e.replace(/[\s\xa0]+$/,"");break}}else break;c=d}};var vm=function(){};
var wm=function(a,b,c,d,e){z.yh.call(this,a,c||vm.a(),d);this.vb(64,!0);this.yj=new z.Fh(null,5);b&&this.Sh(b);this.Tq=null;this.Aa=new dm(500);!z.kj&&!z.lj||z.C("533.17.9")||(this.Yi=!0);this.zp=!0;this.Uq=e||z.di.a()};var xm=function(a,b,c){var d=a.La();c=c?d.q:d.ib;c.call(d,b,"action",a.Sk);c.call(d,b,"close",a.Ok);c.call(d,b,"highlight",a.Rk);c.call(d,b,"unhighlight",a.Uk)};var ym=function(a,b){var c=a.La();(b?c.q:c.ib).call(c,a.f(),"keydown",a.jq)};
var zm=function(a,b){var c=a.f(),d=z.Jg(b,"activedescendant"),d=z.de(b).getElementById(d)||b;if(!d.id){var e=z.Kg.a();d.id=z.Lg(e)}e="";d&&(e=d.id);z.R(c,"activedescendant",e);z.R(c,"owns",d.id)};var Am=function(a){z.Hc.call(this);this.Md=[];Bm(this,a)};var Bm=function(a,b){b&&((0,z.Pc)(b,function(a){Cm(this,a,!1)},a),z.ab(a.Md,b))};var Cm=function(a,b,c){b&&("function"==typeof a.Ko?a.Ko(b,c):"function"==typeof b.pm&&b.pm(c))};
var Dm=function(a,b,c,d,e){wm.call(this,a,b,c,d,e||new z.di("listbox"));this.vk=this.ed();this.$k=null;this.Th("listbox")};var Em=function(a,b){a.ga=new Am;b&&z.Zg(b,function(a){Fm(a);this.ga.Pb(a)},a);Gm(a)};var Gm=function(a){a.ga&&a.La().q(a.ga,"select",a.rq)};var Hm=function(a){var b=a.ef();a.Pa(b?b.cd():a.vk);var c=a.O.sa(a.f());c&&a.G().Aq(c)&&(null==a.$k&&(a.$k=z.Jg(c,"label")),b=(b=b?b.f():null)?z.Jg(b,"label"):a.$k,z.R(c,"label",b),Im(a))};
var Im=function(a){var b=a.O;if(b&&(b=b.sa(a.f()))){var c=a.p;b.id||(b.id=z.Lg(z.Kg.a()));z.Hg(b,"option");z.R(c,"activedescendant",b.id);a.ga&&(c=a.ga.Kk(),c=em(c,function(a){return a instanceof z.ai}),z.R(b,"setsize",c),z.R(b,"posinset",1+a.ga.Ii()))}};var Fm=function(a){a.Th(a instanceof z.ai?"option":"separator")};var pm=function(){sm.call(this);this.Ud=null;this.ql=0;this.xj=!1;this.xl=[];this.$n=this.rh=this.qh=this.ph=this.sh=this.Nq=null;z.T.a().i("onUILanguageChanged",this.Lh,this)};
var qm=function(){sm.call(this);z.T.a().i("onUILanguageChanged",this.Lh,this);this.Ie=this.pf=null;this.Je=!1;this.X=this.mj=null;this.xc=60;this.sj=this.Kc=0;this.jj=!1;this.ij=0;this.Hb=null;this.oo=this.jl=!1;this.nh=this.Ge=0;this.xh=!1;this.Gb=null};
var Jm=function(a){try{var b=z.J("round-mic-record-circle");if(null!=b){var c=z.J("round-mic-record-circle-img");if(null!=c){(0,window.clearTimeout)(a.sj);a.xc=60;var d=z.J("round-countdownclock");if(null!==d){var e=Math.floor(a.xc/60),g=a.xc-60*e,h=e+":"+g;10>g&&(h=e+":0"+g);z.ze(d,h)}a.Ie.stop();a.Ie.exportMonoWAV(a.Hq);a.X.clearRect(-300,-300,800,800);a.Ya(a.X,"#efefef",4,1,a.Kc);a.Je=!1;a.Gb.close();a.Gb=null;z.S.a().wa(b,"recording");z.S.a().wa(c,"recording");Km();var l=z.J("voicenote-message-spacer");
z.ze(l,"");var m=z.J("thRecorderPH");z.O(m,"display","none")}}}catch(n){z.S.a().b(n)}};
var Xm=function(a){try{var b=z.J("round-mic-record-circle");if(null!=b){var c=z.J("round-mic-record-circle-img");if(null!=c){var d=z.J("round-micplayback-circle-img");Ym(a);a.Ya(a.X,"#efefef",4,1,a.Kc);null==a.Gb&&(a.Gb=new window.AudioContext,window.navigator.tn({audio:!0},a.Mq,function(){}));a.jl||(z.S.a().Q(z.J("gdwr-voicenote-add-button"),"enabled"),a.jl=!0);z.S.a().Q(b,"recording");z.S.a().Q(c,"recording");z.S.a().S(d,"stop")&&z.S.a().wa(d,"stop");z.S.a().S(d,"play")||z.S.a().Q(d,"play");a.sj=
(0,window.setTimeout)(a.Nn,0);Zm();var e=z.J("voicenote-message-spacer");z.ze(e,z.U.a().ha("voicenote_recording"));var g=z.J("thRecorderPH");z.O(g,"display","block")}}}catch(h){z.S.a().b(h)}};var $m=function(a){try{a.jj=!0,a.Ge=0,a.nh=0,a.xh=!1,a.Gb=null,a.Hb.play(),a.ij=(0,window.setTimeout)(a.Mn,0)}catch(b){z.S.a().b(b)}};var Ym=function(a){try{a.jj=!1,a.Hb.pause(),a.Hb.currentTime=0,a.Ge=0,a.nh=0,a.xh=!1,a.Gb=null,a.X.clearRect(-300,-300,800,800),a.Ya(a.X,"#efefef",4,1,a.Kc)}catch(b){z.S.a().b(b)}};
var Km=function(){try{var a=z.J("round-micplayback-circle-img"),b=z.J("round-countdownclock");z.O(b,"display","none");z.O(a,"display","block")}catch(c){z.S.a().b(c)}};var Zm=function(){try{var a=z.J("round-micplayback-circle-img"),b=z.J("round-countdownclock");z.O(a,"display","none");z.O(b,"display","block")}catch(c){z.S.a().b(c)}};z.ei.prototype.Kk=z.ca(18,function(){var a=[];z.Zg(this,function(b){a.push(b)});return a});z.ei.prototype.Xg=z.ca(17,function(){return z.Ug(this)});
z.ei.prototype.bf=z.ca(16,function(a){return z.Vg(this,a)});z.ei.prototype.me=z.ca(15,function(a,b){this.Qf(a,b,!0)});z.di.prototype.Bd=z.ca(14,function(a,b){return z.ye(a.f(),b)});z.ei.prototype.Bd=z.ca(13,function(a){if(this.O.Bd(this,a))return!0;for(var b=0,c=z.Ug(this);b<c;b++){var d=z.Vg(this,b);if("function"==typeof d.Bd&&d.Bd(a))return!0}return!1});z.Dh.prototype.pn=z.ca(12,function(){return this.cj});z.qh.prototype.Th=z.ca(11,function(a){this.Nh=a});
z.xi.prototype.Th=z.ca(10,function(a){this.Nh=a});z.Wf.prototype.Dj=z.ca(7,function(){try{if(null===this.F)throw Error("The WebReaderAPI has not been created");this.F.Dj()}catch(a){z.S.a().b(a)}});z.Wf.prototype.Ni=z.ca(6,function(){try{if(null===this.F)throw Error("The WebReaderAPI has not been created");this.F.Ni()}catch(a){z.S.a().b(a)}});z.Wf.prototype.ii=z.ca(5,function(){try{if(null===this.F)throw Error("The WebReaderAPI has not been created");this.F.ii()}catch(a){z.S.a().b(a)}});
z.Wf.prototype.Ac=z.ca(4,function(a){try{if(null===this.F)throw Error("The WebReaderAPI has not been created");this.F.Ac(a)}catch(b){window.console.error(b.stack)}});z.B(dm,z.Hc);z.f=dm.prototype;z.f.enabled=!1;z.f.Aa=null;z.f.setInterval=function(a){this.jh=a;this.Aa&&this.enabled?(this.stop(),this.start()):this.Aa&&this.stop()};
z.f.Gt=function(){if(this.enabled){var a=(0,z.Vi)()-this.fl;0<a&&a<.8*this.jh?this.Aa=this.Ag.setTimeout(this.lk,this.jh-a):(this.Aa&&(this.Ag.clearTimeout(this.Aa),this.Aa=null),this.dispatchEvent("tick"),this.enabled&&(this.Aa=this.Ag.setTimeout(this.lk,this.jh),this.fl=(0,z.Vi)()))}};z.f.start=function(){this.enabled=!0;this.Aa||(this.Aa=this.Ag.setTimeout(this.lk,this.jh),this.fl=(0,z.Vi)())};z.f.stop=function(){this.enabled=!1;this.Aa&&(this.Ag.clearTimeout(this.Aa),this.Aa=null)};
z.f.D=function(){dm.g.D.call(this);this.stop();delete this.Ag};z.f=fm.prototype;
z.f.U=function(a,b){try{if(this.yh=this.lg=!1,this.Xd!==a){if(!this.ho){var c=z.Si(om);z.J(b).appendChild(c);this.Td=z.J("kix-thprediction-popup");this.rj=z.J("kix-thPredictions");var d=z.S.a().bind(this,this.Er);z.E(this.Td,"mouseover",d);var e=z.S.a().bind(this,this.Cr);z.E(this.Td,"mousemove",e);var g=z.S.a().bind(this,this.Br);z.E(this.Td,"mousedown",g);this.ho=!0}a?(z.O(this.Td,"display","block"),z.S.a().nm(!0)):(z.O(this.Td,"display","none"),z.S.a().nm(!1));this.oj=!1;this.Xd=a}}catch(h){z.S.a().b(h)}};
z.f.Er=function(a){this.lg=!1;this.oj?(null!==this.qj&&(0,window.clearTimeout)(this.qj),this.yh=!0,this.mg=a,this.qj=(0,window.setTimeout)(this.jt,300),this.oj=!1):(0,window.clearTimeout)(this.qj)};
z.f.Br=function(a){a.stopPropagation();a.preventDefault();if(!this.lg){this.lg=!0;this.yh=!1;var b="";if("thprediction-word"==this.mg.target.className)b=a.target.innerText.substr(3);else if("thprediction"==this.mg.target.className)b=a.target.firstChild.innerText.substr(3);else return;0!=b.length&&(a=[],a.push(b),z.T.a().k("onPredictionChange",a))}};
z.f.Fr=function(){if(("thprediction-word"===this.mg.target.className||"thprediction"===this.mg.target.className)&&this.yh){var a=[],b=this.mg.target.innerText,b=b.replace(/[;().,*+?^${}"\u201c\u201d<>|[\]\\]/g,"");a.push(b.substr(3));z.T.a().k("onWordChanged",a);a[0]+="-,";z.S.a().Ua.td(a)}};z.f.Cr=function(){this.oj=!0};z.f.cr=function(){try{this.U(!1)}catch(a){z.S.a().b(a)}};
z.f.br=function(a){try{for(var b=z.V.a().I().prediction.results,c="",d=0;d<b;d++)c+='\x3cdiv class\x3d"thprediction"\x3e\x3cdiv class\x3d"thprediction-word"\x3e\x3c/div\x3e\x3c/div\x3e';if(null!=this.rj&&void 0!=this.rj){this.rj.innerHTML=c;var e=z.J(a.position),g=new z.H(e.offsetLeft,e.offsetTop),h=z.pg(e),l=g.y+h.height+e.scrollHeight+6+"px";z.O(this.Td,"left",g.x-h.width-e.scrollWidth-18+"px");z.O(this.Td,"top",l)}}catch(m){z.S.a().b(m)}};z.f.Ir=function(){};
z.f.Mr=function(a){try{if(this.Xd&&!this.lg){this.lg=!0;this.yh=!1;var b=0;a[0].ctrlKey&&(b=48==a[0].keyCode?9:a[0].keyCode-49);b>=this.co.length||(a=[],a.push(this.co[b]),z.T.a().k("onPredictionChange",a))}}catch(c){z.S.a().b(c)}};hm.ie="textHelp.fixedtoolbar.templates.Toolbar";im.ie="textHelp.fixedtoolbar.templates.Tooltip";jm.ie="textHelp.fixedtoolbar.templates.CollectHighlights";km.ie="textHelp.fixedtoolbar.templates.VoiceNote";lm.ie="textHelp.fixedtoolbar.templates.CollectHighlightsNotification";mm.ie="textHelp.fixedtoolbar.templates.VocabNotification";nm.ie="textHelp.fixedtoolbar.templates.MessageNotification";om.ie="textHelp.fixedtoolbar.templates.Prediction";z.Kk.ie="textHelp.fixedtoolbar.templates.VoiceNoteCommentOverlay";z.B(z.mj,z.Mg);z.f=z.mj.prototype;z.f.w=function(){try{z.mj.g.w.call(this);var a=z.S.a().Zf(),b=z.I(z.S.a().ah());if(null!=b){var c=window.document.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=a+"assets/thFixedToolbar.css";this.G().appendChild(b,c);var d=z.Si(hm);this.G().bl(d,window.document.body.firstChild);d=z.Si(im);this.G().appendChild(window.document.body,d);new rm;new fm}}catch(e){z.S.a().b(e)}};z.f.Eb=function(a){try{this.gc=a,this.On.Eb(""),this.mo.Eb("")}catch(b){z.S.a().b(b)}};
z.f.ls=function(){};z.f.Gs=function(a){try{if(!this.Bh){var b=window.document.getElementById("th-RW4GC-picture-dictionary"),c=window.document.getElementById("th-RW4GC-translator"),d=window.document.getElementById("th-RW4GC-prediction");if(null!=window.document.getElementById("th-RW4GC-dictionary")||null!=b||null!=c||null!=d)b="",b=0==a.length?this.gc.ab():a[0],1>b.length||b==this.Yn||(this.Yn=b,window.texthelp.RW4GC.thToolbarStoreInstance.onWordChanged(b))}}catch(e){z.S.a().b(e)}};
z.f.Yr=function(){try{window.open("https://script.google.com/macros/s/AKfycbyPhfA6NYF8msRlb7BF4aR8Ax_JWSDM6eAj3tjR2CpkXUMfjhk/exec","_ntthad")}catch(a){z.S.a().b(a)}};z.f.Rl=function(){};
z.f.Lr=function(a){try{if(z.S.a().Ra("Prediction",!0)){var b=z.S.a().Ma(),c=[];c.push("prediction lookup");c.push(b.Email);c.push(b.Email.split("@")[1]);window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"SendEvent",parameters:c},"*");var d=this.gc.ya();if(0>d.x||0>d.y)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else null==window.document.getElementById("texthelp-prediction-frame")&&(window.texthelp.RW4GC.riot.prediction=window.texthelp.RW4GC.riot.mount("texthelp-prediction")[0]),
window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionUpdate(d,a.parentId,a.words)}}catch(e){z.S.a().b(e)}};z.f.Nr=function(a){try{var b=window.document.getElementsByClassName("th-prediction-image")[0];null!=b&&(this.da=!1,a=[],a.push(this.da),z.T.a().k("onWRPredictionStateChanged",a),z.S.a().wa(b,"enabled"))}catch(c){z.S.a().b(c)}};
z.f.zr=function(a){try{var b=a.m.message,c=a.m.link;if(0!=b.length){var d=z.Si(nm);a="";a=0<c.length?'\x3ca href\x3d"'+c+'" target\x3d"_blank"\x3e'+b+"\x3c/a\x3e":"\x3cdiv\x3e"+b+"\x3c/div\x3e";var e=z.qe(window.document,a);z.J("mn-notification-msg",d).appendChild(e);window.notification({msg:d.innerHTML,delay:1E4,type:"success",animIn:"fadeInRight",animOut:"fadeOutDown"})}}catch(g){z.S.a().b(g)}};
z.f.Lh=function(){try{for(var a=window.document.querySelectorAll("[data-fixedtoolbar-tooltip]"),b=0;b<a.length;b++){var c=a[b].getAttribute("data-fixedtoolbar-tooltip");a[b].setAttribute("tooltip",z.U.a().ha(c))}}catch(d){z.S.a().b(d)}};z.f.Ss=function(){try{z.S.a().Ra("Play",!0)&&(window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*"),z.V.a().Zj(),z.T.a().k("onWRPlay",[]))}catch(a){z.S.a().b(a)}};
z.f.Ys=function(){try{z.S.a().Ra("Stop",!0)&&(window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*"),z.T.a().k("onWRStop",[]))}catch(a){z.S.a().b(a)}};z.f.Ps=function(){try{z.S.a().Ra("Pause",!0)&&(window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*"),z.T.a().k("onWRPause",[]))}catch(a){z.S.a().b(a)}};
z.f.Ls=function(){try{if(z.S.a().Ra("Web Search",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ma();z.S.a().nb()["Web Search"]?z.T.a().k("onWRFactFinder",[]):null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(b){z.S.a().b(b)}};
z.f.Ws=function(){try{if(z.S.a().Ra("Simplify Page",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ma();z.S.a().nb()["Simplify Page"]?z.T.a().k("onWRSimplify",[]):null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(b){z.S.a().b(b)}};z.f.Ts=function(){try{z.T.a().k("onWRPracticeReadingAloud",[])}catch(a){z.S.a().b(a)}};
z.f.Ks=function(){try{window.texthelp.RW4GC.currentDictionary={word:this.gc.ab()};window.texthelp.RW4GC.riot.dictionary=window.texthelp.RW4GC.riot.mount("texthelp-dictionary",window.texthelp.RW4GC.currentDictionary)[0];var a=z.S.a().ua();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"dictionary",label:a.split("@")[1]}},"*")}catch(b){z.S.a().b(b)}};
z.f.Zs=function(){try{window.texthelp.RW4GC.currentTranslator={word:this.gc.ab()};window.texthelp.RW4GC.riot.translator=window.texthelp.RW4GC.riot.mount("texthelp-translator",window.texthelp.RW4GC.currentTranslator)[0];var a=z.S.a().ua();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"translate",label:a.split("@")[1]}},"*")}catch(b){z.S.a().b(b)}};
z.f.at=function(){try{var a=z.S.a().Ma();if(z.S.a().nb()["Voice Note"]){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");this.mo.Uh();var b=z.S.a().ua();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"voice note",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}catch(c){z.S.a().b(c)}};
z.f.Qs=function(){try{window.texthelp.RW4GC.currentPictureDictionary={word:this.gc.ab()};window.texthelp.RW4GC.riot.pictureDictionary=window.texthelp.RW4GC.riot.mount("texthelp-picture-dictionary",window.texthelp.RW4GC.currentPictureDictionary)[0];var a=z.S.a().ua();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"picture dictionary",label:a.split("@")[1]}},"*")}catch(b){z.S.a().b(b)}};
z.f.bt=function(){try{if(z.S.a().Ra("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ma();if(z.S.a().nb().Highlights){this.gc.ck();var b=z.S.a().ua();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"yellow study skills",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(c){z.S.a().b(c)}};
z.f.Hs=function(){try{if(z.S.a().Ra("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ma();if(z.S.a().nb().Highlights){this.gc.ii();var b=z.S.a().ua();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"blue study skills",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(c){z.S.a().b(c)}};
z.f.Ms=function(){try{if(z.S.a().Ra("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ma();if(z.S.a().nb().Highlights){this.gc.Ni();var b=z.S.a().ua();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"green study skills",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(c){z.S.a().b(c)}};
z.f.Rs=function(){try{if(z.S.a().Ra("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ma();if(z.S.a().nb().Highlights){this.gc.Dj();var b=z.S.a().ua();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"pink study skills",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(c){z.S.a().b(c)}};
z.f.Is=function(){try{if(z.S.a().Ra("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().Ma();if(z.S.a().nb().Highlights){this.gc.mc();var b=z.S.a().ua();if(null==b)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"clear study skills",label:b.split("@")[1]}},"*")}else null!==a.Redirect&&window.open(a.Redirect,"_exthtb").focus()}}catch(c){z.S.a().b(c)}};
z.f.Os=function(){try{window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");gm("https://www.texthelp.com/products/read-write/read-write-for-google/");var a=z.S.a().ua();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"logo",label:a.split("@")[1]}},"*")}catch(b){z.S.a().b(b)}};
z.f.Ns=function(){try{window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");gm("https://text.help/DNYrdP");var a=z.S.a().ua();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"help",label:a.split("@")[1]}},"*")}catch(b){z.S.a().b(b)}};
z.f.Vs=function(){try{if(z.S.a().Ra("Screenshot Reader",!0)){var a=z.S.a().ua();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"screenshot reader",label:a.split("@")[1]}},"*");var b=z.V.a().I();window.thPostMessage({method:"thCheckExtension",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo",Lang:b.language.services,defaultsettings:b.speechoptions}},"*")}}catch(c){z.S.a().b(c)}};
z.f.Js=function(){try{if(z.S.a().Ra("Highlights",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");this.On.Uh();var a=z.S.a().ua();if(null==a)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:a,action:"collect highlights",label:a.split("@")[1]}},"*")}}catch(b){z.S.a().b(b)}};
z.f.$s=function(){try{if(z.S.a().Ra("Vocabulary List",!0)){window.thPostMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");var a=z.S.a().bind(this,this.ns),b=[];b.push("#FFFF00");b.push("#00FFFF");b.push("#ADFF2F");b.push("#FF00FF");z.S.a().Ua.Xe(a,b,"untitled Vocabulary List");var c=z.S.a().ua();if(null==c)return null;window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:c,action:"vocab words",
label:c.split("@")[1]}},"*");for(var d=z.Si(mm),e=d.querySelectorAll("[data-vocab-notification]"),a=0;a<e.length;a++){var g=e[a].getAttribute("data-vocab-notification");e[a].innerText=z.U.a().ha(g)}this.lo=window.notification({msg:d.innerHTML,delay:5E3,type:"success",animIn:"fadeInRight",animOut:"fadeOutDown"})}}catch(h){z.S.a().b(h)}};
z.f.Xs=function(){try{if(z.S.a().Ra("Talk\x26Type",!0)){window.postMessage({method:"thStopScreenShotReaderSpeech",type:"1757FROM_PAGERW4G",payload:{ChromeExtId:"enfolipbjmnmleonhhebhalojdpcpdoo"}},"*");this.vj=!this.vj;var a=z.S.a().Ua.Ab();void 0===a.custom||void 0===a.custom.screenshotreadertoogle||a.custom.screenshotreadertoogle||(this.vj=!0);if(this.vj){this.gc.Xc();b=z.S.a().ua();if(null==b)return null;c=b.split("@")[1];window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,
action:"speech input",label:c}},"*")}else this.gc.Zc()}else{var b=z.S.a().ua();if(null==b)return null;var c=b.split("@")[1];window.thPostMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:b,action:"speech input",label:c}},"*")}}catch(d){z.S.a().b(d)}};z.f.Us=function(){try{if(z.S.a().Ra("Screen Masking",!0)){this.tj=!this.tj;var a=window.document.getElementsByClassName("th-screenmasking-image")[0];this.tj?z.S.a().Q(a,"enabled"):z.S.a().wa(a,"enabled");window.textHelp.thScreenMasking.screenmasking.toggle(this.tj)}}catch(b){z.S.a().b(b)}};
z.f.ns=function(){try{this.lo.remove()}catch(a){z.S.a().b(a)}};z.f.Ra=function(a,b){try{var c=z.S.a().Ma();if(void 0!==c.lt)return!0;var d=z.S.a().nb();z.V.a().Zj();return d[a]?!0:(null!==c.Redirect&&b&&window.open(c.Redirect,"_exthtb").focus(),!1)}catch(e){z.S.a().b(e)}};rm.prototype.U=function(a){try{this.Xd!==a&&(a?z.S.a().wa(this.jo,"thTooltipHide"):z.S.a().Q(this.jo,"thTooltipHide"),this.Xd=a)}catch(b){z.S.a().b(b)}};sm.prototype.Eb=function(a){try{this.Oq=a,this.R=new z.xi("gdwr-modal-dialog",!0),z.Ei(this.R),z.Gi(this.R),z.S.a().Q(z.Ci(this.R),"gdwr-"+this.Oq+"-dialog")}catch(b){z.S.a().b(b)}};sm.prototype.show=function(){this.R.U(!0);this.Xd=!0};sm.prototype.W=function(){try{return this.Xd}catch(a){z.S.a().b(a)}};z.B(tm,z.nh);z.ga(tm);z.f=tm.prototype;z.f.w=function(a){var b={"class":"goog-inline-block "+this.dd(a).join(" ")},b=a.G().w("div",b,this.vi(a.ed(),a.G()));this.Rj(b,a.eh());z.ih(this,a,b);return b};z.f.se=function(){return"button"};z.f.sa=function(a){return a&&a.firstChild&&a.firstChild.firstChild};z.f.vi=function(a,b){return b.w("div","goog-inline-block "+(this.P()+"-outer-box"),b.w("div","goog-inline-block "+(this.P()+"-inner-box"),a))};z.f.$b=function(a){return"DIV"==a.tagName};
z.f.$=function(a,b){um(b,!0);um(b,!1);var c;a:{c=a.G().on(b);var d=this.P()+"-outer-box";if(c&&z.bh(c,d)&&(c=a.G().on(c),d=this.P()+"-inner-box",c&&z.bh(c,d))){c=!0;break a}c=!1}c||b.appendChild(this.vi(b.childNodes,a.G()));z.dh(b,["goog-inline-block",this.P()]);return tm.g.$.call(this,a,b)};z.f.P=function(){return"goog-custom-button"};z.B(vm,tm);z.ga(vm);z.f=vm.prototype;z.f.sa=function(a){return vm.g.sa.call(this,a&&a.firstChild)};z.f.$=function(a,b){var c=z.fe(window.document,"*","goog-menu",b)[0];if(c){z.tg(c,!1);z.de(c).body.appendChild(c);var d=new z.ei;d.$(c);a.Sh(d)}return vm.g.$.call(this,a,b)};z.f.vi=function(a,b){return vm.g.vi.call(this,[this.createCaption(a,b),b.w("div","goog-inline-block "+(this.P()+"-dropdown"),"\u00a0")],b)};
z.f.createCaption=function(a,b){return b.w("div","goog-inline-block "+(this.P()+"-caption"),a)};z.f.P=function(){return"goog-menu-button"};z.B(wm,z.yh);z.f=wm.prototype;z.f.Yi=!1;z.f.nt=!1;z.f.vt=!1;z.f.pa=function(){wm.g.pa.call(this);ym(this,!0);this.j&&xm(this,this.j,!0);z.R(this.p,"haspopup",!!this.j)};z.f.Ta=function(){wm.g.Ta.call(this);ym(this,!1);if(this.j){this.Fa(!1);this.j.Ta();xm(this,this.j,!1);var a=this.j.f();a&&z.ue(a)}};z.f.D=function(){wm.g.D.call(this);this.j&&(this.j.ca(),delete this.j);delete this.ft;this.Aa.ca()};
z.f.we=function(a){wm.g.we.call(this,a);this.lf()&&(this.Fa(!this.Hc(),a),this.j&&(a=this.Hc(),this.j.rd=a))};z.f.xe=function(a){wm.g.xe.call(this,a);this.j&&!this.lf()&&(this.j.rd=!1)};z.f.Me=function(){this.setActive(!1);return!0};z.f.eq=function(a){this.j&&this.j.W()&&!this.Bd(a.target)&&this.Fa(!1)};z.f.Bd=function(a){return a&&z.ye(this.f(),a)||this.j&&this.j.Bd(a)||!1};
z.f.Fc=function(a){if(32==a.keyCode){if(a.preventDefault(),"keyup"!=a.type)return!0}else if("key"!=a.type)return!1;if(this.j&&this.j.W()){var b=13==a.keyCode||32==a.keyCode,c=this.j.bc(a);return 27==a.keyCode||b&&this.zp?(this.Fa(!1),!0):c}return 40==a.keyCode||38==a.keyCode||32==a.keyCode||13==a.keyCode?(this.Fa(!0,a),!0):!1};z.f.Sk=function(){this.Fa(!1)};z.f.oq=function(){this.lf()||this.Fa(!1)};z.f.ff=function(a){this.Yi||this.Fa(!1);wm.g.ff.call(this,a)};
z.f.df=function(){this.j||this.Sh(new z.ei(this.G(),this.Uq));return this.j||null};z.f.Sh=function(a){var b=this.j;if(a!=b&&(b&&(this.Fa(!1),this.ba&&xm(this,b,!1),delete this.j),this.ba&&z.R(this.p,"haspopup",!!a),a)){this.j=a;z.Qg(a,this);a.U(!1);var c=this.Yi;(a.di=c)&&a.he(!0);this.ba&&xm(this,a,!0)}return b};z.f.Pb=function(a){this.df().Ve(a,!0)};z.f.me=function(a,b){this.df().Qf(a,b,!0)};z.f.removeItem=function(a){(a=this.df().removeChild(a,!0))&&a.ca()};
z.f.bf=function(a){return this.j?z.Vg(this.j,a):null};z.f.Xg=function(){return this.j?z.Ug(this.j):0};z.f.U=function(a,b){var c=wm.g.U.call(this,a,b);c&&!this.W()&&this.Fa(!1);return c};z.f.Ob=function(a){wm.g.Ob.call(this,a);this.isEnabled()||this.Fa(!1)};
z.f.Fa=function(a,b){wm.g.Fa.call(this,a);if(this.j&&!!(this.Z&64)==a){if(a){if(!this.j.ba)if(this.nt){var c;c=this.f();(c=void 0!=c.nextElementSibling?c.nextElementSibling:z.we(c.nextSibling))?z.Sg(this.j,c.parentNode,c):this.j.na(this.f().parentNode)}else this.j.na();this.ip=z.kg(this.f());this.Jm=z.rg(this.f());this.Ej();c=!!b&&(13==b.keyCode||32==b.keyCode);this.j.Wc(b&&(40==b.keyCode||38==b.keyCode)||c&&this.vt?0:-1)}else{this.setActive(!1);this.j.rd=!1;if(c=this.f())z.R(c,"activedescendant",
""),z.R(c,"owns","");null!=this.Bj&&(this.Bj=void 0,(c=this.j.f())&&z.og(c,"",""))}this.j.U(a,!1,b);if(!this.Cd){c=this.La();var d=a?c.q:c.ib;d.call(c,z.Me(this.G()),"mousedown",this.eq,!0);this.Yi&&d.call(c,this.j,"blur",this.oq);d.call(c,this.Aa,"tick",this.cs);a?this.Aa.start():this.Aa.stop()}}this.j&&this.j.f()&&this.j.p.removeAttribute("aria-hidden")};
z.f.Ej=function(){if(this.j.ba){var a=this.yj;this.yj.element=this.ft||this.f();var b=this.j.f();this.j.W()||(b.style.visibility="hidden",z.tg(b,!0));!this.Bj&&this.yj.pn&&this.yj.cj&32&&(this.Bj=z.pg(b));a.vg(b,a.ui^1,this.Tq,this.Bj);this.j.W()||(z.tg(b,!1),b.style.visibility="visible")}};
z.f.cs=function(){var a=z.rg(this.f()),b=z.kg(this.f()),c=this.Jm;(c=!(c==a||c&&a&&c.left==a.left&&c.width==a.width&&c.top==a.top&&c.height==a.height))||(c=this.ip,c=!(c==b||c&&b&&c.top==b.top&&c.right==b.right&&c.bottom==b.bottom&&c.left==b.left));c&&(this.Jm=a,this.ip=b,this.Ej())};z.f.Rk=function(a){(a=a.target.f())&&zm(this,a)};z.f.jq=function(a){z.jh(this,32)&&this.Ha()&&this.j&&this.j.W()&&a.stopPropagation()};
z.f.Uk=function(){if(!z.Oh(this.j)){var a=this.f();z.R(a,"activedescendant","");z.R(a,"owns","")}};z.f.Ok=function(a){if(this.Hc()&&a.target instanceof z.ai){a=a.target;var b=a.f();a.W()&&a.Z&2&&null!=b&&zm(this,b)}};z.oh("goog-menu-button",function(){return new wm(null)});z.B(Am,z.Hc);z.f=Am.prototype;z.f.ge=null;z.f.Ko=null;z.f.Xg=function(){return this.Md.length};z.f.bf=function(a){return this.Md[a]||null};z.f.Pb=function(a){this.me(a,this.Xg())};z.f.me=function(a,b){a&&(Cm(this,a,!1),z.bb(this.Md,b,0,a))};z.f.removeItem=function(a){a&&z.Ya(this.Md,a)&&a==this.ge&&(this.ge=null,this.dispatchEvent("select"))};z.f.ef=function(){return this.ge};z.f.Kk=function(){return z.$a(this.Md)};z.f.Hf=function(a){a!=this.ge&&(Cm(this,this.ge,!1),this.ge=a,Cm(this,a,!0));this.dispatchEvent("select")};
z.f.Ii=function(){var a=this.ge;return a?(0,z.Wa)(this.Md,a):-1};z.f.Oo=function(a){this.Hf(this.bf(a))};z.f.clear=function(){var a=this.Md;if(!z.ia(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0;this.ge=null};z.f.D=function(){Am.g.D.call(this);delete this.Md;this.ge=null};z.B(Dm,wm);z.f=Dm.prototype;z.f.ga=null;z.f.pa=function(){Dm.g.pa.call(this);Hm(this);Gm(this)};z.f.ac=function(a){Dm.g.ac.call(this,a);(a=this.cd())?(this.vk=a,Hm(this)):this.ef()||this.Oo(0)};z.f.D=function(){Dm.g.D.call(this);this.ga&&(this.ga.ca(),this.ga=null);this.vk=null};z.f.Sk=function(a){this.Hf(a.target);Dm.g.Sk.call(this,a);a.stopPropagation();this.dispatchEvent("action")};z.f.rq=function(){var a=this.ef();Dm.g.gb.call(this,a&&a.ma());Hm(this)};
z.f.Sh=function(a){var b=Dm.g.Sh.call(this,a);a!=b&&(this.ga&&this.ga.clear(),a&&(this.ga?z.Zg(a,function(a){Fm(a);this.ga.Pb(a)},this):Em(this,a)));return b};z.f.Pb=function(a){Fm(a);Dm.g.Pb.call(this,a);this.ga?this.ga.Pb(a):Em(this,this.df());Im(this)};z.f.me=function(a,b){Fm(a);Dm.g.me.call(this,a,b);this.ga?this.ga.me(a,b):Em(this,this.df())};z.f.removeItem=function(a){Dm.g.removeItem.call(this,a);this.ga&&this.ga.removeItem(a)};
z.f.Hf=function(a){if(this.ga){var b=this.ef();this.ga.Hf(a);a!=b&&this.dispatchEvent("change")}};z.f.Oo=function(a){this.ga&&this.Hf(this.ga.bf(a))};z.f.gb=function(a){if(null!=a&&this.ga)for(var b=0,c;c=this.ga.bf(b);b++)if(c&&"function"==typeof c.ma&&c.ma()==a){this.Hf(c);return}this.Hf(null)};z.f.ma=function(){var a=this.ef();return a?a.ma():null};z.f.ef=function(){return this.ga?this.ga.ef():null};z.f.Ii=function(){return this.ga?this.ga.Ii():-1};
z.f.Fa=function(a,b){Dm.g.Fa.call(this,a,b);this.Hc()?this.df().Wc(this.Ii()):Im(this)};z.oh("goog-select",function(){return new Dm(null)});sm.prototype.W=function(){try{return this.R.W()}catch(a){z.S.a().b(a)}};z.B(pm,sm);z.f=pm.prototype;
z.f.Eb=function(){pm.g.Eb.call(this,"collecthighlights");this.Qq=z.S.a().bind(this,this.sr);z.Ki(this.R);var a=z.Si(jm),b=this.R;b.Vj="Collect Highlights";b.hb&&z.ze(b.hb,"Collect Highlights");this.R.Pa(a.innerHTML);this.xl[0]=this.zt;this.xl[1]=this.At;this.Ud=z.J("thSelect");z.E(this.Ud,"mouseup",this.Zr,!1,this);this.sh=new z.Hl;this.sh.$(z.I("thYellowChk"));this.ph=new z.Hl;this.ph.$(z.I("thBlueChk"));this.qh=new z.Hl;this.qh.$(z.I("thGreenChk"));this.rh=new z.Hl;this.rh.$(z.I("thPinkChk"));this.Od=
new z.yh("Cancel");this.Od.Q("gdwr-dialog-button");this.Pd=new z.yh("OK");this.Pd.Q("gdwr-dialog-button");this.Od.na(z.J("gdwr-collect-dialog-buttons"));this.Pd.na(z.J("gdwr-collect-dialog-buttons"));z.E(this.Od,"action",this.Eh,!1,this);z.E(this.Pd,"action",this.Jh,!1,this)};
z.f.Uh=function(){try{this.xj=!0;this.show();var a=z.V.a().I();this.Ud[a.collecthighlights.sortAlgorithm].selected=!0;void 0==a.collecthighlights.yellow&&(a.collecthighlights.yellow=!0);void 0==a.collecthighlights.green&&(a.collecthighlights.green=!0);void 0==a.collecthighlights.blue&&(a.collecthighlights.blue=!0);void 0==a.collecthighlights.pink&&(a.collecthighlights.pink=!0);this.sh.fb(a.collecthighlights.yellow);this.ph.fb(a.collecthighlights.blue);this.qh.fb(a.collecthighlights.green);this.rh.fb(a.collecthighlights.pink)}catch(b){z.S.a().b(b)}};
z.f.Zr=function(){try{if(!this.xj&&this.ql!==this.Ud.selectedIndex){var a=z.V.a().I();a.collecthighlights.sortAlgorithm=this.Ud.selectedIndex;z.V.a().Mj(a);if(!this.xj){try{var b=this.Nq,c=z.I("collecthighlightsFrame");this.ql=this.Ud.selectedIndex;for(var a="\x3cdiv\x3e",d=0;d<b.length;d++){var e=b[d];e.highlights.sort(this.xl[this.ql]);for(var g=0;g<e.highlights.length;g++)var h=e.highlights[g],a=a+('\x3cspan style\x3d"background-color:'+h.bgcolor+";color:"+h.fgcolor+';"\x3e'+h.text+"\x3c/span\x3e\x3cbr\x3e\x3cbr\x3e");
a+="\x3cdiv\x3e"+e.title+"\x3c/div\x3e\x3cdiv\x3e"+e.author+"\x3cbr\x3e"+e.link+"\x3c/div\x3e\x3c/div\x3e"}c.contentWindow.postMessage("content:"+(a+"\x3c/div\x3e"),z.S.a().Zf());this.xj=!1}catch(l){z.S.a().b(l)}window.document.createRange().selectNodeContents(window.document.body)}}}catch(m){z.S.a().b(m)}};z.f.zt=function(a,b){try{return a.colorOrder>b.colorOrder?1:a.colorOrder<b.colorOrder?-1:0}catch(c){z.S.a().b(c)}};z.f.At=function(a,b){try{return a.start>b.start?1:a.start<b.start?-1:0}catch(c){z.S.a().b(c)}};
z.f.Eh=function(){try{this.R.U(!1)}catch(a){z.S.a().b(a)}};
z.f.Jh=function(){try{this.R.U(!1);var a=z.V.a().I();a.collecthighlights.sortAlgorithm=this.Ud.selectedIndex;a.collecthighlights.yellow=this.sh.Tb();a.collecthighlights.green=this.qh.Tb();a.collecthighlights.blue=this.ph.Tb();a.collecthighlights.pink=this.rh.Tb();z.V.a().Mj(a);var a=1,b=this.Ud[this.Ud.selectedIndex].value;"0"===b?a=2:"1"===b&&(a=1);b=[];this.sh.Tb()&&b.push("#FFFF00");this.ph.Tb()&&b.push("#00FFFF");this.qh.Tb()&&b.push("#ADFF2F");this.rh.Tb()&&b.push("#FF00FF");z.S.a().Ua.Ac(this.Qq,
a,b,"Highlights Untitled");for(var c=z.Si(lm),d=c.querySelectorAll("[data-collect-highlights-notification]"),a=0;a<d.length;a++){var e=d[a].getAttribute("data-collect-highlights-notification");d[a].innerText=z.U.a().ha(e)}this.$n=window.notification({msg:c.innerHTML,type:"success",animIn:"fadeInRight",delay:5E3,animOut:"fadeOutDown"})}catch(g){z.S.a().b(g)}};z.f.sr=function(){try{this.$n.remove()}catch(a){z.S.a().b(a)}};
z.f.Lh=function(){try{var a=this.R,b=z.U.a().ha("collect_highlights_dialog_heading");a.Vj=b;a.hb&&z.ze(a.hb,b);for(var c=window.document.querySelectorAll("[data-collecthighlights-dialog]"),a=0;a<c.length;a++){var d=c[a].getAttribute("data-collecthighlights-dialog");c[a].innerText=z.U.a().ha(d)}var e=z.U.a().ha("dialog_OK");this.Pd.Pa(e);var g=z.U.a().ha("dialog_Cancel");this.Od.Pa(g)}catch(h){z.S.a().b(h)}};z.B(qm,sm);z.f=qm.prototype;
z.f.Eb=function(){qm.g.Eb.call(this,"voicenote");var a=window.document.getElementById("thSpeechStreamTBPlaceHolder"),b=a.getAttribute("data-root");if(!this.oo){var c=window.document.createElement("script");c.src=b+"assets/recorder.js";c.async=!0;c.id="thRecordWorker";c.onload=c.onreadystatechange=function(){this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(c.onload=c.onreadystatechange=null,a.removeChild(c))};c.textContent='function init(e){sampleRate\x3de.sampleRate}function record(e){recBuffersL.push(e[0]),recBuffersR.push(e[1]),recLength+\x3de[0].length}function exportWAV(e){var t\x3dmergeBuffers(recBuffersL,recLength),r\x3dmergeBuffers(recBuffersR,recLength),n\x3dinterleave(t,r),a\x3dencodeWAV(n),f\x3dnew Blob([a],{type:e});this.postMessage(f)}function exportMonoWAV(e){var t\x3dmergeBuffers(recBuffersL,recLength),r\x3dencodeWAV(t,!0),n\x3dnew Blob([r],{type:e});this.postMessage(n)}function getBuffers(){var e\x3d[];e.push(mergeBuffers(recBuffersL,recLength)),e.push(mergeBuffers(recBuffersR,recLength)),this.postMessage(e)}function clear(){recLength\x3d0,recBuffersL\x3d[],recBuffersR\x3d[]}function mergeBuffers(e,t){for(var r\x3dnew Float32Array(t),n\x3d0,a\x3d0;a\x3ce.length;a++)r.set(e[a],n),n+\x3de[a].length;return r}function interleave(e,t){for(var r\x3de.length+t.length,n\x3dnew Float32Array(r),a\x3d0,f\x3d0;r\x3ea;)n[a++]\x3de[f],n[a++]\x3dt[f],f++;return n}function interleaveForceMono(e){for(var t\x3de.length,r\x3dnew Float32Array(t),n\x3d0,a\x3d0;t\x3en;)r[n++]\x3d.25*(e[a++]+e[a++]+e[a++]+e[a++]);return r}function floatTo16BitPCM(e,t,r){for(var n\x3d0;n\x3cr.length;n++,t+\x3d2){var a\x3dMath.max(-1,Math.min(1,r[n]));e.setInt16(t,0\x3ea?32768*a:32767*a,!0)}}function writeString(e,t,r){for(var n\x3d0;n\x3cr.length;n++)e.setUint8(t+n,r.charCodeAt(n))}function encodeWAV(e,t){var r\x3dnew ArrayBuffer(44+2*e.length),n\x3dnew DataView(r);return writeString(n,0,"RIFF"),n.setUint32(4,32+2*e.length,!0),writeString(n,8,"WAVE"),writeString(n,12,"fmt "),n.setUint32(16,16,!0),n.setUint16(20,1,!0),n.setUint16(22,t?1:2,!0),n.setUint32(24,sampleRate,!0),n.setUint32(28,2*sampleRate,!0),n.setUint16(32,2,!0),n.setUint16(34,16,!0),writeString(n,36,"data"),n.setUint32(40,2*e.length,!0),floatTo16BitPCM(n,44,e),n}var recLength\x3d0,recBuffersL\x3d[],recBuffersR\x3d[],sampleRate;this.onmessage\x3dfunction(e){switch(e.data.command){case"init":init(e.data.config);break;case"record":record(e.data.buffer);break;case"exportWAV":exportWAV(e.data.type);break;case"exportMonoWAV":exportMonoWAV(e.data.type);break;case"getBuffers":getBuffers();break;case"clear":clear()}};';a.appendChild(c);
this.oo=!0}z.Ki(this.R);b=z.Si(km);this.R.Pa(b.innerHTML);b=z.J("gdwr-modal-dialog-title",this.R.f());z.O(b,"visibility","hidden");this.Hb=new window.Audio;z.E(z.J("gdwr-voicenote-add-button"),"click",this.Jh,!1,this);z.E(z.J("gdwr-voicenote-dialog-close"),"click",this.Eh,!1,this);this.Mq=z.S.a().bind(this,this.Ct);this.Iq=z.S.a().bind(this,this.Tp);z.S.a();this.Hq=z.S.a().bind(this,this.Yq);this.Mn=z.S.a().bind(this,this.Vl);this.Ln=z.S.a().bind(this,this.Ul);z.S.a();this.Lq=z.S.a().bind(this,this.Rr);
this.Nn=z.S.a().bind(this,this.Sr);this.Kq=z.S.a().bind(this,this.Jr);this.Jq=z.S.a().bind(this,this.Sl);z.E(z.J("round-mic-record"),"click",this.Lq,!1,this);z.E(z.J("round-micplayback-circle-img"),"click",this.Kq,!1,this);z.E(z.J("round-playback-canvas"),"mouseup",this.Jq,!0,this)};
z.f.Uh=function(){try{this.R.U(!0);this.jm();var a=z.J("thVNload-bar",this.R.f());z.O(a,"display","none");null==this.Gb&&(window.AudioContext=window.AudioContext||window.webkitAudioContext,window.navigator.tn=window.navigator.tn||window.navigator.webkitGetUserMedia,window.URL=window.URL||window.webkitURL,this.Hb.onended=this.Hm);if(null==this.X){var b=z.J("round-playback-canvas");b.width=b.height;this.X=b.getContext("2d");this.X.translate(b.height/2,b.height/2);this.X.rotate(-.5*Math.PI);this.X.translate(.5,
.5);this.Kc=b.height-20;this.Ya(this.X,"#efefef",4,1,this.Kc);b=z.J("thMicLevelCanvas");this.Sd=b.getContext("2d");this.Hb.onended=this.Ln}null==this.Hb.onended&&(this.Hb.onended=this.Ln)}catch(c){z.S.a().b(c)}};z.f.Eh=function(){try{this.Je&&Jm(this);if(this.jj){var a=z.J("round-micplayback-circle-img");z.S.a().wa(a,"stop");z.S.a().Q(a,"play");Ym(this)}this.R.U(!1);this.Ie=this.Gb=null}catch(b){z.S.a().b(b)}};
z.f.Jh=function(){try{if(this.Je)try{var a=z.J("round-mic-record-circle");if(null!=a){var b=z.J("round-mic-record-circle-img");if(null!=b){(0,window.clearTimeout)(this.sj);this.xc=60;var c=z.J("round-countdownclock");if(null!==c){var d=Math.floor(this.xc/60),e=this.xc-60*d,g=d+":"+e;10>e&&(g=d+":0"+e);z.ze(c,g)}this.Ie.stop();this.X.clearRect(-300,-300,800,800);this.Ya(this.X,"#efefef",4,1,this.Kc);this.Je=!1;this.Gb.close();this.Gb=null;z.S.a().wa(a,"recording");z.S.a().wa(b,"recording");Km();var h=
z.J("voicenote-message-spacer");z.ze(h,"");var l=z.J("thRecorderPH");z.O(l,"display","none")}}}catch(m){z.S.a().b(m)}if(this.jl){var n=z.J("thVNload-bar",this.R.f());z.O(n,"display","block");this.Ie.exportMonoWAV(z.S.a().bind(this,this.lr))}}catch(p){z.S.a().b(p)}};
z.f.Sr=function(){try{var a=z.J("round-countdownclock");60==this.xc&&z.O(a,"display","block");--this.xc;var b=100/60*this.xc,c=Math.floor(this.xc/60),d=this.xc-60*c,e=c+":"+d;10>d&&(e=c+":0"+d);this.X.clearRect(-300,-300,800,800);this.Ya(this.X,"#efefef",4,1,this.Kc);0<b&&100>b&&this.Ya(this.X,"#FD3269",4,b/100,this.Kc);z.ze(a,e);0==this.xc?Jm(this):this.sj=(0,window.setTimeout)(this.Nn,1E3)}catch(g){z.S.a().b(g)}};
z.f.Jr=function(){try{var a=z.J("round-micplayback-circle-img");z.S.a().S(a,"play")?(z.S.a().wa(a,"play"),z.S.a().Q(a,"stop"),$m(this)):(z.S.a().wa(a,"stop"),z.S.a().Q(a,"play"),Ym(this))}catch(b){z.S.a().b(b)}};z.f.Rr=function(){try{this.Je?Jm(this):Xm(this)}catch(a){z.S.a().b(a)}};z.f.lr=function(a){try{if(this.xh){var b=z.J("voicenote-message-spacer");z.ze(b,z.U.a().ha("voicenote_nomic"))}else(window.URL||window.webkitURL).createObjectURL(a),z.S.a().Ua.yc(a,z.S.a().bind(this,this.os))}catch(c){z.S.a().b(c)}};
z.f.os=function(){try{this.R.U(!1),this.Gb=null}catch(a){z.S.a().b(a)}};z.f.Yq=function(a){try{if(this.xh){var b=z.J("voicenote-message-spacer");z.ze(b,z.U.a().ha("voicenote_nomic"))}else{0<this.Hb.src.length&&(window.URL||window.webkitURL).revokeObjectURL(this.Hb.src);var c=(window.URL||window.webkitURL).createObjectURL(a);this.Hb.src=c}}catch(d){z.S.a().b(d)}};z.f.Tp=function(){try{this.Gb.createBufferSource()}catch(a){z.S.a().b(a)}};
z.f.jm=function(){try{z.O(z.Ci(this.R),"left","0px"),z.O(z.Ci(this.R),"top","0px"),z.O(z.Ci(this.R),"width","100%"),z.O(z.Ci(this.R),"height","140px")}catch(a){z.S.a().b(a)}};z.f.Lh=function(){try{for(var a=window.document.querySelectorAll("[data-voicenote-dialog]"),b=0;b<a.length;b++){var c=a[b].getAttribute("data-voicenote-dialog");a[b].innerText=z.U.a().ha(c)}}catch(d){z.S.a().b(d)}};
z.f.Ct=function(a){try{var b=this.Gb.createMediaStreamSource(a);this.Ie=new window.Recorder(b);this.pf=this.Gb.createAnalyser();this.pf.Uu=.3;this.pf.pu=1024;b.connect(this.pf);this.Ie.record();this.Je=!0;this.Ie.getBuffers(this.Iq);this.mj=new window.Uint8Array(this.pf.fftSize);this.pf.getByteTimeDomainData(this.mj);this.cn()}catch(c){z.S.a().b(c)}};
z.f.Vl=function(){try{if(this.jj){var a=(100/this.Hb.duration*this.Hb.currentTime).toFixed();this.X.clearRect(-300,-300,800,800);this.Ya(this.X,"#efefef",4,1,this.Kc);0<a&&100>a&&this.Ya(this.X,"#555555",4,a/100,this.Kc);this.ij=(0,window.setTimeout)(this.Mn,250)}}catch(b){z.S.a().b(b)}};
z.f.Ul=function(){try{var a=z.J("round-micplayback-circle-img");z.S.a().wa(a,"stop");z.S.a().Q(a,"play");Ym(this);(0,window.clearTimeout)(this.ij);this.ij=0;this.X.clearRect(-300,-300,800,800);this.Ya(this.X,"#efefef",4,1,this.Kc)}catch(b){z.S.a().b(b)}};
z.f.Sl=function(a){try{if(!this.Je){var b=z.Q(a.currentTarget),c={};c.x=a.clientX-b.x;c.y=a.clientY-b.y;var d=z.pg(a.currentTarget);a={};a.x=d.width/2;a.y=d.height/2;var e=2*Math.PI,g=(Math.atan2(c.y-a.y,c.x-a.x)+e)%e,h=(0,window.parseInt)(g/e*100),h=h+25;99<h&&(h-=100);this.Hb.currentTime=h/100*this.Hb.duration;var l=z.J("round-micplayback-circle-img");z.S.a().wa(l,"play");z.S.a().Q(l,"stop");$m(this)}}catch(m){z.S.a().b(m)}};
z.f.cn=function(){try{if(this.Je)if(250<this.nh)this.xh=!0,this.Sd.clearRect(-200,-200,400,400),Jm(this);else{(0,window.requestAnimationFrame)(z.S.a().bind(this,this.cn));this.pf.getByteTimeDomainData(this.mj);var a=this.mj[0];this.Ge<a-127&&129<a?this.Ge+=20:this.Ge>a-127&&(this.Sd.clearRect(-200,-200,400,400),this.Ge--);this.Sd.globalAlpha=.5;this.Sd.beginPath();this.Sd.arc(67,67,46+this.Ge,0,2*Math.PI,!1);this.Sd.arc(67,67,20,0,2*Math.PI,!0);this.Sd.fillStyle="#FD3269";this.Sd.fill();128==a?this.nh++:
this.nh=0}else this.Sd.clearRect(-200,-200,400,400)}catch(b){z.S.a().b(b)}};z.f.Ya=function(a,b,c,d,e){d=Math.min(Math.max(0,d||1),1);e=(e-c)/2;a.beginPath();a.arc(0,0,e,0,2*Math.PI*d,!1);a.strokeStyle=b;a.lineCap="round";a.lineWidth=c;a.stroke()};z.Of("FixedToolbar");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_FixedToolbar.js