(function(z){
var Xk=function(a){this.h=window;this.K=a;new z.yd;this.da=!1;this.fc=this.rb=null;this.V=[];this.wc=!1;this.r={};this.r.ia=0;this.r.Hj="";this.r.Gj="";this.r.Wb=null;this.qd=this.pd=0;this.Nc=/\w/i;this.o={};this.o.parentId="panel-right";this.o.positionId="Selected";this.o.seq="1";this.o.words=[];this.o.words.push("The");this.o.words.push("In");this.o.words.push("I");this.o.words.push("It");this.o.words.push("He");this.o.words.push("This");this.o.words.push("A");this.o.words.push("But");this.o.words.push("As");
this.o.words.push("For");this.ce=z.S.a().bind(this,this.ke);this.it=z.S.a().bind(this,this.Lt);this.bj=this.va=this.T=null;this.Vb=!1};
var $=function(){this.vd="Highlights";this.jc="WACViewPanel_EditingElement";this.ja="kix-lineview";this.jb="kix-lineview-text-block";this.dk="kix-paragraphrenderer";this.ci="kix-page";this.Dg="thRWGDns";this.Cg="thCTag";this.Ba=this.Dg+":"+this.Cg;this.N="textHELPWR";this.u="thGBWord";this.Ga="thSpace";this.qa=null;this.rf=-1;this.ng={};this.ng.x=-1;this.ng.y=-1;this.Ke=0;this.vc=z.oj.a().Fd();this.sb=this.vc.sentences.wordEnds;this.ta=[];this.og=0;this.rl=this.Rn=-1;this.Zn=!1;this.gg=void 0;this.Oh=
!1;this.Nc=/\w/i;this.Va=this.oa=null;this.Vn=z.I(this.jc);this.Fe=window.document;this.h=window;this.He=[];this.Ka=null;this.Ib=-1;this.sf=!1;this.Ub=null;this.Le=0;this.uf=z.S.a().bind(this,this.Zd);this.fa=new Xk(this);window.addEventListener("message",this.uf,!1);var a=z.S.a().Zf(),b=this.Fe.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=a+"assets/thFixedToolbar.css";this.Fe.body.appendChild(b);this.md=this.Rd=this.Ia=this.wj=this.tf=this.zh=this.uh=this.pg=null;(0,window.setTimeout)(this.Hg.bind(this),
1E3);z.T.a().i("onWRPredictionStateChanged",this.Qc,this);z.T.a().i("onBarToggled",this.Kl,this);z.T.a().i("onBarClosed",this.Jl,this);z.T.a().i("onBrowserAction",this.Ll,this)};
var Yk=function(a){try{try{if(a.Zn){for(var b=window.document.getElementById("pages"),c=null,d=0;d<b.childElementCount;d++)if("none"!=b.childNodes[d].style.display){c=d;break}var e=window.document.getElementById("pages").getElementsByTagName("image");if(c!=a.Rn)a.Rn=c,a.rl=e.length,Zk(a);else if(e.length!=a.rl){b=!0;for(c=0;c<e.length;c++)if("//ssl.gstatic.com/docs/common/loading_animation.gif"==e[c].href.bu){b=!1;break}b&&(a.rl=e.length,Zk(a))}}}catch(g){z.S.a().b(g)}var h=window.document.querySelector(".sketchy-text-selection-overlay");
null==h&&(h=window.document.querySelector('rect[fill\x3d"#000"] '));if(null!==h)window.console.dir(h),$k(a,h);else{var l=window.document.querySelector(".docs-text-ui-cursor-blink");null==l&&(l=window.document.querySelector('rect[shape-rendering\x3d"crispEdges"]'));null!==l&&(window.console.dir(l),$k(a,l))}}catch(m){}};
var Zk=function(a){try{for(var b=window.document.getElementById("pages").getElementsByTagName("image"),c=0;c<b.length;c++)(function(a,b){var c=a.getAttribute("latex");if(null==c||void 0==c)a.setAttribute("latex",""),window.thEquatioLatexExtractor.getLatexFromImageUrl(a.href.baseVal).then(function(c){void 0!=c&&""!=c?(a.setAttribute("latex",c),void 0==b.gg&&(b.gg=[]),b.gg.push(a),window.postMessage({type:"EQUATIO_MATHJAX_GET_SPOKEN_TEXT",text:c,id:a.J},window.location.href)):a.setAttribute("latex",
"")})})(b[c],a)}catch(d){z.S.a().b(d)}};var al=function(a){try{var b=[],c=bl(a);if(-1==c.innerHTML.indexOf("tspan"))b.push(bl(a).innerHTML);else{var d=c.getElementsByTagName("tspan");a="";for(c=0;c<=d.length-1;c++)a+=d[c].innerHTML,a=a.replace(/[\u200B-\u200D\uFEFF]/g,"");b.push(a)}return b}catch(e){z.S.a().b(e)}};
var bl=function(a){var b=null;Yk(a);try{var c=[],c=null==a.Ia?[]:null==a.Ia.parentNode?[]:null==a.Ia.parentNode.parentNode?[]:null==a.Ia.parentNode.parentNode.parentNode?[]:a.Ia.parentNode.parentNode.parentNode.getElementsByTagName("g")}catch(d){window.console.log(d)}for(var e=null,g=!1,h=1;h<c.length;h++)try{var g=c[h].hasAttribute("transform"),l=-10;0==g&&(l=0);if(1==g){var m=c[h].getAttribute("transform"),n=c[h].getAttribute("id"),p=c[h].getAttribute("class"),q=null,u=!1;null==n&null==p?(q=m.split(" "),
u=!0):q=m.split(",");var r=q[1].replace(")",""),r=r.trim(),l=(0,window.parseInt)(r);if(1==u&&1==c[h].parentNode.hasAttribute("transform"))var q=null,q=c[h].parentNode.getAttribute("transform").split(","),v=q[1].replace(")",""),v=v.trim(),l=l+(0,window.parseInt)(v)}a.Rd=Math.round(a.Rd);if(l>a.Rd+5){var w=h-1;"sketchy-text-content-decoration"==c[h-1].getAttribute("class")&&(w=h-2);if(0!=c[w].getElementsByTagName("text").length){e=1==c[w].hasAttribute("id")?c[w].childNodes[0]:c[w];break}else if("image"==
c[w].nodeName.toLowerCase()&&1==c[w].hasAttribute("latex")){e=c[w];break}}}catch(K){}null!=e&&void 0!=e||1!=g||(0!=c[c.length-1].getElementsByTagName("text").length?e=1==c[c.length-1].hasAttribute("id")?c[c.length-1].childNodes[0]:c[c.length-1]:void 0!==w&&"image"==c[w].nodeName.toLowerCase()&&1==c[w].hasAttribute("latex")&&(e=c[c.length-1]));if(null==e||void 0==e)for(e=c[1],h=1;h<c.length;h++)c[h].getBBox();try{if(null!=e&&void 0!=e)for(var G=e.getElementsByTagName("text"),h=0;h<G.length;h++)(0,window.parseInt)(G[h].getAttribute("x"))<=
(0,window.parseInt)(a.md)&&(b=G[h])}catch(A){window.console.log(A)}return b};
var cl=function(a,b){try{var c=[],d=[];if(null==b)if(null!=a.pg){if(null==a.Ia)d=a.wj;else{var e=window.document.querySelectorAll(".sketchy-text-selection-overlay");0==e.length&&(e=window.document.querySelectorAll('rect[fill\x3d"#000"]'));0!=e.length?(d=a.Ia.parentNode.parentNode.parentNode.getElementsByTagName("text"),a.fa.rc(),a.Ia=null,a.fa.ra("ArrowLeft")):d=a.Ia.previousSibling.getElementsByTagName("text")}a.uh>d.length-1&&(a.uh=d.length);for(var e=0,g=a.pg;g<=a.uh;g++)c[e]=d[g],e++;a.zh=c}else c=
a.Ia.previousSibling.getElementsByTagName("text");else c=b,a.zh=c;d=-1;for(g=0;g<c.length;g++)c[g].getBBox().height>d&&(d=c[g].getBBox().height);for(g=0;g<c.length;g++){d=-1;for(e=g;e<c.length;e++)c[e].getBBox().height>d&&(d=c[e].getBBox().height);var h=c[g].getAttribute("x"),h=h.replace("px",""),h=(0,window.parseInt)(h),e=-1*d,l=d,m=c[g].getBBox().width;if(g!=c.length-1){var n=c[g+1].getAttribute("x"),n=n.replace("px",""),n=(0,window.parseInt)(n),p=c[g].getAttribute("x"),p=p.replace("px",""),p=(0,window.parseInt)(p);
c[g+1].getBBox().x>c[g].getBBox().x&&(m=n-p)}var q=l,u=window.document.createElement("g");u.setAttribute("class","sketchy-text-background-inner TH-Word-BackHighlightTest");u.setAttribute("transform","translate(0 "+q+")");var r=window.document.createElement("rect");r.setAttribute("x",h);r.setAttribute("y",e);r.setAttribute("width",1);r.setAttribute("height",l);r.setAttribute("fill","#ffff00");r.setAttribute("fill-opacity","1");u.appendChild(r);c[g].parentNode.parentNode.previousSibling.appendChild(u);
var v=c[g].parentNode.parentNode.previousSibling;v.innerHTML+=" ";var w=c[g].parentNode.parentNode.previousSibling.getBBox().height;w>=l+10&&(v.innerHTML+=" ",l=w);for(var K=window.document.getElementsByClassName("sketchy-text-background-inner TH-Word-BackHighlightTest"),G=0;0<K.length&&5E3>G;)K[K.length-1].remove(),G++;var A=window.document.createElement("g");A.setAttribute("class","sketchy-text-background-inner TH-Word-BackHighlight");A.setAttribute("transform","translate(0 "+q+")");window.colorRectEl=
window.document.createElement("rect");window.colorRectEl.setAttribute("x",h);window.colorRectEl.setAttribute("y",e);window.colorRectEl.setAttribute("width",m+1);window.colorRectEl.setAttribute("height",l);1!=c.length&&(window.colorRectEl.setAttribute("fill","#ffff00"),window.colorRectEl.setAttribute("fill-opacity","1"));A.appendChild(window.colorRectEl);c[g].parentNode.parentNode.previousSibling.appendChild(A);v=c[g].parentNode.parentNode.previousSibling;v.innerHTML+=" "}}catch(N){window.console.log(N)}};
var dl=function(){for(var a=[],b=0,c=window.document.getElementById("pages"),d=null,e=0;e<=c.childNodes.length-1;e++)if(-1==c.childNodes[e].getAttribute("style").indexOf("display: none")){d=c.childNodes[e];break}var g=d.querySelectorAll("[transform]");window.yCoordArray=[];for(e=0;e<g.length;e++)if(c=g[e].getAttribute("transform"),-1!=c.indexOf("matrix")&&("image"==g[e].nodeName.toLowerCase()||0<g[e].getElementsByTagName("text").length)){d=!1;if(0<g[e].getElementsByTagName("text").length)d=!0;else if("image"==
g[e].nodeName.toLowerCase()&&void 0!=g[e].href.baseVal&&0<g[e].href.baseVal.length){var h=g[e].getAttribute("latex");null!=h&&void 0!=h&&""!=h&&(d=!0)}d&&(a[b]=g[e],b++,d="",d=c.substr(c.lastIndexOf(",")+1),d=d.replace(")",""),d=(0,window.parseInt)(d),window.yCoordArray[b]=d)}window.yCoordArray.sort(function(a,b){return a-b});b=[];for(h=g=0;h<=window.yCoordArray.length-1;h++)for(e=0;e<=a.length-1;e++)if(c=a[e].getAttribute("transform"),d="",d=c.substr(c.lastIndexOf(",")+1),d=d.replace(")",""),d=(0,window.parseInt)(d),
d==window.yCoordArray[h]){c=!1;for(d=0;d<=b.length-1;d++)b[d]==a[e]&&(c=!0);c||(b[g]=a[e],g++)}return b};var el=function(){try{for(var a=window.document.getElementsByClassName("thImageHighlightedSlides"),b=0;b<a.length;b++)fl(a[b],!1)}catch(c){z.S.a().b(c)}};var fl=function(a,b){b?a.classList.add("thImageHighlightedSlides"):a.classList.remove("thImageHighlightedSlides")};z.Sk=function(a,b,c,d){z.Tk?(z.Tk=!1,z.Uk(a,b,c,d)):window.setTimeout(z.Sk,100,a,b,c,d)};z.Uk=function(){};z.Vk=function(){};
z.Wk=function(){};var $k=function(a,b){try{a.Ia=b,a.Rd=b.getAttribute("y"),a.md=b.getAttribute("x")}catch(c){z.S.a().b(c)}};z.f=Xk.prototype;z.f.Pc=function(a){null!==this.bj&&((0,window.clearTimeout)(this.bj),this.bj=null);var b=this;Yk(this.K);this.bj=(0,window.setTimeout)(function(){b.it(a)},500)};z.f.Ih=function(){};
z.f.Kb=function(a){this.K.Vf(a.key);if("Shift"!==window.event.key&&"Control"!==window.event.key&&"Alt"!==window.event.key){if(this.Vb)if(this.Vb=!1,-1=="?!.,:;".indexOf(window.event.key))this.Vb=!1;else{var b=this.K.pc().context.split("");if(2>b.length)return;var c=b[b.length-2];" "==b[b.length-1]&&" "!==c&&(window.event.preventDefault(),window.event.stopPropagation(),this.ra("Backspace"),this.Ne(window.event.key+" "))}this.Vb=!1}if(a.ctrlKey&&47<a.keyCode&&58>a.keyCode){var d=[];d.push(a);null!==
this.Ja&&((0,window.clearTimeout)(this.Ja),this.Ja=null);this.Ja=(0,window.setTimeout)(function(){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionKeyDown(d)}.bind(this),10);z.Xj()&&(a.preventDefault(),a.stopPropagation())}};z.f.Lt=function(a){this.da&&this.xa(a);this.qe()};z.f.ke=function(){this.da&&this.xa("")};
z.f.xa=function(a){this.T=null;if(this.da){void 0==a&&(a="");var b=this.K.pc(a);"string"==typeof a&&(6<a.length||" "==a.substr(a.length-1,1))&&(b.context=a);if(null==b)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{a=b.context.substr(b.context.length-1);if(0==b.context.length||" "==a||-1!==".?!".indexOf(a)){a=z.S.a().nb();var c=z.V.a().I().prediction.predictahead;if(!a["Predict Ahead"]||!c){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();return}}a=z.V.a().I().prediction.results;
c=z.V.a().I().language.services;this.r.ia++;999<this.r.ia&&(this.r.ia=0);var d='"'+z.S.a().Pf(b.context)+'","'+a+'","'+c+'"',e='{ "parent":"panel-right", "position":"'+this.K.wb+'","addSpace":true,"seq":"'+this.r.ia+'"}';z.S.a().wg(this.r.ia);this.r.Wb=b;e=z.pd(e);d=[];d[0]=b.context;d[1]=a;d[2]=c;if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else e.context=d,window.postMessage({method:"thPrediction",type:"1757FROM_PAGERW4G",payload:e},"*")}}};
z.f.Lb=function(a){this.Vb=!1;null!==this.va&&((0,window.clearTimeout)(this.va),this.va=null);var b=this;window.console.log("ActiveElement: "+window.document.activeElement);"thprediction-word"!=a.target.className&&(this.va=(0,window.setTimeout)(function(){b.ce(a)},600))};z.f.Gh=function(){var a=this.K.ya();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,this.h.className)};
z.f.Ml=function(){var a=this.K.ya();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,this.h.className)};z.f.qe=function(){z.T.a().k("onWordChanged",[])};z.f.be=function(a){try{var b=this.r.Wb,c=b.prepunc+a[0]+b.postpunc;this.Ne(c+" ");var d=z.S.a().Ma();this.Vb=!0;a=[];a.push("prediction insert");a.push(d.Email);a.push(d.Email.split("@")[1]);window.postMessage({type:"1757FROM_PAGERW4G",key:"function",method:"SendEvent",parameters:a},"*")}catch(e){z.S.a().b(e)}};
z.f.Qc=function(a){try{if(this.da=a[0])a=[],a.push("panel-right"),this.xa(""),z.T.a().k("onOpenPredictionWindow",a)}catch(b){z.S.a().b(b)}};
z.f.Kh=function(a){try{window.console.log("speech recog "+a);var b=(a+" ").split(""),c=window.document.getElementsByClassName("docs-texteventtarget-iframe");window.console.log("2");var d=c[0].contentDocument;window.console.log("2 end");window.console.log("3");var e=c[0].contentDocument.createEventObject?c[0].contentDocument.createEventObject():c[0].contentDocument.createEvent("Events");window.console.log("3 end");e.initEvent&&e.initEvent("keypress",!0,!0);for(a=0;a<b.length;a++)e.keyCode=b[a].charCodeAt(0),
e.which=b[a].charCodeAt(0),d.dispatchEvent?d.dispatchEvent(e):d.fireEvent("onkeydown",e)}catch(g){z.S.a().b(g)}};z.f.rc=function(){this.V.keydown=this.Bb("keydown",this.M);this.V.keypress=this.Bb("keypress",this.M);this.V.mousedown=this.Bb("mousedown",window.document);this.V.mouseup=this.Bb("mouseup",window.document);this.wc=!0};
z.f.Hg=function(a){try{if(null==z.J("docs-texteventtarget-iframe"))(0,window.setTimeout)(this.Hg(a),1E3);else if(null==z.J("docs-texteventtarget-iframe").contentDocument)(0,window.setTimeout)(this.Hg(a),1E3);else{this.M=z.J("docs-texteventtarget-iframe").contentDocument;this.Wd=z.J("docs-texteventtarget-iframe").contentWindow;var b=z.S.a().bind(this,this.Pc);this.M.addEventListener("keyup",b,!0);var c=z.S.a().bind(this,this.Ih);this.M.addEventListener("keypress",c,!0);var d=z.S.a().bind(this,this.Kb);
this.M.addEventListener("keydown",d,!0);var e=z.S.a().bind(this,this.Lb);window.document.addEventListener("mousedown",e,!0);window.document.addEventListener("mouseup",function(){(0,window.setTimeout)(function(){this.qe()}.bind(this),600)}.bind(this),!0);var g=z.S.a().bind(this,this.Gh);z.E(this.h,"scroll",g);z.T.a().i("onPredictionChange",this.be,this);z.T.a().i("onWRPredictionStateChanged",this.Qc,this);z.T.a().i("onSpeechRecognitionChange",this.Kh,this);a()}}catch(h){z.S.a().b(h)}};
z.f.Bb=function(a,b){try{var c=[],d;for(d in b)if(d.match(/^closure/)&&"number"!=typeof b[d]){var e=b[d];if(e){if(!this.rb)for(var g in e){var h=e[g];if(h&&h!=b)for(var l in h){var m=h[l];m&&void 0!=m.length&&m[0].src==b&&(this.rb=g)}}for(var n in e[this.rb])if(n==a)for(var p=e[this.rb][n],q=0;q<p.length;q++){if(!this.fc&&p[q].src==b)for(var u in p[q])if(p[q][u].src==b){this.fc=u;break}c.push({en:p[q],Cc:p[q][this.fc]})}}}return c}catch(r){z.S.a().b(r)}};
z.f.ra=function(a,b,c){void 0==c&&(c="keydown");this.rc();void 0==b&&(b=1);var d={altGraphKey:!1,altKey:!1,bubbles:!0,cancelBubble:!1,cancelable:!0,charCode:0,clipboardData:void 0,ctrlKey:!1,currentTarget:this.M,defaultPrevented:!1,detail:0,eventPhase:0,keyCode:0,keyLocation:0,layerX:0,layerY:0,metaKey:!1,pageX:0,pageY:0,returnValue:!0,shiftKey:!1,srcElement:this.M.body,target:this.M.body,timeStamp:(new Date).getTime(),type:"keydown",view:this.Wd,which:0};switch(a){case "CTRL+Z":d.ctrlKey=!0;d.keyCode=
90;d.which=90;break;case "Apple+Z":d.metaKey=!0;d.keyCode=90;d.which=90;break;case "Backspace":d.defaultPrevented=!0;d.keyCode=8;d.which=8;break;case "Newline":d.defaultPrevented=!0;d.keyCode=13;d.which=13;break;case "CTRL+Home":d.ctrlKey=!0;d.keyCode=36;d.which=36;break;case "Shift+ArrowLeft":d.keyCode=37;d.shiftKey=!0;d.which=37;break;case "ArrowRight":d.keyCode=39;d.which=39;break;case "ArrowLeft":d.keyCode=37;d.which=37;break;case "AppleAlt+ArrowLeft":d.altKey=!0;d.keyCode=37;d.which=37;break;
case "CTRL+ArrowLeft":d.ctrlKey=!0;d.keyCode=37;d.which=37;break;case "AppleAlt+Shift+ArrowRight":d.altKey=!0;d.keyCode=39;d.shiftKey=!0;d.which=39;break;case "CTRL+Shift+ArrowRight":d.ctrlKey=!0;d.keyCode=39;d.shiftKey=!0;d.which=39;break;case "AppleAlt+Shift+ArrowLeft":d.altKey=!0;d.keyCode=37;d.shiftKey=!0;d.which=37;break;case "CTRL+Shift+ArrowLeft":d.ctrlKey=!0;d.keyCode=37;d.shiftKey=!0;d.which=37;break;case "CTRL+Shift+S":d.ctrlKey=!0;d.charCode=83;d.keyCode=83;d.shiftKey=!0;d.altKey=!1;d.which=
83;d.code="KeyS";d.key="s";break;case "CMD+Shift+S":d.metaKey=!0;d.charCode=83;d.keyCode=83;d.shiftKey=!0;d.altKey=!1;d.which=83;d.code="KeyS";d.key="s";break;case "ESC":d.keyCode=27,d.which=27;case "s":d.keyCode=83,d.which=83;default:return}for(a=0;a<b;a++)for(var e in this.V[c])this.V[c][e].Cc(d)};
z.f.Ne=function(a){window.getSelection();var b=this.r.Wb.context,c=a.split(""),d=window.document.getElementsByClassName("docs-texteventtarget-iframe");window.console.log("4");var e=d[0].contentDocument;window.console.log("4 end");window.console.log("5");d=d[0].contentDocument.createEventObject?d[0].contentDocument.createEventObject():d[0].contentDocument.createEvent("Events");window.console.log("5 end");d.initEvent&&d.initEvent("keypress",!0,!0);if(" "!=b.substr(b.length-1,1)){this.rc();var g=0<=
window.navigator.platform.toUpperCase().indexOf("MAC"),h=this.K,l="";try{bl(h);for(var m=bl(h).parentNode.children,n=null,p=!1,q=0;q<m.length;q++)(0,window.parseInt)(m[q].getAttribute("x"))>(0,window.parseInt)(h.md)-2&&(null==n&&(n=m[q]),l=l+m[q].innerHTML+" ",p=!0);0==p&&(l=m[m.length-1].innerHTML)}catch(u){window.console.log(u),l=""}""!=l?1==g?(this.ra("AppleAlt+ArrowLeft"),this.ra("AppleAlt+Shift+ArrowRight")):(this.ra("CTRL+ArrowLeft"),this.ra("CTRL+Shift+ArrowRight")):1==g?this.ra("AppleAlt+Shift+ArrowLeft"):
this.ra("CTRL+Shift+ArrowLeft")}for(m=0;m<c.length;m++)d.keyCode=c[m].charCodeAt(0),d.which=c[m].charCodeAt(0),e.dispatchEvent?e.dispatchEvent(d):e.fireEvent("onkeydown",d);try{" "!=b.substr(b.length-1,1)&&""!=b?(b=b.substring(0,b.lastIndexOf(" ")),this.xa(b+" "+a)):this.xa(b+a)}catch(r){window.console.log(r)}};
z.f.ri=function(a,b){this.wc||this.rc();z.Q(this.h);if(!(a<this.h.x||a>this.h.x+this.h.offsetWidth||b<this.h.y||b>this.h.y+this.h.offsetHeight)){var c=z.S.a().bind(this,this.Tg);this.pd=a;this.qd=b;(0,window.setTimeout)(c,1)}};
z.f.Tg=function(){this.rc();var a={altKey:!1,bubbles:!0,button:0,cancelBubble:!1,cancelable:!0,charCode:0,clientX:this.pd,clientY:this.qd,clipboardData:void 0,ctrlKey:!1,currentTarget:window.document,dataTransfer:null,defaultPrevented:!1,detail:1,eventPhase:0,fromElement:null,keyCode:0,layerX:0,layerY:0,metaKey:!1,offsetX:0,offsetY:0,pageX:0,pageY:0,relatedTarget:null,returnValue:!0,screenX:0,screenY:0,shiftKey:!1,srcElement:this.h,target:this.h,timeStamp:(new Date).getTime(),toElement:this.h,type:null,
view:window,which:1,x:0,y:0},b=["mousedown","mouseup"],c;for(c in b){a.type=b[c];"mouseup"==b[c]&&(a.srcElement=a.target=a.toElement=window.document);for(var d in this.V[b[c]])this.V[b[c]][d].Cc(a)}};z.ek.Mh="GoogleSlidesParser";z.B($,z.Uj);z.f=$.prototype;z.f.Hg=function(){try{this.fa.Hg(function(){}.bind(this))}catch(a){z.S.a().b(a)}};z.f.Qc=function(){};z.f.Gf=function(a){try{this.qa=a}catch(b){z.S.a().b(b)}};z.f.Cb=function(){try{return this.qa.name}catch(a){z.S.a().b(a)}};z.f.Ab=function(){try{return this.qa.bar}catch(a){z.S.a().b(a)}};z.f.Bo=function(a){this.Bh=0<a.length?a[0]:!1};
z.f.bg=function(){try{var a=z.S.a().Zf(),b=this.Fe.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=a+"assets/thFixedToolbar.css";this.Fe.body.appendChild(b);var c=this.Ec();cl(this);z.S.a();for(var d=this.vc.sentences.sentenceEndExclusions,a=0;a<c.length-1;a++)if(!z.Vj(d,c[a]))for(var e in this.sb)-1!==c[a].search(this.sb[e])&&(a=c.length);return c}catch(g){z.S.a().b(g)}};z.f.hf=function(){return!0};
z.f.ab=function(){try{var a=this.qc();if(void 0!==a&&null!==a){if(1==a.length)return a[0]=a[0].replace(/[\u200B-\u200D\uFEFF]/g,""),a;if(2==a.length)return a[0]=a[0].replace(/[\u200B-\u200D\uFEFF]/g,""),a[1]=a[1].replace(/[\u200B-\u200D\uFEFF]/g,""),[a.join(" ")]}return al(this)}catch(b){z.S.a().b(b)}};
z.f.pc=function(){Yk(this);var a="",b="",c=0;try{bl(this);for(var d=bl(this).parentNode.children,e=!1,e=!0,g=null,h=0;h<d.length;h++)(0,window.parseInt)(d[h].getAttribute("x"))<(0,window.parseInt)(this.md)&&(null==g&&(g=d[h]),a=a+d[h].innerHTML+" ",b=d[h].innerHTML,c=h);if(1==e)for(var l=d[0].parentNode.parentNode.parentNode.parentNode.parentNode.getElementsByTagName("text"),h=0;h<l.length;h++)if(g==l[h]){0<h&&(a=l[h-2].innerHTML+" "+l[h-1].innerHTML+" "+a);break}Math.round((0,window.parseInt)(this.md))>
Math.round((0,window.parseInt)(d[c].getAttribute("x"))+(0,window.parseInt)(d[c].getBBox().width))+1||(a=a.substring(0,a.length-1))}catch(m){window.console.log(m)}try{var n=this.Ia.getBoundingClientRect();null!=n&&0!=n.left&&(this.ng.x=n.left+n.width-22,this.ng.y=n.top+n.height)}catch(p){window.console.log(p)}c=[];c.context=a;c.word=b;c.cursorindex="";c.spaceatstart=!1;c.spaceatend=!1;c.prepunc="";c.postpunc="";c.selectRight=0;c.selectLeft=0;c.prechar="";c.currentchar="";c.postchar="";return c};
z.f.ue=function(){try{this.hd();var a={};a.$a=z.He(z.X(this.u)[0]);if(!(1>a.$a.length)){for(var b=z.I(this.jc),c=b.innerHTML.split("\x3cthrwgdns:thctag")[0],d=c.split("\x3e"),e=[],g=0;g<d.length;g++){var h=d[g];"\x3c"!=h.substr(0,1)&&e.push(h.split("\x3c")[0])}a.Yc=e.join(" ").split(a.$a).length-1;var l=z.X(this.u);a.cb=a.$a;a.Ic=a.Yc;a.cb=z.He(l[l.length-1]);if(0<a.cb.length){var m=b.innerHTML.split("\x3c/thrwgdns:thctag\x3e");m[m.length-1]=null;c=m.join();c=c.substr(0,c.length-2);d=c.split("\x3e");
e=[];for(g=0;g<d.length;g++)h=d[g],"\x3c"!=h.substr(0,1)&&e.push(h.split("\x3c")[0]);a.Ic=e.join(" ").split(a.cb).length-1}this.la();return a}}catch(n){z.S.a().b(n)}};
z.f.Gc=function(a){try{a=a.substring(1);var b=(0,window.parseInt)(a,16);a="rgb("+(b>>16&255)+","+(b>>8&255)+","+(b&255)+")";var c=window.document.getElementById("bgColorButton");if(null!=c){window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(c,"mousedown");window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(c,"mouseup");var d=window.document.querySelector(".docs-colormenuitems");if(null!=d){var e=d.querySelector(".jfk-palette-cell");if(null!=e&&null!==e){var g=e.firstChild.style.backgroundColor;
e.firstChild.style.backgroundColor=a;window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(e,"mousedown");window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(e,"mouseup");e.firstChild.style.backgroundColor=g}}}}catch(h){z.S.a().b(h)}};
z.f.mc=function(){try{var a=window.document.getElementById("bgColorButton");if(null!=a){window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(a,"mousedown");window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(a,"mouseup");window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(a,"click");var b=window.document.querySelector(".docs-colormenuitems");null!=b&&(b=b.firstElementChild,null!=b&&(window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(b,"mousedown"),
window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(b,"mouseup"),window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(b,"click"),window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(b,"mousedown"),window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(b,"mouseup"),window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(b,"click")))}}catch(c){z.S.a().b(c)}};
z.f.mn=function(a){try{var b=window.document.getElementsByTagName("rect"),c=window.document.getElementById("pages"),d=c.getElementsByTagName("image"),e=!1,g=window.document.getElementById("speakernotes-workspace").querySelector(".docs-text-ui-cursor-blink");null!==g&&(this.Ia=g,this.Rd=g.getAttribute("y"),this.md=g.getAttribute("x"),e=!0);if(0!=b.length&&!e)for(var h=0;h<b.length-1;){if(-1!=b[h].outerHTML.indexOf("docs-text-ui-cursor-blink")){e=!0;this.Ia=b[h];this.Rd=b[h].getAttribute("y");this.md=
b[h].getAttribute("x");break}for(g=0;g<=c.childNodes.length-1;g++)c.childNodes[g].contains(this.Ia)&&"none"==c.childNodes[g].style.display&&(this.md=this.Rd=this.Ia=null);if(b[h].hasAttribute("fill")&&"#000"==b[h].getAttribute("fill")){e=!0;this.Ia=b[h];this.Rd=b[h].getAttribute("y");this.md=b[h].getAttribute("x");break}h++}if(!e)for(h=0;h<d.length;h++){for(var l=d[h],m=l.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.getElementsByTagName("g"),b=0;b<m.length;b++){for(var n=
m[b].getElementsByTagName("path"),c=0;c<n.length;c++){var p=n[c];if(p.hasAttribute("stroke")&&"#000"!=p.getAttribute("stroke")){e=!0;this.Ia=l;this.Rd=l.getAttribute("y");this.md=l.getAttribute("x");break}}if(e)break}if(e)break}a([]);return window.words}catch(q){z.S.a().b(q)}};
z.f.getSelection=function(a){try{this.fg=a;var b=this.ue(),c='{ "doc":"'+window.location.href+'","startWordCount":"'+b.Yc+'", "startWord":"'+(0,window.escape)(b.$a)+'", "endWordCount":"'+b.Ic+'", "endWord":"'+(0,window.escape)(b.cb)+'"}',c=z.pd(c);window.postMessage({method:"getSelection",type:"1757FROM_PAGERW4G",payload:c},"*")}catch(d){z.S.a().b(d)}};
z.f.hd=function(){try{Yk(this);var a=null,b=null,c=null,d=null;try{a:{for(var e=window.document.getElementById("pages").getElementsByTagName("image"),g=0;g<e.length;g++)for(var h=e[g],l=h.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.getElementsByTagName("g"),m=0;m<l.length;m++)for(var n=l[m].getElementsByTagName("path"),p=0;p<n.length;p++){var q=n[p];if(q.hasAttribute("stroke")&&"#000"!=q.getAttribute("stroke")){b=h;break a}}b=null}null==b&&(a=bl(this));1>a.textContent.length&&
(b=null);if(null!=a){var u=window.document.querySelectorAll('rect[fill\x3d"#000"]');0==u.length&&(u=window.document.querySelectorAll(".sketchy-text-selection-overlay"));for(var d=0!=u.length?this.Ia.parentNode.parentNode.parentNode.getElementsByTagName("text"):this.Ia.previousSibling.getElementsByTagName("text"),r=0;r<d.length;r++)if(d[r]==a){c=r;break}}else if(null!=b){if(this.wj=null,this.tf=b,b.hasAttribute("spoken")&&(G=b.getAttribute("spoken"),""!=G))return window.lineOfWords=G.split(" ")}else{var v=
dl(),w=v[0].getElementsByTagName("text");0==w.length&&(window.console.log("Crivens! It's getSelectionOnly"),w=v[0]);this.wj=w;a=w[0];d=w;c=0}}catch(K){v=dl(),w=v[0].getElementsByTagName("text"),0==w.length&&(window.console.log("Crivens! It's getSelectionOnly"),w=v[0]),this.wj=w,a=w[0],d=w,c=0}var G="";if(-1==d[c].innerHTML.indexOf("tspan"))G=d[c].innerHTML;else{for(var A=a.getElementsByTagName("tspan"),N="",P=0;P<=A.length-1;P++)N+=A[P].innerHTML;G=N}this.pg=-1;a=null;b=!1;0<c&&d[c].parentNode.parentNode.parentNode.parentNode!=
d[c-1].parentNode.parentNode.parentNode.parentNode&&(b=!0);if(1!=b)for(r=c-1;-1<r;r--){var L="";if(-1==d[r].innerHTML.indexOf("tspan"))L=d[r].innerHTML;else{A=d[r].getElementsByTagName("tspan");N="";for(P=0;P<=A.length-1;P++)N+=A[P].innerHTML;L=N}if(-1==L.indexOf(".")&&-1==L.indexOf("!")&&-1==L.indexOf("?")){if(null!=a&&d[r].parentNode.parentNode.parentNode.parentNode!=a)break;G=L+" "+G;this.pg=r;a=d[r].parentNode.parentNode.parentNode.parentNode}else break}if(-1==this.pg||1==b)this.pg=c;a=null;b=
!1;d.length-1>=c&&(d.length-1==c?b=!0:d[c].parentNode.parentNode.parentNode.parentNode!=d[c+1].parentNode.parentNode.parentNode.parentNode&&(b=!0));L="";if(-1==d[c].innerHTML.indexOf("tspan"))L=d[c].innerHTML;else{A=d[c].getElementsByTagName("tspan");N="";for(P=0;P<=A.length-1;P++)N+=A[P].innerHTML;L=N}if(-1!=L.indexOf(".")||-1!=L.indexOf("!")||-1!=L.indexOf("?")||1==b)this.uh=c;else for(r=c+1;r<d.length&&(null==a||d[r].parentNode.parentNode.parentNode.parentNode==a);r++){L="";if(-1==d[r].innerHTML.indexOf("tspan"))L=
d[r].innerHTML;else{A=d[r].getElementsByTagName("tspan");N="";for(P=0;P<=A.length-1;P++)N+=A[P].innerHTML;L=N}G=G+" "+L;this.uh=r;a=d[r].parentNode.parentNode.parentNode.parentNode;if(-1!=L.indexOf(".")||-1!=L.indexOf("!")||-1!=L.indexOf("?"))break}return window.lineOfWords=G.split(" ")}catch(ma){z.S.a().b(ma)}};
z.f.getSelection=function(a){try{this.fg=a;var b=this.ue(),c='{ "doc":"'+window.location.href+'","startWordCount":"'+b.Yc+'", "startWord":"'+(0,window.escape)(b.$a)+'", "endWordCount":"'+b.Ic+'", "endWord":"'+(0,window.escape)(b.cb)+'"}',c=z.pd(c);window.postMessage({method:"getSelection",type:"1757FROM_PAGERW4G",payload:c},"*")}catch(d){z.S.a().b(d)}};
z.f.qc=function(a){try{var b=[],c=window.document.querySelectorAll('rect[fill\x3d"#000"]');0==c.length&&(c=window.document.querySelectorAll(".sketchy-text-selection-overlay"));if(0!=c.length)for(var d=0;d<c.length;d++)for(var e=c[d].parentNode.parentNode.parentNode.getElementsByTagName("text"),g=0;g<e.length;g++){var h=e[g].getBBox().x+1,l=(0,window.parseInt)(c[d].getAttribute("x")),m=e[g].getBBox().x+e[g].getBBox().width,n=(0,window.parseInt)(c[d].getAttribute("x"))+(0,window.parseInt)(c[d].getAttribute("width"));
if(m>=l&&m<=n||h>=l&&h<=n)if(-1==e[g].innerHTML.indexOf("tspan"))b.push(e[g].innerHTML);else{for(var p=e[g].getElementsByTagName("tspan"),q="",u=0;u<=p.length-1;u++)q+=p[u].innerHTML;b.push(q)}}else b=al(this);void 0!==a&&a(b);return b}catch(r){z.S.a().b(r)}};
z.f.bh=function(a){try{var b=[],c=window.document.querySelectorAll('rect[fill\x3d"#000"]');0==c.length&&(c=window.document.querySelectorAll(".sketchy-text-selection-overlay"));if(0!=c.length){for(var d=0;d<c.length;d++)for(var e=c[d].parentNode.parentNode.parentNode.getElementsByTagName("text"),g=0;g<e.length;g++){var h=e[g].getBBox().x+1,l=(0,window.parseInt)(c[d].getAttribute("x")),m=e[g].getBBox().x+e[g].getBBox().width,n=(0,window.parseInt)(c[d].getAttribute("x"))+(0,window.parseInt)(c[d].getAttribute("width"));
if(m>=l&&m<=n||h>=l&&h<=n)if(-1==e[g].innerHTML.indexOf("tspan"))b.push(e[g].innerHTML);else{for(var p=e[g].getElementsByTagName("tspan"),q="",u=0;u<=p.length-1;u++)q+=p[u].innerHTML;b.push(q)}}var r=b.join(" ").replace(/(\.+|\:|\!|\?)(\"*|\'*|\)*|}*|]*)(\s|\n|\r|\r\n)/gm,".\x3cbr /\x3e\x3cbr /\x3e$2").split("|"),v={documentTitle:window.document.title.replace(" - Google Slides",""),html:r.join(" ")}}else v={documentTitle:window.document.title,html:""};a(v)}catch(w){z.S.a().b(w)}};z.f.Ec=function(){try{return this.hd()}catch(a){z.S.a().b(a)}};
z.f.Ji=function(){try{return this.Ec().join(" ")}catch(a){z.S.a().b(a)}};z.f.Sf=function(){};z.f.Ac=function(a,b,c,d){try{this.Og(a,b,c,d)}catch(e){z.S.a().b(e)}};
z.f.Xe=function(a,b,c){try{b=[];var d=window.document.getElementById("WACViewPanel");d.querySelectorAll('[class*\x3d"TextRun"][style*\x3d"background-color: rgb"]');for(var e=[].slice.call(d.querySelectorAll('[class*\x3d"TextRun"][style*\x3d"background-color: rgb(255, 0, 255)"]')),g=[].slice.call(d.querySelectorAll('[class*\x3d"TextRun"][style*\x3d"background-color: rgb(255, 255, 0)"]')),h=[].slice.call(d.querySelectorAll('[class*\x3d"TextRun"][style*\x3d"background-color: rgb(0, 255, 0)"]')),l=[].slice.call(d.querySelectorAll('[class*\x3d"TextRun"][style*\x3d"background-color: rgb(0, 255, 255)"]')),
m=window.document.getElementById("WACViewPanel_EditingElement_WrappingDiv"),d=0,n="",d=0;d<e.length;++d)if(!m.contains(e[d].parentNode)){var p;p=e[d].nextSibling?e[d].nextSibling:e[d].parentNode.nextSibling;if("rgb(255, 0, 255)"===p.style.backgroundColor)n+=e[d].text;else{n+=e[d].text;if(0<n.length){var q;q=0>n.indexOf(" ")?n:n.substr(0,n.indexOf(" "));0>b.indexOf(q)&&b.push(q)}n=""}}d=0;e="";for(d=0;d<g.length;++d)m.contains(g[d].parentNode)||(p=g[d].nextSibling?g[d].nextSibling:g[d].parentNode.nextSibling,
"rgb(255, 255, 0)"===p.style.backgroundColor?e+=g[d].text:(e+=g[d].text,0<e.length&&(q=0>e.indexOf(" ")?e:e.substr(0,e.indexOf(" ")),0>b.indexOf(q)&&b.push(q)),e=""));d=0;g="";for(d=0;d<h.length;++d)m.contains(h[d].parentNode)||(p=h[d].nextSibling?h[d].nextSibling:h[d].parentNode.nextSibling,"rgb(0, 255, 0)"===p.style.backgroundColor?g+=h[d].text:(g+=h[d].text,0<g.length&&(q=0>g.indexOf(" ")?g:g.substr(0,g.indexOf(" ")),0>b.indexOf(q)&&b.push(q)),g=""));d=0;h="";for(d=0;d<l.length;++d)m.contains(l[d].parentNode)||
(p=l[d].nextSibling?l[d].nextSibling:l[d].parentNode.nextSibling,"rgb(0, 255, 255)"===p.style.backgroundColor?h+=l[d].text:(h+=l[d].text,0<h.length&&(q=0>h.indexOf(" ")?h:h.substr(0,h.indexOf(" ")),0>b.indexOf(q)&&b.push(q)),h=""));this.Pg(a,b,c)}catch(u){z.S.a().b(u)}};z.f.dh=function(){};
z.f.pb=function(a){try{var b=null,c=window.document.getElementById("TH-Word-highlight");null!=c&&c.remove();var d=window.document.getElementById("TH-Word-highlightFont");if(null!=d&&void 0!=d){if(-1==d.innerHTML.indexOf("tspan")){var e=d.getAttribute("style"),e=e.replace("fill:white","");d.setAttribute("style",e)}else for(var g=d.getElementsByTagName("tspan"),h=0;h<=g.length-1;h++)e=g[h].getAttribute("style"),e=e.replace("fill:white",""),g[h].setAttribute("style",e);d.removeAttribute("id")}b=this.zh;
if(null==b){var l=window.document.getElementsByClassName("thImageHighlightedSlides");0<l.length&&(this.tf=l[0])}else if(void 0!=b[a]){var m=b[a].getAttribute("style"),n=b[a].getAttribute("x"),n=n.replace("px",""),n=(0,window.parseInt)(n),p=b[a].parentNode.parentNode.previousSibling.getBBox().height,c=-1*p,q=b[a].getBBox().width,u=window.document.createElement("g");u.setAttribute("class","sketchy-text-background-inner TH-Word-HighlightTest");u.setAttribute("transform","translate(0 "+p+")");var r=window.document.createElement("rect");
r.setAttribute("x",n);r.setAttribute("y",c);r.setAttribute("width",1);r.setAttribute("height",p);r.setAttribute("fill","#ffff00");r.setAttribute("fill-opacity","1");u.appendChild(r);b[a].parentNode.parentNode.previousSibling.appendChild(u);var v=b[a].parentNode.parentNode.previousSibling;v.innerHTML+=" ";for(var w=window.document.getElementsByClassName("sketchy-text-background-inner TH-Word-HighlightTest"),u=0;0<w.length&&5E3>u;)w[w.length-1].remove(),u++;if(-1==b[a].innerHTML.indexOf("tspan"))b[a].setAttribute("style",
m+";fill:white");else for(g=b[a].getElementsByTagName("tspan"),h=0;h<=g.length-1;h++)m=g[h].getAttribute("style"),g[h].setAttribute("style",m+";fill:white");b[a].setAttribute("id","TH-Word-highlightFont");var K=window.document.createElement("g");K.setAttribute("class","sketchy-text-background-inner");K.setAttribute("id","TH-Word-highlight");K.setAttribute("transform","translate(0 "+p+")");window.colorRectEl=window.document.createElement("rect");window.colorRectEl.setAttribute("x",n);window.colorRectEl.setAttribute("y",
c);window.colorRectEl.setAttribute("width",q);window.colorRectEl.setAttribute("height",p);window.colorRectEl.setAttribute("fill","#0000ff");window.colorRectEl.setAttribute("fill-opacity","1");window.colorRectEl.setAttribute("rx","2");window.colorRectEl.setAttribute("ry","2");K.appendChild(window.colorRectEl);b[a].parentNode.parentNode.previousSibling.appendChild(K);v=b[a].parentNode.parentNode.previousSibling;v.innerHTML+=" ";this.tf=b[a]}}catch(G){z.S.a().b(G)}};
z.f.stop=function(){try{this.la(),el()}catch(a){z.S.a().b(a)}};
z.f.Jd=function(a,b){try{if(this.Oh)return el(),b(null),null;var c=z.V.a().I().speechoptions.continousreading;if(a&&!c)el(),b(null);else{window.postMessage({command:"GBooksSelection",type:"1757FROM_PAGERW4G",speech:"nextSentence",highlightWordIndex:-1},"*");for(var d=dl(),c="",e=[],g=0,h=null,l=null,m=null,n=0;n<=d.length-1;n++)if("image"==d[n].nodeName){if(d[n]==this.tf){m=d[n+1];break}}else if(1==d[n].contains(this.tf)){var p=d[n].getElementsByTagName("text"),m=this.tf==p[p.length-1]?d[n+1]:d[n];
break}d=[];if(void 0!=m){d="image"==m.nodeName?m:m.getElementsByTagName("text");if("image"!=d.nodeName){for(n=l=0;n<=d.length-1;n++)if(this.tf==d[n]){l=n;l++;break}for(n=l;n<=d.length-1&&(null==h||d[n].parentNode.parentNode.parentNode.parentNode==h);n++){l="";if(-1==d[n].innerHTML.indexOf("tspan"))l=d[n].innerHTML;else{for(var q=d[n].getElementsByTagName("tspan"),m="",p=0;p<=q.length-1;p++)m+=q[p].innerHTML;l=m}c=""==c?l:c+" "+l;e[g]=d[n];g++;h=d[n].parentNode.parentNode.parentNode.parentNode;if(-1!=
l.indexOf(".")||-1!=l.indexOf("!")||-1!=l.indexOf("?"))break}cl(this,e)}else if(d.hasAttribute("spoken")){c=d.getAttribute("spoken");if(""==c){el();b(null);return}q=d;try{el(),fl(q,!0),this.zh=null}catch(u){window.console.log(u)}}else{el();b(null);return}b(c.split(" "))}else el(),b(null)}}catch(r){z.S.a().b(r)}};
z.f.la=function(){try{for(var a=window.document.getElementsByClassName("sketchy-text-background-inner TH-Word-BackHighlight"),b=0;0<a.length&&5E3>b;)a[a.length-1].remove(),b++;var c=window.document.getElementById("TH-Word-highlight");null!=c&&c.remove();var d=window.document.getElementById("TH-Word-highlightFont");if(null!=d){var e=d.getAttribute("style"),e=e.replace("fill:white","");d.setAttribute("style",e);d.removeAttribute("id")}this.zh=null}catch(g){z.S.a().b(g)}};
z.f.zi=function(a,b){try{var c=window.document.createEvent("MouseEvents");c.initMouseEvent.apply(c,b);a.dispatchEvent(c)}catch(d){z.S.a().b(d)}};
z.f.Zd=function(a){try{if(void 0!=a.source&&void 0!=a.data&&a.source==window)if("1757FROM_BGRW4G"==a.data.type)if("onGetSelection"==a.data.method){var b=z.pd(a.data.payload);this.fg(b)}else if("GBooksSelectionReturn"===a.data.method&&(0,window.alert)(a.data.Iu),"onCollectHighlights"==a.data.method){var c=z.pd(a.data.payload);if("string"===typeof c){var d=null,e=z.S.a().fd(),d=window.open(c,"_ntthch"+e);d.focus();this.uc(c)}else 0==c[0].highlights.length?this.uc("false"):this.uc("true")}else{if("onVocabWords"==
a.data.method){var g=z.pd(a.data.payload);"string"===typeof g&&(d=null,e=z.S.a().fd(),d=window.open(g,"_ntthchVc"+e),d.focus(),this.Bl(g))}}else if(a.data&&"EQUATIO_MATHJAX_RESPOND_SPOKEN_TEXT"===a.data.type)try{for(b=0;b<this.gg.length;b++){var h=this.gg[b];try{if(h.J==a.data.id){this.gg.splice(b,1);h.setAttribute("spoken",a.data.text);break}}catch(l){}}}catch(m){}else a.data&&"EQUATIO_MATHJAX_READY"===a.data.type&&(this.Zn=!0)}catch(n){z.S.a().b(n)}};z.f.Og=function(a){try{this.uc=a,z.S.a().fd()}catch(b){z.S.a().b(b)}};
z.Tk=!0;z.f=$.prototype;
z.f.Pg=function(a,b,c){try{var d=[];this.Bl=a;var e=z.S.a().fd();c=c+" "+e;var g=new window.XMLHttpRequest;a="https://webservices-us.texthelp.com/v1.11.0/vocab?json\x3d{%22u%22:%22RWOfficeApps%22,%22e%22:%229yvydZ1FQn%22,%22b%22:";for(var e="",h=0;h<b.length;h++)e=h===b.length-1?e+"%22"+b[h]+"%22]}":0===h?e+"[%22"+b[h]+"%22,":e+"%22"+b[h]+"%22,";g.open("POST",a+e);g.setRequestHeader("Accept","application/json;odata\x3dverbose");g.onreadystatechange=function(){var a="";if(4==this.readyState&&200==
this.status&&(a=this.getResponseHeader("Content-Type"),"application/json"==a.substr(0,16))){for(var a=JSON.parse(this.response).hv,b,e=0;e<a.length;e++)for(var g=a[e].xu,h=0;h<g.length;h++){b=g[h].Xu;for(var l=0;l<b.length;l++)d.push(b[l])}for(a=0;a<d.length;a++)z.Sk(d[a],z.Vk,d.length,c)}};g.send()}catch(l){z.S.a().b(l)}};z.f.Sj=function(a,b){try{var c=z.Qj(a,this.h),d=z.Qj(b,this.h);if(c.y>d.y)return 1;if(c.y<d.y)return-1;if(c.y===d.y){if(c.x<d.x)return-1;if(c.x>d.x)return 1}return 0}catch(e){z.S.a().b(e)}};
z.f.ya=function(){try{return{x:this.ng.x,y:this.ng.y}}catch(a){z.S.a().b(a)}};z.f.Xc=function(){try{var a=window.document.querySelector("#slides-view");null!==a&&(a.focus(),window.textHelp.webreaderapi.HelpersSingleton.getInst().fireEvent(a,"click"));(0,window.setTimeout)(function(){this.fa.ra("CTRL+Shift+S",1,"keydown")}.bind(this),300);(0,window.setTimeout)(function(){this.fa.ra("CMD+Shift+S",1,"keydown")}.bind(this),350)}catch(b){z.S.a().b(b)}};z.f.Zc=function(){};z.f.Kl=function(){this.af()};
z.f.Jl=function(){this.af()};z.f.Ll=function(){this.af()};z.f.af=function(){try{var a=window.document.querySelector("#workspace-container"),b=a.style.overflow;a.style.overflow="scroll";a.scrollTop=a.scrollTop++;(0,window.requestAnimationFrame)(function(){a.scrollTop=a.scrollTop--;a.style.overflow=b}.bind(this))}catch(c){window.console.log(c)}};z.f.jd=function(){try{return this.Ji()}catch(a){z.S.a().b(a)}};z.t("textHelp.parsers",z.ek);z.t("textHelp.parsers.GoogleSlidesParser",$);
$.prototype.hiliteNextSentence=$.prototype.Jd;$.prototype.hiliteWord=$.prototype.pb;$.prototype.highlightSelection=$.prototype.Gc;$.prototype.getUserSettings=$.prototype.I;$.prototype.getCaretPosition=$.prototype.mn;$.prototype.getSelection=$.prototype.getSelection;$.prototype.getSelectionLocal=$.prototype.qc;$.prototype.clearHighlights=$.prototype.mc;$.prototype.getTextWithContext=$.prototype.dh;$.prototype.getParserName=$.prototype.Cb;$.prototype.getBarConfigFromParser=$.prototype.Ab;
$.prototype.getPredictionPosition=$.prototype.ya;$.prototype.startSpeechRecognition=$.prototype.Xc;$.prototype.stopSpeechRecognition=$.prototype.Zc;$.prototype.getSentenceText=$.prototype.jd;z.Of("GoogleSlidesParser");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_GoogleSlidesParser.js