(function(z){
var fk=function(a){return z.Za.concat.apply(z.Za,arguments)};var gk=function(a,b,c){this.oc=a||null;this.wq=!!c};var hk=function(a){if(!a.Ea&&(a.Ea=new z.Uc,a.Da=0,a.oc))for(var b=a.oc.split("\x26"),c=0;c<b.length;c++){var d=b[c].indexOf("\x3d"),e=null,g=null;0<=d?(e=b[c].substring(0,d),g=b[c].substring(d+1)):e=b[c];e=(0,window.decodeURIComponent)(e.replace(/\+/g," "));e=ik(a,e);a.add(e,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};
var ik=function(a,b){var c=String(b);a.wq&&(c=c.toLowerCase());return c};var jk=function(a){var b=z.Nc(a);if("undefined"==typeof b)throw Error("Keys are undefined");var c=new gk(null,0,void 0);a=z.Mc(a);for(var d=0;d<b.length;d++){var e=b[d],g=a[d];if(z.ia(g)){var h=c;h.remove(e);0<g.length&&(h.oc=null,h.Ea.set(ik(h,e),z.$a(g)),h.Da+=g.length)}else c.add(e,g)}return c};
var kk=function(){window.m_webReaderElem=window.document.getElementById("webReaderModule");window.m_extensionPath=window.m_webReaderElem.getAttribute("data-root");var a=window.document.createElement("link");a.rel="stylesheet";a.type="text/css";a.href=window.m_extensionPath+"assets/checkit/checkit.css";window.m_webReaderElem.appendChild(a);this.Kd(window.m_extensionPath+"assets/checkit/gdciip.js",function(){this.Kd(window.m_extensionPath+"assets/checkit/ciip.js",function(){this.Kd(window.m_extensionPath+
"assets/checkit/ciiprw4gc.js",function(){}.bind(this))}.bind(this))}.bind(this));z.T.a().i("onGetCheckItOnOff",this.or,this)};
var lk=function(a){this.h=this.Wd=this.M=null;this.Vb=!1;null!=z.J("docs-texteventtarget-iframe")&&null!=z.J("docs-texteventtarget-iframe")&&(this.M=z.J("docs-texteventtarget-iframe").contentDocument,this.Wd=z.J("docs-texteventtarget-iframe").contentWindow,this.h=z.J("kix-appview-editor"),this.K=a,new z.yd,this.da=!1,this.fc=this.rb=this.Ja=null,this.V=[],this.wc=!1,this.r={},this.r.ia=0,this.r.Hj="",this.r.Gj="",this.r.Wb=null,this.qd=this.pd=0,this.Nc=/\w/i,this.o={},this.o.parentId="kix-appview-editor",
this.o.positionId="kix-cursor",this.o.seq="1",this.sd=z.S.a().bind(this,this.Mf),this.ce=z.S.a().bind(this,this.ke),this.va=this.T=null,this.zg=this.Be=!1,this.th=null)};var mk=function(a){this.fa=a;this.Jn="";this.Mc=this.pj=0;this.Pn=this.qg=this.Dh="";this.il=null;a=window.location.pathname.split("/");this.lj=a[a.length-2];this.Qn=""};
var nk=function(a){try{var b=new z.yd;z.E(b,"complete",z.S.a().bind(a,a.gr));var c=jk(new z.Uc({Authorization:"Bearer "+a.Mc}));b.send("https://www.googleapis.com/drive/v2/files?q\x3dtitle%3D'TexthelpVoiceNoteConfig'\x26spaces\x3dappDataFolder","GET",null,c)}catch(d){z.S.a().b(d)}};var ok=function(a,b,c){try{var d=new z.yd;null!==c&&z.E(d,"complete",c);var e=jk(new z.Uc({Authorization:"Bearer "+a.Mc}));d.send("https://www.googleapis.com/drive/v2/files/"+b,"GET",null,e)}catch(g){z.S.a().b(g)}};
var pk=function(a){try{var b=new z.yd;z.E(b,"complete",z.S.a().bind(a,a.pr));var c=jk(new z.Uc({Authorization:"Bearer "+a.Mc}));b.send("https://www.googleapis.com/drive/v2/files/"+a.lj+"/properties/voicenotefolder","GET",null,c)}catch(d){z.S.a().b(d)}};var qk=function(a){try{var b=new window.FileReader;b.readAsDataURL(a.Jn);b.onloadend=z.S.a().bind(a,a.$q)}catch(c){z.S.a().b(c)}};var rk=function(a){try{z.S.a().fireEvent(a,"mousedown"),z.S.a().fireEvent(a,"mouseup"),z.S.a().fireEvent(a,"click")}catch(b){z.S.a().b(b)}};
var yk=function(a,b){this.K=a;this.fa=b;this.ld=null;this.vf=this.ul=!1;this.X=this.eb=null;this.Ch=0;this.Al=null;z.E(window.document,"mouseover",this.$d,!0,this);z.E(window.document,"mouseout",this.Dr,!0,this);null!=z.J("docs-texteventtarget-iframe")&&(this.M=z.J("docs-texteventtarget-iframe").contentDocument,this.Hm=z.S.a().bind(this,this.Ul),this.Im=z.S.a().bind(this,this.Vl),this.wp=z.S.a().bind(this,this.Sl))};
var zk=function(a,b){try{(0,window.clearTimeout)(a.Ch),a.vf=!0,a.Ch=(0,window.setTimeout)(a.Im,250),b.play()}catch(c){z.S.a().b(c)}};
var Y=function(){this.vd="kix-selection-overlay";this.Ue="kix-selection-overlay-mac";this.jc="kix-appview-editor";this.wb="kix-cursor";this.Te="kix-cursor-caret";this.ja="kix-lineview";this.jb="kix-lineview-text-block";this.dk="kix-paragraphrenderer";this.ci="kix-page";this.Bm=30;this.Dg="thRWGDns";this.Cg="thCTag";this.Ba=this.Dg+":"+this.Cg;this.N="textHELPWR";this.u="thWord";this.Ga="thSpace";this.Of=100;this.jg=this.qa=null;this.rf=-1;this.Ke=0;this.vc=z.oj.a().Fd();this.sb=this.vc.sentences.wordEnds;
this.ta=[];this.hl=[];this.og=0;this.eg=null;this.Bh=!1;this.Nc=/\w/i;this.ec=/[\u200B-\u200D\uFEFF\u25A0-\u27A2]/g;this.h=z.J(this.jc);this.He=[];this.kg=this.Ka=null;this.Ib=-1;this.sf=!1;this.Ub=null;this.uf=z.S.a().bind(this,this.Zd);z.S.a();this.fa=new lk(this);this.Sq=new yk(this,this.fa);window.addEventListener("message",this.uf,!1);z.T.a().i("onSpeechStateChanged",this.Bo,this);z.T.a().i("onBarToggled",this.Kl,this);z.T.a().i("onBarClosed",this.Jl,this);z.T.a().i("onBrowserAction",this.Ll,
this);this.Td=null;var a=this.fa;if(null!=a.M){var b=z.S.a().bind(a,a.Pc);a.M.addEventListener("keyup",b,!0);b=z.S.a().bind(a,a.Ih);a.M.addEventListener("keypress",b,!0);b=z.S.a().bind(a,a.Kb);a.M.addEventListener("keydown",b,!0);b=z.S.a().bind(a,a.Lb);z.E(window.document,"click",b,!0);b=z.S.a().bind(a,a.ae);z.E(window.document,"mouseup",b);b=z.S.a().bind(a,a.Gh);z.E(a.h,"scroll",b);b=z.S.a().bind(a,a.Ml);z.E(window,"resize",b);z.T.a().i("onPredictionChange",a.be,a);z.T.a().i("onWRPredictionStateChanged",
a.Qc,a);z.T.a().i("onSpeechRecognitionChange",a.Kh,a);z.T.a().i("onFocusOnCursor",a.Hh,a)}new kk;this.od=null};
var Ak=function(a,b,c,d){try{var e=window.document.querySelector('[aria-label\x3d"Ctrl+Alt+A Ctrl+Alt+H"]');null==e&&(e=window.document.querySelector('[aria-label\x3d"Ctrl+\u2318A Ctrl+\u2318H"]'));var g=null;if(null==e){if(b>a.Bm){d();return}}else if(g=e.closest(".apps-menuitem"),null!==g&&(g=g.previousElementSibling),null==g&&b>a.Bm){d();return}null==g?(0,window.setTimeout)(function(){Ak(this,++b,c,d)}.bind(a),300):c(g)}catch(h){window.console.log(h)}};
var Bk=function(a,b){var c={};c.Ng=z.J(a.Te);if(null==c.Ng)return c;c.ne=z.Q(c.Ng);var d=z.Oj(c.Ng,"height"),d=d.substr(0,d.length-2),d=(0,window.parseInt)(d/2,10),e=0;a.S(c.Ng,"kix-cursor-italic")&&(e=d/Math.tan(Math.PI/180*77));c.ne.y+=d;c.ne.x+=e+(c.Ng.offsetWidth/2+.5);c.element=Ck(a,c.ne.x,c.ne.y,b);return c};
var Ck=function(a,b,c,d){a=a.Wf(b,c);b=null;for(c=0;c<a.length;c++){if("string"==typeof a[c].className&&void 0!==a[c].className&&-1<a[c].className.indexOf(d))if(-1<a[c].className.indexOf("kix-lineview-content"))b=a[c];else return a[c];if("kix-lineview"==a[c].className)return a[c]}return b};var Dk=function(a,b,c){for(var d=0;d<b.length;d++)Ek(a,[b[d].toLowerCase()],c)};
var Ek=function(a,b,c){b=b.map(function(a){return a.toLowerCase()});for(var d=0;d<c.length;d++)for(var e=c[d],g=e.filter(function(a){return"is"==a.ty})[0].s,h=e.filter(function(a){return"is"==a.ty})[0].ibi,e=e.filter(function(a){var c="text"==a.st,d=a.sm&&a.sm.ts_bgc&&-1!=b.indexOf(a.sm.ts_bgc);return"as"==a.ty&&c&&d}),l=0;l<e.length;l++){var m=e[l].si-h;a.tk.push({text:g.substr(m,e[l].ei-h-m+1),color:e[l].sm.ts_bgc.toUpperCase()})}};
var Fk=function(a,b,c,d){try{var e=new window.XMLHttpRequest;e.onreadystatechange=function(){if(4==e.readyState&&200==e.status){var a=window.document.createElement("div");a.id="th-page-reloaded";a.style.display="none";a.innerHTML=e.responseText;var g={tk:[],title:window.document.getElementsByClassName("docs-title-input")[0].getAttribute("value"),url:window.location.href},m=[];z.S.a().Wj(a.getElementsByTagName("script")).filter(function(a){return"DOCS_modelChunk \x3d ["==a.innerHTML.substr(0,19)}).forEach(function(a){a=
a.innerHTML.replace("DOCS_modelChunk \x3d ","");a=a.substr(0,a.lastIndexOf("}]; ")+2);a=JSON.parse(a);m.push(a)});2==b?Dk(g,c,m):Ek(g,c,m);d(g)}}.bind(a);e.open("GET",window.location.href,!0);e.send()}catch(g){z.S.a().b(g)}};
var Gk=function(a,b,c){var d=b.nextSibling;null!==d?(a.fe(d,a.h),(0,window.setTimeout)(function(){var a=z.Ee(d);if(0<a.length&&" "!==a)if(window.paragraph=z.J(this.dk,d),null==window.paragraph)Gk(this,d,c);else{if(window.nextPageLine=this.sn(window.paragraph,!0),null!==window.nextPageLine)if(a=window.nextPageLine.closest(".kix-page-header"),null!==a){if(null!==a.nextElementSibling)if(1>a.nextElementSibling.textContent.trim().length)Gk(this,d,c);else{for(var a=a.nextSibling.querySelectorAll("."+this.ja),
b=null,h=0;h<a.length;h++)0<a[h].textContent.trim().length&&(b=a[h],h=a.length);null!==b&&c(this.Ui(b))}}else c(this.Ui(window.nextPageLine))}else Gk(this,d,c)}.bind(a),100)):c([])};
var Hk=function(a){try{for(var b=["thrwgdns:thctag","title","desc"];void 0!=a.nodeName&&b.includes(a.nodeName.toLowerCase());)if(null!=a.parentElement)a=a.parentElement;else break;return void 0==a.nodeName?!1:"svg"==a.nodeName.toLowerCase()||"image"==a.nodeName.toLowerCase()||"desc"==a.nodeName.toLowerCase()||"title"==a.nodeName.toLowerCase()?!0:!1}catch(c){return!1}};
var Ik=function(a){for(var b=a;!a.classList.contains("kix-embeddedobject-crop");)if(null!=a.parentElement)a=a.parentElement;else break;return a.classList.contains("kix-embeddedobject-crop")?a:b};var Jk=function(a,b){try{a.eg=z.X(a.ci);a.og=a.h.scrollTop;a.sf=!1;var c=z.S.a().bind(a,a.Kj);(0,window.setTimeout)(function(){c(0,b)},0)}catch(d){z.S.a().b(d)}};
z.S.prototype.Wf=z.ca(19,function(a,b){if(void 0!==window.document.Wf)return window.document.Wf(a,b);for(var c=[],d=[],e,g;(e=window.document.elementFromPoint(a,b))&&-1===c.indexOf(e)&&null!=e;)c.push(e),d.push({value:e.style.getPropertyValue("pointer-events"),fm:e.style.getPropertyPriority("pointer-events")}),e.style.setProperty("pointer-events","none","important");for(e=d.length;g=d[--e];)c[e].style.setProperty("pointer-events",g.value?g.value:"",g.fm);return c});
z.Uc.prototype.Uf=z.ca(1,function(a){return z.Wc(this.Oc,a)});z.f=gk.prototype;z.f.Ea=null;z.f.Da=null;z.f.nn=function(){hk(this);return this.Da};z.f.add=function(a,b){hk(this);this.oc=null;a=ik(this,a);var c=this.Ea.get(a);c||this.Ea.set(a,c=[]);c.push(b);this.Da++;return this};z.f.remove=function(a){hk(this);a=ik(this,a);return this.Ea.Uf(a)?(this.oc=null,this.Da-=this.Ea.get(a).length,this.Ea.remove(a)):!1};z.f.clear=function(){this.Ea=this.oc=null;this.Da=0};
z.f.Uf=function(a){hk(this);a=ik(this,a);return this.Ea.Uf(a)};z.f.gd=function(){hk(this);for(var a=this.Ea.Hd(),b=this.Ea.gd(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};z.f.Hd=function(a){hk(this);var b=[];if(z.s(a))this.Uf(a)&&(b=fk(b,this.Ea.get(ik(this,a))));else{a=this.Ea.Hd();for(var c=0;c<a.length;c++)b=fk(b,a[c])}return b};
z.f.set=function(a,b){hk(this);this.oc=null;a=ik(this,a);this.Uf(a)&&(this.Da-=this.Ea.get(a).length);this.Ea.set(a,[b]);this.Da++;return this};z.f.get=function(a,b){var c=a?this.Hd(a):[];return 0<c.length?String(c[0]):b};
z.f.toString=function(){if(this.oc)return this.oc;if(!this.Ea)return"";for(var a=[],b=this.Ea.gd(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.Hd(d),g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="\x3d"+(0,window.encodeURIComponent)(String(d[g])));a.push(h)}return this.oc=a.join("\x26")};z.f.clone=function(){var a=new gk;a.oc=this.oc;this.Ea&&(a.Ea=this.Ea.clone(),a.Da=this.Da);return a};
z.f.extend=function(a){for(var b=0;b<arguments.length;b++)z.Oc(arguments[b],function(a,b){this.add(b,a)},this)};
kk.prototype.Kd=function(a,b){var c=window.document.documentElement.getElementsByTagName("body")[0];if(null==c||void 0==c)c=window.document.body;var d=window.document.createElement("script");d.src=a;d.async=!0;d.onload=d.onreadystatechange=function(){this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(d.onload=d.onreadystatechange=null,c.removeChild(d),void 0!=b&&b())};c.appendChild(d)};
kk.prototype.or=function(a){try{if(a[0]){if(null==window.texthelp.CheckitLib.checkItManagerInstance){var b=window.document.querySelector("#thSpeechStreamTBPlaceHolder").getAttribute("data-root").split("/")[2];window.texthelp.CheckitLib.checkItManagerInstance=new window.texthelp.CheckitLib.CheckItManagerRW4GC(window.location.href,b)}var c=z.V.a().I().language.Tu;window.texthelp.CheckitLib.checkItManagerInstance.language=c;window.texthelp.CheckitLib.checkItManagerInstance.checkItOn();window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose()}else window.texthelp.CheckitLib.checkItManagerInstance.checkItOff()}catch(d){z.S.a().b(d)}};
kk.prototype.mn=function(){};z.f=lk.prototype;z.f.Pc=function(a){var b=[];b.push(a.keyCode);z.T.a().k("onKeyUpEvent",b);null!==this.T&&((0,window.clearTimeout)(this.T),this.T=null);a.ctrlKey&&17!==a.keyCode&&(this.zg=!0,null!==this.th&&(0,window.clearTimeout)(this.th),this.th=(0,window.setTimeout)(function(){(0,window.clearTimeout)(this.th);this.th=null;this.zg=!1}.bind(this),1E3));this.Be=17===a.keyCode?this.zg?!1:!0:!1;this.T=(0,window.setTimeout)(this.sd,100)};z.f.Ih=function(){};
z.f.Kb=function(a){if("Shift"!==window.event.key&&"Control"!==window.event.key&&"Alt"!==window.event.key){if(this.Vb)if(-1=="?!.,:;'".indexOf(window.event.key))this.Vb=this.Be=!1;else{var b=this.K.pc().context.split("");if(2>b.length){this.Vb=this.Be=!1;return}var c=b[b.length-2];" "==b[b.length-1]&&" "!==c&&(window.event.preventDefault(),window.event.stopPropagation(),this.ra("Backspace"),this.Ne(window.event.key+" "))}this.Vb=!1}if(a.ctrlKey&&47<a.keyCode&&58>a.keyCode){var d=[];d.push(a);null!==
this.Ja&&((0,window.clearTimeout)(this.Ja),this.Ja=null);this.Ja=(0,window.setTimeout)(function(){this.Nl(d)}.bind(this),10);z.Xj()&&(a.preventDefault(),a.stopPropagation())}40===a.keyCode&&this.Be&&(this.zg=this.Be=!1,a.preventDefault(),a.stopPropagation(),window.texthelp.RW4GC.thToolbarStoreInstance.onFocusBar(window.document.activeElement));this.K.Vf(a.key);this.Be=!1};z.f.Nl=function(a){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionKeyDown(a)};
z.f.xa=function(){null!==this.T&&((0,window.clearTimeout)(this.T),this.T=null);this.T=(0,window.setTimeout)(this.sd,10)};
z.f.Mf=function(){this.T=null;if(this.da){var a=this.K.pc();if(null==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{var b=a.context.substr(a.context.length-1);if(0==a.context.length||" "==b||-1!==".?!".indexOf(b)){var b=z.S.a().nb(),c=z.V.a().I().prediction.predictahead;if(!b["Predict Ahead"]||!c){window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();return}}b=z.V.a().I().prediction.results;c=z.V.a().I().language.services;this.r.ia++;999<this.r.ia&&(this.r.ia=0);
var d='"'+z.S.a().Pf(a.context)+'","'+b+'","en_US"',e='{ "parent":"'+this.K.jc+'", "position":"'+this.K.wb+'","addSpace":false,"seq":"'+this.r.ia+'"}';z.S.a().wg(this.r.ia);this.r.Wb=a;e=z.pd(e);d=[];d[0]=a.context;d[1]=b;d[2]=c;if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else e.context=d,window.postMessage({method:"thPrediction",type:"1757FROM_PAGERW4G",payload:e},"*")}}};
z.f.ae=function(){if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose(),this.qe();else return!0};z.f.Gh=function(){try{var a=this.K.ya();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,this.h.className)}catch(b){}};z.f.Ml=function(){(0,window.setTimeout)(function(){var a=this.K.ya();if(null!==a)window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionPositionUpdate(a,this.h.className)}.bind(this),0)};
z.f.ke=function(a){if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose(),this.qe();else{var b=z.Ke(a.target,"kix-lineview-text-block");null==b&&(b=z.J("kix-lineview-text-block",a.target.parentNode));null!==b&&(this.da&&this.xa(),this.qe())}};z.f.Lb=function(a){this.Vb=!1;null!==this.va&&((0,window.clearTimeout)(this.va),this.va=null);var b=this;this.va=(0,window.setTimeout)(function(){b.ce(a)},300)};z.f.qe=function(){z.T.a().k("onWordChanged",[])};
z.f.be=function(a){try{if(null!==z.J("kix-selection-overlay"))window.texthelp.RW4GC.thToolbarStoreInstance.onPredictionClose();else{this.Vb=!0;var b=this.r.Wb,c=b.prepunc+a[0]+b.postpunc;this.ra("ArrowRight",b.selectRight);this.ra("Shift+ArrowLeft",b.selectLeft+b.selectRight);b.spaceatstart&&(c=" "+c);b.spaceatend&&(c+=" ");this.Ne(c);b.spaceatend||this.ra("ArrowRight");this.Vb=!0;var d=z.S.a().Ma();a=[];a.push("prediction insert");a.push(d.Email);a.push(d.Email.split("@")[1]);window.postMessage({type:"1757FROM_PAGERW4G",
key:"function",method:"SendEvent",parameters:a},"*");this.xa()}}catch(e){z.S.a().b(e)}};z.f.Qc=function(a){try{this.da=a[0];var b=z.J("kix-cursor-caret",this.h);if(null!==b&&this.da){var c=0,d=z.Q(b),e=z.Oj(b,"height"),e=e.substr(0,e.length-2),e=(0,window.parseInt)(e,10);d.y+=e/2;z.S.a().S(b,"kix-cursor-italic")&&(c=e/Math.tan(Math.PI/180*77));d.x+=c;this.ri(d.x,d.y)}this.da&&(a=[],a.push("kix-appview-editor"),this.xa(),z.T.a().k("onOpenPredictionWindow",a))}catch(g){z.S.a().b(g)}};
z.f.Hh=function(){try{var a=z.J("kix-cursor-caret",this.h);null!==a&&(z.S.a().fireEvent(a,"click"),a.focus())}catch(b){z.S.a().b(b)}};z.f.Kh=function(a){try{"scratch that"==a.toLowerCase().trim()?this.ra("CTRL+Z"):this.Ne(a)}catch(b){z.S.a().b(b)}};z.f.rc=function(){this.V.keydown=this.Bb("keydown",this.M);this.V.keyup=this.Bb("keyup",this.M);this.V.keypress=this.Bb("keypress",this.M);this.V.mousedown=this.Bb("mousedown",this.h);this.V.mouseup=this.Bb("mouseup",window.document);this.wc=!0};
z.f.Bb=function(a,b){try{var c=[],d;for(d in b)if(d.match(/^closure/)&&"number"!=typeof b[d]){var e=b[d];if(e){if(!this.rb)for(var g in e){var h=e[g];if(h&&h!=b)for(var l in h){var m=h[l];m&&void 0!=m.length&&m[0].src==b&&(this.rb=g)}}for(var n in e[this.rb])if(n==a)for(var p=e[this.rb][n],q=0;q<p.length;q++){if(!this.fc&&p[q].src==b)for(var u in p[q])if(p[q][u].src==b){this.fc=u;break}c.push({en:p[q],Cc:p[q][this.fc]})}}}return c}catch(r){z.S.a().b(r)}};
z.f.ra=function(a,b,c){void 0==c&&(c="keydown");void 0==b&&(b=1);if(!(1>b)){this.wc||this.rc();void 0==b&&(b=1);var d={altGraphKey:!1,altKey:!1,bubbles:!0,cancelBubble:!1,cancelable:!0,charCode:0,clipboardData:void 0,ctrlKey:!1,currentTarget:this.M,defaultPrevented:!1,detail:0,eventPhase:0,keyCode:0,keyLocation:0,layerX:0,layerY:0,metaKey:!1,pageX:0,pageY:0,returnValue:!0,shiftKey:!1,srcElement:this.M.body,target:this.M.body,timeStamp:(new Date).getTime(),type:c,view:this.Wd,which:0};switch(a){case "Alt+V":d.keyCode=
86;d.which=86;d.altKey=!0;break;case "R":d.keyCode=82;d.which=82;d.charCode=82;d.code="KeyR";d.key="r";break;case "ESC":d.keyCode=27;d.which=27;break;case "SPACE":d.keyCode=32;d.which=32;break;case "CTRL+Z":d.ctrlKey=!0;d.keyCode=90;d.which=90;break;case "Apple+Z":d.metaKey=!0;d.keyCode=90;d.which=90;break;case "Delete":d.defaultPrevented=!0;d.keyCode=8;d.which=8;break;case "Backspace":d.defaultPrevented=!0;d.keyCode=8;d.which=8;break;case "Newline":d.defaultPrevented=!0;d.keyCode=13;d.which=13;break;
case "Home":d.keyCode=36;d.which=36;break;case "CTRL+Home":d.ctrlKey=!0;d.keyCode=36;d.which=36;break;case "Shift+ArrowLeft":d.keyCode=37;d.shiftKey=!0;d.which=37;break;case "Shift+ArrowRight":d.keyCode=39;d.shiftKey=!0;d.which=39;break;case "ArrowRight":d.keyCode=39;d.which=39;break;case "ArrowLeft":d.keyCode=37;d.which=37;break;case "CTRL+Shift+ArrowRight":d.ctrlKey=!0;d.keyCode=39;d.shiftKey=!0;d.which=39;break;case "CTRL+ALT+M":d.ctrlKey=!0;d.keyCode=77;d.shiftKey=!1;d.altKey=!0;d.which=77;break;
case "CMD+ALT+M":d.metaKey=!0;d.keyCode=77;d.shiftKey=!1;d.altKey=!0;d.which=77;break;case "CTRL+Shift+S":d.ctrlKey=!0;d.keyCode=83;d.shiftKey=!0;d.altKey=!1;d.which=83;break;case "CMD+Shift+S":d.metaKey=!0;d.keyCode=83;d.shiftKey=!0;d.altKey=!1;d.which=83;break;case "CTRL+Shift+F":d.ctrlKey=!0;d.keyCode=70;d.shiftKey=!0;d.altKey=!1;d.which=70;break;case "CMD+Shift+F":d.metaKey=!0;d.keyCode=70;d.shiftKey=!0;d.altKey=!1;d.which=70;break;case "CTRL+Alt+A":d.ctrlKey=!0;d.charCode=65;d.keyCode=65;d.shiftKey=
!1;d.altKey=!0;d.which=65;d.code="KeyA";d.key="a";break;case "CTRL+CMD+A":d.ctrlKey=!0;d.metaKey=!0;d.charCode=65;d.keyCode=65;d.shiftKey=!1;d.altKey=!1;d.which=65;d.code="KeyA";d.key="a";break;case "CTRL+Alt+H":d.ctrlKey=!0;d.charCode=72;d.keyCode=72;d.shiftKey=!1;d.altKey=!0;d.which=72;d.code="KeyH";d.key="h";break;case "CTRL+CMD+H":d.ctrlKey=!0;d.metaKey=!0;d.charCode=72;d.keyCode=72;d.shiftKey=!1;d.altKey=!1;d.which=72;d.code="KeyH";d.key="h";break;default:return}for(a=0;a<b;a++)for(var e in this.V[c])this.V[c][e].Cc(d)}};
z.f.Ne=function(a){this.wc||this.rc();for(var b={altGraphKey:!1,altKey:!1,bubbles:!0,cancelBubble:!1,cancelable:!0,charCode:0,clipboardData:void 0,ctrlKey:!1,currentTarget:this.M,defaultPrevented:!0,detail:0,eventPhase:0,keyCode:0,keyLocation:0,layerX:0,layerY:0,metaKey:!1,pageX:0,pageY:0,returnValue:!0,shiftKey:!1,srcElement:this.M.body,target:this.M.body,timeStamp:0,type:"keypress",view:this.Wd,which:0},c,d=0;d<a.length;d++){c=a[d];b.charCode=c.charCodeAt(0);b.keyCode=c.charCodeAt(0);b.which=c.charCodeAt(0);
b.shiftKey=c.toUpperCase()==c?!0:!1;b.timeStamp=(new Date).getTime();try{switch(b.keyCode){case 10:if(0<d){if(10!=a[d-1].charCodeAt(0)){b.charCode=13;b.keyCode=13;b.which=13;var e}}else b.charCode=13,b.keyCode=13,b.which=13;for(e in this.V.keydown)this.V.keydown[e].Cc(b);break;case 13:for(e in this.V.keydown)this.V.keydown[e].Cc(b);break;default:for(e in this.V.keypress)this.V.keypress[e].Cc(b)}}catch(g){}}};
z.f.ri=function(a,b){this.wc||this.rc();z.Q(this.h);if(!(a<this.h.x||a>this.h.x+this.h.offsetWidth||b<this.h.y||b>this.h.y+this.h.offsetHeight)){var c=z.S.a().bind(this,this.Tg);this.pd=a;this.qd=b;(0,window.setTimeout)(c,1)}};
z.f.Tg=function(){var a={altKey:!1,bubbles:!0,button:0,cancelBubble:!1,cancelable:!0,charCode:0,clientX:this.pd,clientY:this.qd,clipboardData:void 0,ctrlKey:!1,currentTarget:window.document,dataTransfer:null,defaultPrevented:!1,detail:1,eventPhase:0,fromElement:null,keyCode:0,layerX:0,layerY:0,metaKey:!1,offsetX:0,offsetY:0,pageX:0,pageY:0,relatedTarget:null,returnValue:!0,screenX:0,screenY:0,shiftKey:!1,srcElement:this.h,target:this.h,timeStamp:(new Date).getTime(),toElement:this.h,type:null,view:window,
which:1,x:0,y:0},b=["mousedown","mouseup"],c;for(c in b){a.type=b[c];"mouseup"==b[c]&&(a.srcElement=a.target=a.toElement=window.document);for(var d in this.V[b[c]])this.V[b[c]][d].Cc(a)}};z.f=mk.prototype;z.f.yc=function(a,b){try{this.pj=z.T.a().i("onAddVoiceNoteToken",this.fs,this),window.postMessage({type:"1757FROM_PAGERW4G",key:"function",method:"AddVoiceNote",parameters:[]},"*"),this.Jn=a,this.il=b}catch(c){z.S.a().b(c)}};z.f.fs=function(a){try{z.T.a().Qe(this.pj),this.Mc=a,nk(this)}catch(b){z.S.a().b(b)}};
z.f.gr=function(a){try{var b=JSON.parse(a.target.L.response).items;if(0==b.length)try{var c=new z.yd;z.E(c,"complete",z.S.a().bind(this,this.qs));var d=jk(new z.Uc({Authorization:"Bearer "+this.Mc,"Content-type":"application/json"})),e='{"title": "'+z.U.a().ha("voicenote_folder")+'","mimeType": "application/vnd.google-apps.folder"}';c.send("https://www.googleapis.com/drive/v2/files","POST",e,d)}catch(g){z.S.a().b(g)}else{var h=b[0];try{this.Pn=h.id,this.Dh=h.description,ok(this,this.Dh,z.S.a().bind(this,
this.ps))}catch(l){z.S.a().b(l)}}}catch(m){z.S.a().b(m)}};z.f.er=function(){try{pk(this)}catch(a){z.S.a().b(a)}};
z.f.qs=function(a){try{var b=this.Dh=JSON.parse(a.target.L.response).id;try{var c=new z.yd;z.E(c,"complete",z.S.a().bind(this,this.er));var d=jk(new z.Uc({Authorization:"Bearer "+this.Mc,"Content-type":"application/json"}));c.send("https://www.googleapis.com/drive/v2/files?q\x3dtitle%3D'TexthelpVoiceNoteConfig'","POST",'{"title": "TexthelpVoiceNoteConfig","parents": [{"id": "appfolder"}],"description": "'+b+'"}',d)}catch(e){z.S.a().b(e)}}catch(g){z.S.a().b(g)}};
z.f.ps=function(a){try{var b=JSON.parse(a.target.L.response);if(void 0!==b.error||b.labels.trashed){var c=this.Pn,d=z.S.a().bind(this,this.jr);try{var e=new z.yd;null!==d&&z.E(e,"complete",d);var g=jk(new z.Uc({Authorization:"Bearer "+this.Mc}));e.send("https://www.googleapis.com/drive/v2/files/"+c,"DELETE",null,g)}catch(h){z.S.a().b(h)}}else pk(this)}catch(l){z.S.a().b(l)}};z.f.jr=function(){try{nk(this)}catch(a){z.S.a().b(a)}};
z.f.pr=function(a){try{var b=JSON.parse(a.target.L.response);void 0!==b.error?ok(this,this.lj,z.S.a().bind(this,this.vo)):(this.qg=b.value,ok(this,this.qg,z.S.a().bind(this,this.rs)))}catch(c){z.S.a().b(c)}};
z.f.vo=function(a){try{this.Qn=JSON.parse(a.target.L.response).title;try{var b=new z.yd;z.E(b,"complete",z.S.a().bind(this,this.ir));var c=jk(new z.Uc({Authorization:"Bearer "+this.Mc,"Content-type":"application/json"}));b.send("https://www.googleapis.com/drive/v2/files","POST",'{"title": "'+this.Qn+'","parents": [{"id": "'+this.Dh+'"}],"mimeType": "application/vnd.google-apps.folder"}',c)}catch(d){z.S.a().b(d)}}catch(e){z.S.a().b(e)}};
z.f.rs=function(a){try{var b=JSON.parse(a.target.L.response);void 0!==b.error||b.labels.trashed?ok(this,this.lj,z.S.a().bind(this,this.vo)):qk(this)}catch(c){z.S.a().b(c)}};
z.f.ir=function(a){try{this.qg=JSON.parse(a.target.L.response).id;var b=new z.yd;z.E(b,"complete",z.S.a().bind(this,this.ks));var c=jk(new z.Uc({Authorization:"Bearer "+this.Mc,"Content-type":"application/json"}));b.send("https://www.googleapis.com/drive/v2/files/"+this.lj+"/properties","POST",'{"key": "voicenotefolder","value": "'+this.qg+'"}',c)}catch(d){z.S.a().b(d)}};
z.f.ks=function(){try{var a=new z.yd;z.E(a,"complete",z.S.a().bind(this,this.Xr));var b=jk(new z.Uc({Authorization:"Bearer "+this.Mc,"Content-type":"application/json"}));a.send("https://www.googleapis.com/drive/v2/files/"+this.qg+"/permissions","POST",'{"role": "reader","type": "anyone"}',b)}catch(c){z.S.a().b(c)}};z.f.Xr=function(a){try{JSON.parse(a.target.L.response),qk(this)}catch(b){z.S.a().b(b)}};
z.f.$q=function(a){try{var b=a.currentTarget.result.replace(/^data:audio\/(wav|ogg);base64,/,""),c=new z.yd;z.E(c,"complete",z.S.a().bind(this,this.Zq));var d=jk(new z.Uc({Authorization:"Bearer "+this.Mc,"Content-type":'multipart/form-data; boundary\x3d"rw4g"'})),e='--rw4g\nContent-Type: application/json; charset\x3dUTF-8\n\n{"title": "'+z.U.a().ha("voicenote_filename")+'.wav", "description": "Read\x26Write for Google Chrome\u2122", "mimeType": "audio/wav","parents": [{"id": "'+this.qg+'"}]}\n--rw4g\nContent-Type: audio/wav\nContent-Transfer-Encoding: base64\n\n'+
b+"\n--rw4g--\n";c.send("https://www.googleapis.com/upload/drive/v2/files?uploadType\x3dmultipart","POST",e,d)}catch(g){z.S.a().b(g)}};
z.f.Zq=function(a){try{this.fa.ra("CTRL+ALT+M",1,"keydown");this.fa.ra("CTRL+ALT+M",1,"keyup");this.fa.ra("CMD+ALT+M",1,"keydown");this.fa.ra("CMD+ALT+M",1,"keyup");var b=window.document.activeElement;this.il();z.J("docos-input-buttons-post",b.parentElement);var c;var d=a.target;c=d.L?z.pd(d.L.responseText):void 0;var e=c.webContentLink.split("\x26")[0];b.value="Texthelp;"+e+";";b.focus();b.click();this.Gb=null;rk(b);try{var g=z.J("docos-input-buttons-post",b.parentElement);rk(g)}catch(h){z.S.a().b(h)}}catch(l){z.S.a().b(l)}};z.f=yk.prototype;z.f.yc=function(a,b){try{null==this.Al&&(this.Al=new mk(this.fa)),this.Al.yc(a,b)}catch(c){z.S.a().b(c)}};
z.f.$d=function(a){try{var b=a.target;if(void 0!=b&&void 0!=b.classList&&null!=b.classList){var c=z.Ke(b,"docos-anchoreddocoview");if(null!=c){var d=z.J("docos-collapsible-replyview",c);if(null!=d&&d!=this.ld){this.ul=!0;var e=z.J("kix-thvoicenote-overlay");z.ue(e);this.vf=!1;this.X=null;this.ld=d;if(null!=this.ld){var g=this.ld.innerText;if(-1!=g.indexOf("Texthelp;https://")&&null!=z.Ke(this.ld,"docos-anchoreddocoview")){var h=g.split(";")[1],e=z.J("kix-thvoicenote-overlay");null==e&&(e=z.Si(z.Kk));
e.style.top=(0,window.parseInt)(this.ld.offsetTop)+"px";e.style.left=(0,window.parseInt)(this.ld.offsetLeft)+"px";e.style.width=(0,window.parseInt)(this.ld.offsetWidth)+"px";e.style.height=(0,window.parseInt)(this.ld.offsetHeight)+"px";e.style.background="white";e.style.visibility="visible";var l=z.J("thVNPlayback",e);this.eb={Cj:l.getAttribute("data-percent")||0,size:l.getAttribute("data-size")||60,lineWidth:l.getAttribute("data-line")||4,rotate:l.getAttribute("data-rotate")||0};var m=window.document.createElement("canvas");
"undefined"!==typeof window.G_vmlCanvasManager&&window.G_vmlCanvasManager.yu(m);this.X=m.getContext("2d");m.width=m.height=this.eb.size;m.id="thVNCanPlayback";m.className="thVNCanPlayback";l.appendChild(m);this.X.translate(this.eb.size/2,this.eb.size/2);this.X.rotate((-.5+this.eb.rotate/180)*Math.PI);this.X.translate(.5,.5);this.Ya(this.X,"#efefef",this.eb.lineWidth,1);0<this.eb.Cj&&this.Ya(this.X,"#555555",this.eb.lineWidth,this.eb.Cj/100);var n=z.J("thVNCanPlayback",e),p=z.J("thVNIcon",e);z.E(n,
"mouseup",this.wp,!0,this);z.E(p,"mouseup",this.Gr,!0,this);var q=z.J("thVNAudio",e);q.src=h;this.ld.parentElement.appendChild(e);q.onended=this.Hm}}}}}}catch(u){z.S.a().b(u)}};z.f.Dr=function(a){try{if(this.ul){var b=a.Za.toElement;void 0!=b&&void 0!=b.classList&&null!=b.classList&&null===z.Ke(b,"docos-anchoreddocoview")&&(this.ul=!1)}}catch(c){z.S.a().b(c)}};
z.f.Gr=function(a){try{var b=z.Ke(a.currentTarget,"thVNPlayback");if(null!=b){var c=z.J("thVNIcon",b);if(null!=c){var d=z.J("thVNAudio",b);if(this.vf){this.vf=!1;z.S.a().zd(c,"thVNPause","thVNPlay");try{d.pause()}catch(e){z.S.a().b(e)}}else{this.vf=!0;z.S.a().zd(c,"thVNPlay","thVNPause");zk(this,d);var g=z.S.a().ua();if(null==g)return null;window.postMessage({method:"GAE",type:"1757FROM_PAGERW4G",payload:{category:g,action:"voice note play",label:g.split("@")[1]}},"*")}}}}catch(h){z.S.a().b(h)}};
z.f.Sl=function(a){try{var b=z.J("thVNAudio");if(null!=b){var c=z.Q(a.currentTarget),d,e;d=a.clientX-c.x;e=a.clientY-c.y;var g=z.pg(a.currentTarget),h=2*Math.PI,l=(0,window.parseInt)((Math.atan2(e-g.height/2,d-g.width/2)+h)%h/h*100),l=l+25;99<l&&(l-=100);b.currentTime=l/100*b.duration;zk(this,b);var m=z.Ke(a.currentTarget,"thVNPlayback");if(null!=m){var n=z.J("thVNIcon",m);null!=n&&z.S.a().S(n,"thVNPlay")&&z.S.a().zd(n,"thVNPlay","thVNPause")}}}catch(p){z.S.a().b(p)}};
z.f.Ul=function(a){try{this.vf=!1;(0,window.clearTimeout)(this.Ch);this.Ch=0;var b=a.currentTarget;if(null!=b){var c=b.parentElement;if(null!=c){var d=z.J("thVNIcon",c);null!=d&&(this.X.clearRect(-100,-100,200,200),this.Ya(this.X,"#efefef",this.eb.lineWidth,1),0<this.eb.Cj&&this.Ya(this.X,"#555555",this.eb.lineWidth,this.eb.Cj/100),z.S.a().zd(d,"thVNPause","thVNPlay"))}}}catch(e){z.S.a().b(e)}};
z.f.Vl=function(){try{if(this.vf){var a=z.J("thVNAudio");if(null!=a){var b=(100/a.duration*a.currentTime).toFixed();this.X.clearRect(-100,-100,200,200);this.Ya(this.X,"#efefef",this.eb.lineWidth,1);this.Ya(this.X,"#555555",this.eb.lineWidth,b/100);this.Ch=(0,window.setTimeout)(this.Im,250)}}}catch(c){z.S.a().b(c)}};
z.f.Ya=function(a,b,c,d){d=Math.min(Math.max(0,d||1),1);var e=(this.eb.size-this.eb.lineWidth)/2;a.beginPath();a.arc(0,0,e,0,2*Math.PI*d,!1);a.strokeStyle=b;a.lineCap="round";a.lineWidth=c;a.stroke()};z.ek.Mh="Parser";z.B(Y,z.Uj);z.f=Y.prototype;z.f.Gf=function(a){try{this.qa=a}catch(b){z.S.a().b(b)}};z.f.Cb=function(){try{return this.qa.name}catch(a){z.S.a().b(a)}};z.f.Ab=function(){try{return this.qa.bar}catch(a){z.S.a().b(a)}};z.f.Bo=function(a){this.Bh=0<a.length?a[0]:!1};z.f.Kl=function(){this.af()};z.f.Jl=function(){this.af()};z.f.Ll=function(){this.af()};
z.f.af=function(){try{null!==this.od?(0,window.requestAnimationFrame)(function(){z.S.a().fireEvent(this.od,"mousedown");z.S.a().fireEvent(this.od,"mouseup");z.S.a().fireEvent(this.od,"mousedown");z.S.a().fireEvent(this.od,"mouseup")}.bind(this)):(0,window.setTimeout)(function(){Ak(this,0,function(a){this.od=a;(0,window.requestAnimationFrame)(function(){z.S.a().fireEvent(this.od,"mousedown");z.S.a().fireEvent(this.od,"mouseup");z.S.a().fireEvent(this.od,"mousedown");z.S.a().fireEvent(this.od,"mouseup")}.bind(this))}.bind(this),
function(){var a=window.document.querySelector(".th-RW4GC-toolbar");null!==a&&(a.classList.remove("toolbar--down"),a.classList.add("toolbar--down--nosticky"))}.bind(this))}.bind(this),1E3)}catch(a){window.console.log(a)}};z.f.yc=function(a,b){try{this.Sq.yc(a,b)}catch(c){z.S.a().b(c)}};
z.f.bg=function(){try{var a=this.Ec(),b=!1;z.S.a();for(var c=this.vc.sentences.sentenceEndExclusions,d=0;d<a.length-1;d++){var e=z.Vj(c,a[d]);if(!e){try{e=this.hl[d]}catch(g){e=!1}void 0==e&&(e=!1)}if(!e)for(var h in this.sb)-1!==a[d].search(this.sb[h])&&(b=!0,d=a.length)}if(!b)return a;var l=z.X(this.vd);if(1>l.length&&(l=z.X(this.Ue),1>l.length))return this.Vi(!0);var l=Array.prototype.slice.call(l,0),m=z.S.a().bind(this,this.Sj);l.sort(m);this.la();var n=z.Q(l[0]),p=z.Oj(l[0],"height"),p=p.substr(0,
p.length-2),p=(0,window.parseInt)(p,10);n.y+=p/2;this.Ub=z.Q(l[l.length-1]);var q=z.Oj(l[l.length-1],"width"),q=q.substr(0,q.length-2),q=(0,window.parseInt)(q,10);this.Ub.x+=q;return this.ye(n.x,n.y)}catch(u){z.S.a().b(u)}};z.f.hf=function(){try{var a=z.X(this.vd);return 1>a.length&&(a=z.X(this.Ue),1>a.length)?!1:!0}catch(b){z.S.a().b(b)}};
z.f.ab=function(){try{var a=window.document.getElementById("th-RW4GC-picture-dictionary"),b=window.document.getElementById("th-RW4GC-translator"),c=window.document.getElementById("th-RW4GC-prediction");if((null!=window.document.getElementById("th-RW4GC-dictionary")||null!=a||null!=b||null!=c)&&this.Bh)return"";var a=[],d=RegExp("\u200b","g"),e=z.X(this.vd);if(1>e.length){e=z.X(this.Ue);if(1>e.length){var g=z.J(this.wb);if(null!==g){var h=z.Q(g),l=z.J(this.Te),m=z.Oj(l,"height"),m=m.substr(0,m.length-
2),m=(0,window.parseInt)(m,10)/2,e=0;this.S(l,"kix-cursor-italic")&&(e=m/Math.tan(Math.PI/180*77));h.y+=m;h.x+=l.offsetWidth/2+e;var n=z.Oj(l,"display");z.O(l,"display","none");this.ye(h.x,h.y,!1);var m="",p=this.Id(h.x,h.y,0);if(null==p)return z.O(l,"display",n),this.la(),a;h=[];h.push(p);for(var g=e=0,q=window.document.querySelectorAll(".textHELPWR"),u=0;u<q.length;u++)if(q[u]==p){if(0<u)for(g=u-1;q[g].classList.contains("thWord")&&!(h.unshift(q[g]),g--,0>g););e=u+1;if(e<q.length)for(;q[e].classList.contains("thWord")&&
!(h.push(q[e]),e++,e>=q.length););break}for(u=0;u<h.length;u++)m+=h[u].textContent;this.la();a.push(m.replace(d,""));z.O(l,"display",n)}return a}return""}if(this.Bh)return"";u=this.Ec();2<u.length?a.push(u[0].replace(d,"")):a.push(u.join(" ").replace(d,""));this.la();return a}catch(r){z.S.a().b(r)}};
z.f.Wf=function(a,b){for(var c=[],d=[],e,g;(e=window.document.elementFromPoint(a,b))&&-1===c.indexOf(e)&&null!=e;)c.push(e),d.push({value:e.style.getPropertyValue("pointer-events"),fm:e.style.getPropertyPriority("pointer-events")}),e.style.setProperty("pointer-events","none","important");for(e=d.length;g=d[--e];)c[e].style.setProperty("pointer-events",g.value?g.value:"",g.fm);return c};
z.f.pc=function(){try{var a=[];a.context="";a.word="";a.cursorindex="";a.spaceatstart=!1;a.spaceatend=!1;a.prepunc="";a.postpunc="";a.selectRight=0;a.selectLeft=0;a.prechar="";a.currentchar="";a.postchar="";var b=z.J(this.Te);z.Q(b);var c=window.document.createRange(),d=Bk(this,"kix-embeddedobject-view");if(!(null!==d.element&&-1<d.element.className.indexOf("kix-embeddedobject-view"))){d=Bk(this,"kix-wordhtmlgenerator-word-node");if(null==d.element&&(d=Bk(this,"kix-lineview"),null==d.element))return null;
d.element=z.Ke(d.element,"kix-lineview");if(null==d.element)return null;for(var e=b="",g=!1,h=window.document.createTreeWalker(d.element,window.NodeFilter.SHOW_TEXT),l=h.nextNode(),m="",n="",p=0,q=0;l;){for(var u=l.textContent.split(""),r=0;r<u.length;r++){c.setStart(l,r);c.setEnd(l,r+1);var v=c.getClientRects(),w;a:{for(var K=d.ne.x+1,G=d.ne.y,A=0;A<v.length;++A){var N=v[A];if(N.left<K&&N.right>K&&N.top<G&&N.bottom>G){w=N;break a}if(N.left>K){w="leftpastcaret";break a}}w=!1}"leftpastcaret"==w?(r=
u.length+10,g=!0):w?(r=u.length+10,g=!0):"\u200b"!==c.toString()&&(n=c.toString(),b+=n);p++}g||p!=d.element.textContent.length||(b=d.element.textContent,g=!0,p=b.length+1);if(g){var P=b.split(/(.*?[.?!])/g);1<P.length&&(b=P[P.length-1]);a.context=d.element.textContent.substr(0,p-1).replace(this.ec,"").split(/(.*?[.?!])/g);for(r=a.context.length;r--;)1>a.context[r].length&&a.context.splice(r,1);for(var L=d.element.textContent.substr(0).replace(this.ec,"").split(/(.*?[.?!])/g),r=L.length;r--;)""===
L[r]&&L.splice(r,1);0<q&&(L[0]=L[0].substr(q),a.context[0]=a.context[0].substr(q));if(1>a.context.length)for(var ma=d.element.previousSibling;ma;)10<ma.textContent.split(/\s/g).length?(m=ma.textContent+m,ma=null):(m=ma.textContent+m,ma=ma.previousSibling);0<a.context.length?(L=L[a.context.length-1],a.context=a.context[a.context.length-1],e=L.substr(a.context.length),-1!==".?!".indexOf(a.context.substr(a.context.length-2),1)&&(a.spaceatstart=!0)):L=e=a.context="";var cb=a.context.split(/\s/g);a.word=
L.split(/\s/g)[cb.length-1];var ic=cb[cb.length-1].replace(this.ec,"");a.cursorindex=ic.length;if(0==a.context.length||0==e.trim().replace(/[\u200B]/g,"").length)a.spaceatend=!0;0==a.cursorindex?(a.selectLeft=0,a.selectRight=0,a.spaceatend=!0,a.word=""):(a.selectLeft=ic.replace(this.ec,"").length,a.selectRight=a.word.replace(this.ec,"").length-a.selectLeft);var Bc=a.word.match(this.Nc),Ia=a.word,cd=Ia.indexOf(Bc);0<cd&&(a.prepunc=Ia.substring(0,cd).replace(/[\u200B]/g,""),Ia=Ia.substring(cd).replace(/[\u200B]/g,
""));var Ia=Ia.split("").reverse().join(""),Bc=Ia.match(this.Nc),dd=Ia.indexOf(Bc);0<dd&&(a.postpunc=Ia.substring(0,dd),a.postpunc=a.postpunc.split("").reverse().join("").replace(/[\u200B]/g,""),Ia=Ia.substring(dd));l=null}else Hk(l.parentElement)&&(q=b.length),l=h.nextNode()}a.context=m+a.context;a.context=a.context.replace(this.ec,"").replace(/\u00a0/g," ");return a}}catch(Ye){z.S.a().b(Ye)}};
z.f.ue=function(){try{this.hd();var a={};a.$a=z.He(z.X(this.u)[0]);if(!(1>a.$a.length)){for(var b=z.J(this.jc),c=b.innerHTML.split("\x3cthrwgdns:thctag")[0],d=c.split("\x3e"),e=[],g=0;g<d.length;g++){var h=d[g];"\x3c"!=h.substr(0,1)&&e.push(h.split("\x3c")[0])}a.Yc=e.join(" ").split(a.$a).length-1;var l=z.X(this.u);a.cb=a.$a;a.Ic=a.Yc;a.cb=z.He(l[l.length-1]);if(0<a.cb.length){var m=b.innerHTML.split("\x3c/thrwgdns:thctag\x3e");m[m.length-1]=null;c=m.join();c=c.substr(0,c.length-2);d=c.split("\x3e");
e=[];for(g=0;g<d.length;g++)h=d[g],"\x3c"!=h.substr(0,1)&&e.push(h.split("\x3c")[0]);a.Ic=e.join(" ").split(a.cb).length-1}this.la();return a}}catch(n){z.S.a().b(n)}};
z.f.Gc=function(a){try{a=a.substring(1);var b=(0,window.parseInt)(a,16),b="rgb("+(b>>16&255)+","+(b>>8&255)+","+(b&255)+")",c=window.document.getElementById("bgColorButton");null==c&&(c=window.document.getElementById("textColorButton"));var d=window.document.getElementById("jfk-palette-cell-169");if(null!==c||null!==d){z.S.a().fireEvent(c,"mousedown");z.S.a().fireEvent(c,"mouseup");z.S.a().fireEvent(c,"click");var d=window.document.getElementById("jfk-palette-cell-169"),e=d.firstChild.style.backgroundColor;
d.firstChild.style.backgroundColor=b;z.S.a().fireEvent(d,"mousedown");z.S.a().fireEvent(d,"mouseup");z.S.a().fireEvent(d,"click");d.firstChild.style.backgroundColor=e}else{var g=this.ue(),h='{ "doc":"'+window.location.href+'","color":"'+a+'","startWordCount":"'+g.Yc+'", "startWord":"'+(0,window.escape)(g.$a)+'", "endWordCount":"'+g.Ic+'", "endWord":"'+(0,window.escape)(g.cb)+'"}',h=z.pd(h);window.postMessage({method:"highlightSelection",type:"1757FROM_PAGERW4G",payload:h},"*")}}catch(l){z.S.a().b(l)}};
z.f.mc=function(){try{var a=window.document.getElementById("bgColorButton");null==a&&(a=window.document.getElementById("textColorButton"));if(null!==a){z.S.a().fireEvent(a,"mousedown");z.S.a().fireEvent(a,"mouseup");z.S.a().fireEvent(a,"click");var b=window.document.getElementById("jfk-palette-cell-169"),c=b.firstChild.style.backgroundColor;b.firstChild.style.backgroundColor="rgb(255,255,255)";z.S.a().fireEvent(b,"mousedown");z.S.a().fireEvent(b,"mouseup");z.S.a().fireEvent(b,"click");b.firstChild.style.backgroundColor=
c}else{var d=this.ue(),e='{ "doc":"'+window.location.href+'","startWordCount":"'+d.Yc+'", "startWord":"'+(0,window.escape)(d.$a)+'", "endWordCount":"'+d.Ic+'", "endWord":"'+(0,window.escape)(d.cb)+'"}',e=z.pd(e);window.postMessage({method:"clearHighlights",type:"1757FROM_PAGERW4G",payload:e},"*")}}catch(g){z.S.a().b(g)}};
z.f.hd=function(a){try{void 0==a&&(a=!0);var b=[],c=[],d=z.X(this.vd);if(1>d.length&&(d=z.X(this.Ue),1>d.length))return b;var d=Array.prototype.slice.call(d,0),e=z.S.a().bind(this,this.Sj);d.sort(e);for(var g=d,d=[],e=0;e<g.length;e++)a?z.S.a().Bn(g[e])&&d.push(g[e]):d.push(g[e]);if(0==d.length)return b;a=[];for(var h=g=null,l=null,e=0;e<d.length;e++){for(var h=z.X(this.ja,d[e].parentNode),m=0;m<h.length;m++)h[m]!==l&&(a.push(h[m]),l=h[m]);1>h.length&&(g=z.Ke(d[e],this.ja),g!==l&&(a.push(g),l=g))}g=
e=null;for(h=0;h<a.length;h++)for(e=z.X(this.jb,a[h]),l=0;l<e.length;l++)this.Tc(e[l]),null===g&&(g=e[l]);var n;n=Hk(d[0])?z.Qj(Ik(d[0]),this.h):z.Qj(d[0],this.h);var p;p=Hk(d[d.length-1])?z.Qj(Ik(d[d.length-1]),this.h):z.Qj(d[d.length-1],this.h);var q=z.pg(d[d.length-1]);p.x+=q.width-4;this.pi(n);this.oi(p);this.Df();this.ta=z.X(this.u);var u=window.document.querySelectorAll("."+this.N),d="";for(n=0;n<u.length;n++)u[n].classList.contains(this.u)?d+=u[n].textContent:(b.push(d),d="",c.push(Hk(this.ta[n])));
b.push(d);c.push(Hk(this.ta[n]));this.hl=c;return b}catch(r){z.S.a().b(r)}};z.f.getSelection=function(a){try{this.fg=a;var b=this.ue(),c='{ "doc":"'+window.location.href+'","startWordCount":"'+b.Yc+'", "startWord":"'+(0,window.escape)(b.$a)+'", "endWordCount":"'+b.Ic+'", "endWord":"'+(0,window.escape)(b.cb)+'"}',c=z.pd(c);window.postMessage({method:"getSelection",type:"1757FROM_PAGERW4G",payload:c},"*")}catch(d){z.S.a().b(d)}};
z.f.mt=function(){this.h.scrollTop=this.og;var a=this.hd(!1);this.la();this.jg(a);this.jg=null};z.f.kt=function(){this.h.scrollTop=this.og;var a=this.hd(!1);this.la();a=a.join(" ").replace(/(\.+|\:|\!|\?)(\"*|\'*|\)*|}*|]*)(\s|\n|\r|\r\n)/gm,".\x3cbr /\x3e\x3cbr /\x3e$2").split("|");a={documentTitle:window.document.title.replace(" - Google Docs",""),html:a.join(" ")};this.jg(a);this.jg=null};z.f.qc=function(a){try{this.jg=a,Jk(this,this.mt.bind(this))}catch(b){z.S.a().b(b)}};
z.f.bh=function(a){try{this.jg=a,Jk(this,this.kt.bind(this))}catch(b){z.S.a().b(b)}};z.f.Ec=function(){try{var a=z.X(this.vd);if(1>a.length&&(a=z.X(this.Ue),1>a.length))return this.Vi(!0);var b=this.hd();return 1>b.length&&1>a.length?this.Vi(!0):b}catch(c){z.S.a().b(c)}};z.f.Ji=function(){try{return this.Ec().join(" ")}catch(a){z.S.a().b(a)}};
z.f.Sf=function(){try{this.qk();var a=z.X(this.N);if(0!==a.length)for(var b=a[0].parentNode;null!==a;){b.innerHTML=z.He(b);a=z.X(this.N);if(0===a.length)break;b=a[0].parentNode}}catch(c){z.S.a().b(c)}};z.f.Ac=function(a,b,c,d){try{this.Og(a,b,c,d)}catch(e){z.S.a().b(e)}};z.f.Xe=function(a,b,c){try{this.Pg(a,b,c)}catch(d){z.S.a().b(d)}};
z.f.dh=function(){try{var a={trailingSpace:!1},b=this.Ec(),c=z.J(this.wb);if(null!==c){var d=z.Q(c),e=z.J(this.Te),g=z.Oj(e,"height"),g=g.substr(0,g.length-2),g=(0,window.parseInt)(g/2,10),c=0;this.S(e,"kix-cursor-italic")&&(c=g/Math.tan(Math.PI/180*77));d.y+=g;d.x+=c+(e.offsetWidth/2+.5);d.x+=1;d.y+=4;var h=this.Id(d.x,d.y,0),l=z.Q(h);l.x+=this.Qh(h.offsetWidth);l.y+=this.Qh(h.offsetHeight);if(l.x<d.x-2||l.y<d.y-2)a.trailingSpace=!0;a.currentWord=(0,window.parseInt)(h.className.split(" ")[2])}this.la();
a.words=b.join(" ");return a}catch(m){z.S.a().b(m)}};z.f.pb=function(a){try{var b=function(a,b){b?a.classList.add("thImageHighlighted"):a.classList.remove("thImageHighlighted")};0<a&&(Hk(this.ta[a-1])?b(Ik(this.ta[a-1]),!1):z.S.a().wa(this.ta[a-1],"thHighlighted"));if(Hk(this.ta[a]))b(Ik(this.ta[a]),!0);else{try{this.fe(this.ta[a],this.h)}catch(c){}z.S.a().Q(this.ta[a],"thHighlighted")}}catch(d){z.S.a().b(d)}};z.f.stop=function(){try{this.la()}catch(a){z.S.a().b(a)}};
z.f.Jd=function(a,b){try{var c=null,d=z.V.a().I().speechoptions.continousreading;if(a&&!d&&null===this.Ub)this.Ka=null,this.Ib=-1,b(null);else{var e=z.Q(this.Ka);e.x+=this.Ib;for(var g=this.Ka.querySelectorAll(".kix-wordhtmlgenerator-word-node"),h=0;h<g.length;h++){var l=z.Q(g[h]).x;if(e.x>=l&&e.x<g[h].offsetWidth+l){var m=z.Q(g[h]);e.y=m.y;h=g.length}}if(-1<this.Ib)!d&&null!==this.Ub&&(e.y>this.Ub.y||e.y===this.Ub.y&&e.x>=this.Ub.x)?(this.Ka=null,this.Ib=-1,b(null)):(this.Ka=null,this.Ib=-1,b(this.ye(e.x+
5,e.y+2)));else{this.Ib=-1;if(null!==this.kg)for(var n=this.kg.nextElementSibling;null!==n;){if(0<n.textContent.trim().length){this.kg=n;var p;a:{try{c=[];this.Tc(n);this.Nj();this.Df();for(var q=z.X(this.u),u=0;u<q.length;u++)c.push(z.Ee(q[u]));(0,window.setTimeout)(this.Tf.bind(this),this.Of);this.ta=z.X(this.u);1===this.ta.length&&this.pb(0);p=c;break a}catch(r){z.S.a().b(r)}p=void 0}b(p);return}n=n.nextElementSibling}c=this.Ka.closest(".kix-page");if(null==c)return[];u=c.querySelectorAll("."+
this.ja);if(1==u.length)return Gk(this,c,b);var v=this.Ka;p=null;for(q=0;q<u.length;q++)v==u[q]&&(window.currentCellIndex=q,q=u.length);for(q=++window.currentCellIndex;q<u.length;q++)0<u[q].textContent.trim().length&&(p=u[q],q=u.length);if(null==p)return Gk(this,c,b);b(this.Ui(p));return[]}}}catch(w){z.S.a().b(w)}};
z.f.Vi=function(a){var b=z.J(this.wb);if(null!==b){var b=z.Q(b),c=z.J(this.Te),d=z.Oj(c,"height"),d=d.substr(0,d.length-2),d=(0,window.parseInt)(d/2,10),e=0;this.S(c,"kix-cursor-italic")&&(e=d/Math.tan(Math.PI/180*77));b.y+=d;b.x+=e+(c.offsetWidth/2+.5);return this.ye(b.x,b.y,a)}return null};
z.f.Wk=function(a){try{var b=[];if(null!==a){var c=z.X(this.jb,a);for(a=0;a<c.length;a++)this.Tc(c[a]);this.Nj()}this.Df();for(var d=z.X(this.u),c=0;c<d.length;c++)b.push(z.Ee(d[c]));(0,window.setTimeout)(this.Tf.bind(this),this.Of);this.ta=z.X(this.u);1===this.ta.length&&this.pb(0);return b}catch(e){z.S.a().b(e)}};
z.f.ye=function(a,b,c){try{void 0==c&&(c=!0);var d=[],e=[],g=this.Yg(a,b);if(null==g&&(g=this.Yg(a,b),null==g))return null;if(null!==g){this.kg=z.Ke(g,this.jb);if(null==this.kg){var h=g.querySelectorAll("."+this.jb);if(0==h.length||1==h.length&&1==h.length&&0==h[0].textContent.trim().length)return;var l=z.Q(h[0]),m=l.x,n=m+h[0].offsetWidth;1<h.length&&(n=m+h[h.length-1].offsetWidth);return a>=n?this.ye(n-4,l.y,c):this.ye(m,l.y,c)}this.Tc(this.kg);this.lm(a,b)}this.Df();var p=z.X(this.u);if(0==p.length)return d;
for(a=0;a<p.length;a++)d.push(z.Ee(p[a])),e.push(Hk(p[a]));(0,window.setTimeout)(this.Tf.bind(this),this.Of);this.ta=z.X(this.u);1===this.ta.length&&c&&this.pb(0);this.hl=e;return d}catch(q){z.S.a().b(q)}};
z.f.Tc=function(a){try{var b=z.J(this.jb,a);if(null===b)if(this.S(a,this.jb))b=a;else throw Error("The element has no text child.");a={};a.key=b;a.value=a.key.innerHTML;this.He.push(a);var c=RegExp("\u200b","g"),b=b.childNodes;for(a=0;a<b.length;a++){for(var d=z.Wj(z.S.a(),b[a]),e=[],g=!1,h=0;h<d.length;h++){var l=d[h];if(g=Hk(l.parentElement))try{var m;var n=l;try{for(var p=["svg","image","title","desc"];!p.includes(n.nodeName.toLowerCase());)if(null!=n.parentElement)n=n.parentElement;else break;
m=void 0==n.nodeName?"undefined":"svg"==n.nodeName.toLowerCase()||"image"==n.nodeName.toLowerCase()?"image":"desc"==n.nodeName.toLowerCase()?"desc":"title"==n.nodeName.toLowerCase()?"title":"undefined"}catch(q){m="undefined"}"desc"==m.toLowerCase()?-1==l.nodeValue.indexOf("gmath_latex")&&e.push(d[h]):e.push(d[h])}catch(u){e.push(d[h])}else e.push(d[h])}for(g=0;g<e.length;g++)if(0<e.length){for(var r=e[g].nodeValue.split(/\s/),n=h="",p=0;p<r.length;p++){var v=r[p].replace(c,"");"\x3c"===v.substr(0,
1)?(n+="\x3c"+this.Ba+" class\x3d'"+this.N+"'\x3e"+v.trim()+"\x3c/"+this.Ba+"\x3e",p<r.length-1&&(n+="\x3c"+this.Ba+" class\x3d'"+this.N+" "+this.Ga+"'\x3e\x26nbsp;\x3c/"+this.Ba+"\x3e")):(" "===v||""===v)&&p<r.length-1?n+="\x3c"+this.Ba+" class\x3d'"+this.N+" "+this.Ga+"'\x3e\x26nbsp;\x3c/"+this.Ba+"\x3e":0<v.length&&(this.rf++,n+="\x3c"+this.Ba+" class\x3d'"+this.N+" "+this.u+"'\x3e"+v.trim()+"\x3c/"+this.Ba+"\x3e",p<r.length-1&&(n+="\x3c"+this.Ba+" class\x3d'"+this.N+" "+this.Ga+"'\x3e\x26nbsp;\x3c/"+
this.Ba+"\x3e"))}var h=h+n,w=z.le("thrwgdns:thctag");w.innerHTML=h;var K=e[g],G=K.parentNode;G&&G.replaceChild(w,K);this.rf=-1}}}catch(A){z.S.a().b(A)}};z.f.fe=function(a,b){try{if(void 0!=a&&void 0!=b&&null!=a&&null!=b){var c=0,d=a;if(null!=d&&void 0!=d){for(;d!==b;)if(null!==d.offsetTop&&void 0!==d.offsetTop&&(c+=d.offsetTop),d=d.offsetParent,null==d||void 0==d)return;c+30>b.scrollTop&&c<b.scrollTop+b.offsetHeight-30||(b.scrollTop=c-30)}}}catch(e){z.S.a().b(e)}};
z.f.la=function(){try{if(0!==z.X(this.N).length){for(var a in this.He)this.He[a].key.innerHTML=this.He[a].value;this.He.length=0}}catch(b){z.S.a().b(b)}};
z.f.pi=function(a){try{var b=[];this.Ke=0;for(var c=z.X(this.N),d=0;d<c.length;d++){var e;e=Hk(c[d])?z.Qj(Ik(c[d]),this.h):z.Qj(c[d],this.h);var g=z.pg(c[d]);if(e.x+g.width<a.x)b.push(c[d]),this.S(c[d],this.u)&&this.Ke++;else{for(;this.S(c[d],this.Ga);)b.push(c[d]),d++;d=c.length}}if(0!==b.length){a="";var h=b[0].parentNode;3==h.firstChild.nodeType&&(a+=h.firstChild.textContent,z.ue(h.firstChild));c="";for(d=0;d<b.length;d++)b[d].parentNode!==h&&(h.innerHTML=a+h.innerHTML,a="",h=b[d].parentNode),
c=z.He(b[d]),a+=c,z.ue(b[d]);0!=h.childNodes.length&&3==h.lastChild.nodeType&&(a+=h.lastChild.textContent);h.innerHTML=a+h.innerHTML}}catch(l){z.S.a().b(l)}};
z.f.oi=function(a){try{for(var b=[],c=z.X(this.N),d=c.length-1;0<=d;--d){var e;e=Hk(c[d])?z.Qj(Ik(c[d]),this.h):z.Qj(c[d],this.h);e.x+=2;if(e.x>=a.x)b.push(c[d]),this.Ka=this.Dk(c[d]),Hk(c[d])?this.Ib=z.Qj(Ik(c[d]),this.Ka).x:this.Ib=z.Qj(c[d],this.Ka).x;else{for(;this.S(c[d],this.Ga);)b.push(c[d]),d--;d=-1}}if(0!==b.length){a="";b.reverse();c=b;for(d=b.length-1;0<=d;d--)b[d].parentNode!==c&&(c.innerHTML+=a,a="",c=b[d].parentNode),a=z.He(b[d])+a,z.ue(b[d]);z.He(c.innerHTML);c.innerHTML+=a}}catch(g){z.S.a().b(g)}};
z.f.pk=function(a){try{var b=z.X(this.N,a),b=Array.prototype.slice.call(b,0);if(0!==b.length){a="";for(var c=b,d=b.length-1;0<=d;d--)b[d].parentNode!==c&&(c.innerHTML+=a,a="",c=b[d].parentNode),a=z.He(b[d])+a,z.ue(b[d]);c.innerHTML+=a}}catch(e){z.S.a().b(e)}};z.f.Df=function(){try{for(var a=-1,b=z.X(this.N),c=0;c<b.length;c++)this.S(b[c],this.u)&&a++,this.zd(b[c],(a+this.Ke).toString(),a.toString())}catch(d){z.S.a().b(d)}};
z.f.Tf=function(){try{var a=z.X(this.vd);1>a.length&&(a=z.X(this.Ue));for(var b=0;b<a.length;b++)z.ue(a[b])}catch(c){z.S.a().b(c)}};z.f.Yg=function(a,b){try{return Ck(this,a,b,"kix-lineview")}catch(c){z.S.a().b(c)}};
z.f.Id=function(a,b){try{var c=z.S.a().Wf(a,b),d=c.find(function(a){return a.classList.contains(this.u)}.bind(this));if(void 0==d){var e=c.find(function(a){return a.classList.contains(this.Ga)}.bind(this));if(void 0!==e){for(var g=[].slice.call(window.document.querySelectorAll("."+this.N)),h=g.findIndex(function(a){return e==a}.bind(this)),c=null,d=h;0<=d;d--)if(g[d].classList.contains(this.u)){c=g[d];break}for(var l=null,d=h;d<g.length;d++)if(g[d].classList.contains(this.u)){l=g[d];break}if(null==
l&&null==c)return null;if(null==l)return c;if(null==c)return l;var m=c.getBoundingClientRect().x+c.getBoundingClientRect().width,n=l.getBoundingClientRect().x;return a<=m+((n-m)/2+.5)?c:l}l=c[0].closest("."+this.ja);if(null==l)return d;var p=l.querySelectorAll("."+this.u);return a<=z.Q(p[0]).x?p[0]:p[p.length-1]}return d}catch(q){z.S.a().b(q)}};
z.f.Qh=function(a){try{var b=z.J("kix-zoomdocumentplugin-inner",this.h);if(null==b)return a;var c=z.Oj(b,"webkitTransform");if(null==c||0==c.length)return a;c=c.substr(6,c.length-7);return a*(0,window.parseFloat)(c)}catch(d){z.S.a().b(d)}};
z.f.lm=function(a,b){try{var c=this.Id(a,b,0);if(null===c||void 0===c){var d=z.X(this.u);if(0==d.length){this.la();return}var e=z.Q(d[0]).x,g=e+d[0].offsetWidth;1<d.length&&(e=z.Q(d[d.length-1]).x,g=e+d[d.length-1].offsetWidth);c=d[0];a>=g&&(c=d[d.length-1])}this.$e(c);c=this.Id(a,b,0);this.Ze(c)}catch(h){z.S.a().b(h)}};z.f.Nj=function(){try{var a=z.X(this.u);this.$e(a[0]);a=z.X(this.u);null===a[0]?this.la():0==a.length?this.la():this.Ze(a[0])}catch(b){z.S.a().b(b)}};
z.f.$e=function(a){try{var b=null,c=null,d=null,e=!1;if(this.S(a,this.u))b=a;else if(this.S(a,this.ja)){for(var g=z.X(this.jb,a),h=0;h<g.length;h++)this.Tc(g[h]);c=z.X(this.u,a);b=c[c.length-1];e=!0}else return;z.S.a();var l=this.vc.sentences.sentenceEndExclusions,g=-1;null===c&&(d=z.Ke(b,this.ja),c=z.X(this.u,d));if(e)g=c.length-1;else for(var m=0;m<c.length;m++)c[m]===b&&(g=m,m=c.length);if(-1!==g){a=g;!e&&0<a&&a--;if(0<g){e=-1;for(m=a;0<=m;m--){var n=z.Vj(l,z.Ee(c[m]));n||(n=Hk(c[m]));if(!n)for(var p in this.sb)-1!==
c[m].innerText.search(this.sb[p])&&(e=m,m=-1)}if(-1<e){if(c.length-1===e)this.pk(z.Ke(c[e],this.ja));else{var q;q=Hk(c[e+1])?z.Qj(Ik(c[e+1]),this.h):z.Qj(c[e+1],this.h);this.pi(q)}return}}null===d&&(d=z.Ke(b,this.ja));this.$e(d.previousSibling)}}catch(u){z.S.a().b(u)}};
z.f.Ze=function(a){try{if(null!=a){var b=null,c=null,d=null,e=!1;if(this.S(a,this.u))b=a;else if(this.S(a,this.ja)){for(var d=a,g=z.X(this.jb,a),h=0;h<g.length;h++)this.Tc(g[h]);c=z.X(this.u,a);b=c[0];e=!0}else return;z.S.a();var l=this.vc.sentences.sentenceEndExclusions;a=-1;null===c&&(d=z.Ke(b,this.ja),c=z.X(this.u,d));if(e)a=0;else for(var m=0;m<c.length;m++)c[m]===b&&(a=m,m=c.length);if(-1!==a){e=-1;for(m=a;m<c.length;m++){var n=z.Vj(l,z.Ee(c[m]));n||(n=Hk(c[m]));if(!n)for(var p in this.sb)-1!==
c[m].innerText.search(this.sb[p])&&(e=m,m=c.length)}-1===e&&null===d.nextSibling&&(e=c.length-1);if(e===c.length-1||0<c.length&&-1==e)this.Ka=d;if(-1<e){if(e<c.length-1){var q;q=Hk(c[e+1])?z.Qj(Ik(c[e+1]),this.h):z.Qj(c[e+1],this.h);this.oi(q)}}else null===d&&(d=z.Ke(b,this.ja)),this.Ze(d.nextSibling)}}}catch(u){z.S.a().b(u)}};z.f.Dk=function(a){try{return null===a?null:this.S(a,this.ja)?a:z.Ke(a,this.ja)}catch(b){z.S.a().b(b)}};
z.f.zi=function(a,b){try{var c=window.document.createEvent("MouseEvents");c.initMouseEvent.apply(c,b);a.dispatchEvent(c)}catch(d){z.S.a().b(d)}};z.f.rk=function(){};z.f.qk=function(){try{var a=z.J(this.wb);if(null!==a){var b=z.Q(a);this.rk(b.x,b.y)}}catch(c){z.S.a().b(c)}};z.f.Kj=function(a,b){try{if(a<this.eg.length&&!1===this.sf){this.fe(this.eg[a],this.h);var c=z.S.a().bind(this,this.Kj);a+=1;(0,window.setTimeout)(function(){c(a,b)},30)}else this.sf=!0,void 0!==b&&b()}catch(d){z.S.a().b(d)}};
z.f.Zd=function(a){try{if(void 0!=a.source&&void 0!=a.data&&a.source==window&&"1757FROM_BGRW4G"==a.data.type)if("onGetSelection"==a.data.method){var b=z.pd(a.data.payload);this.fg(b)}else if("onCollectHighlights"==a.data.method){var c=z.pd(a.data.payload);if(void 0!==c.auth)window.textHelp.webreaderapi.EventBusSingleton.getInst().publish("onShowDocsOAuthDialog",c.auth);else if("string"===typeof c){var d=null,e=z.S.a().fd(),d=window.open(c,"_ntthch"+e);d.focus();this.uc(c)}else void 0!==c.auth?this.uc("false"):
0==c[0].highlights.length?this.uc("false"):this.uc("true")}else if("onVocabWords"==a.data.method){var g=z.pd(a.data.payload);void 0!==g.auth?window.textHelp.webreaderapi.EventBusSingleton.getInst().publish("onShowDocsOAuthDialog",g.auth):"string"===typeof g&&(d=null,e=z.S.a().fd(),d=window.open(g,"_ntthchVc"+e),d.focus(),this.Bl(g))}}catch(h){z.S.a().b(h)}};
z.f.Og=function(a,b,c){try{this.uc=a,z.U.a(),Fk(this,b,c,function(a){var b=z.U.a().ha("ch_documentTitle");window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"CollectHighlights",parameters:{highlights:a.tk,title:window.document.getElementsByTagName("title")[0].innerHTML,url:window.location.href,docTitle:b}},"*")})}catch(d){z.S.a().b(d)}};
z.f.Pg=function(a,b){try{Fk(this,0,b,function(a){var b=[];z.S.a().Wj(a.tk).filter(function(a){if(3>a.text.trim().split(/\s/g).length)return b.push(a.text.trim()),!0});b.sort();a=window.textHelp.webreader.ConfigurationSingleton.getInst().getConfiguration();var c={};c.words=b;c.locale=a.locale;c.user=a.serversettings.user;c.translations={};c.translations.docTitle=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_document_title");c.translations.title=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_title");
c.translations.heading=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_heading");c.translations.symbol=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_symbol");c.translations.notes=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_notes");c.translations.meaning=window.textHelp.webreader.LocaleSingleton.getInst().getLocaleString("vocab_word_meaning");c.locale=window.textHelp.webreader.UserSettingsSingleton.getInst().getUserSettings().language.services;
window.window.thPostMessage({type:"1757FROM_PAGERW4G",key:"function",method:"Vocab",parameters:c},"*")})}catch(c){z.S.a().b(c)}};z.f.Sj=function(a,b){try{var c,d;Hk(a)?window.thPos=z.Qj(Ik(a),this.h):c=z.Qj(a,this.h);Hk(b)?window.thPos=z.Qj(Ik(b),this.h):d=z.Qj(b,this.h);if(c.y>d.y)return 1;if(c.y<d.y)return-1;if(c.y===d.y){if(c.x<d.x)return-1;if(c.x>d.x)return 1}return 0}catch(e){z.S.a().b(e)}};
z.f.Ui=function(a){try{if(null===a)return[];this.fe(a,this.h);var b=z.V.a().I().speechoptions.continousreading;this.Ka=null;this.Ib=-1;if(null!==a){var c=z.Q(a);if(!b&&null!==this.Ub&&c.y>this.Ub.y)return this.Ka=null,this.Ib=-1,[];var d=z.Oj(a,"height"),d=d.substr(0,d.length-2),d=(0,window.parseInt)(d,10);c.y+=d/2;return this.Wk(a)}return[]}catch(e){z.S.a().b(e)}};
z.f.sn=function(a,b){try{var c=a.nextSibling;!0===b&&(c=a);if(null===c)return null;for(;null!==c;){var d=z.Ee(c);if(0<d.length&&" "!==d)return z.J(this.ja,c);c=c.nextSibling}return null}catch(e){z.S.a().b(e)}};z.f.xm=function(a){try{a.doc=window.location.href,window.postMessage({method:"updateSelection",type:"1757FROM_PAGERW4G",payload:a},"*")}catch(b){z.S.a().b(b)}};
z.f.Xc=function(){try{this.fa.Hh(),this.fa.ra("CTRL+Shift+S",1,"keydown"),this.fa.ra("CTRL+Shift+S",1,"keyup"),this.fa.ra("CMD+Shift+S",1,"keydown"),this.fa.ra("CMD+Shift+S",1,"keyup")}catch(a){z.S.a().b(a)}};z.f.Zc=function(){};z.f.ya=function(){try{var a=z.J(this.wb),b={x:10,y:10};if(null==a)return{x:-1,y:-1};var c=z.Q(a),d=z.pg(a);b.x=c.x-d.width-a.scrollWidth-19;b.y=c.y+d.height+a.scrollHeight;return b}catch(e){z.S.a().b(e)}};z.f.jd=function(){try{var a=this.Ji();this.la();return a}catch(b){z.S.a().b(b)}};
z.f.Vf=function(a){null!==this.yl&&(0,window.clearTimeout)(this.yl);this.yl=null;if(-1!=" ?!.".indexOf(a)){var b=z.V.a().I().speechoptions.speakoneachword,c=z.V.a().I().speechoptions.speakoneachsentence;if(b||c)z.S.a().Ua.stop(),this.yl=(0,window.setTimeout)(function(){var d=this.jd(a).split(" "),e=d[d.length-1],g=e[e.length-1];-1<" .?!".indexOf(g)&&" "==a||void 0==g||0==g.trim().length||(g=[],g.push(e),b&&c?(" "!==a&&(this.sl=z.T.a().i("onthAPIStop",function(){z.S.a().Ua.td(d);z.T.a().Qe(this.sl)},
this)),z.S.a().Ua.td(g)):b?z.S.a().Ua.td(g):c&&" "!==a&&z.S.a().Ua.td(d))}.bind(this),300)}};z.t("textHelp.parsers",z.ek);z.t("textHelp.parsers.Parser",Y);Y.prototype.hiliteNextSentence=Y.prototype.Jd;Y.prototype.hiliteWord=Y.prototype.pb;Y.prototype.highlightSelection=Y.prototype.Gc;Y.hiliteWord=Y.pb;Y.prototype.getUserSettings=Y.prototype.I;Y.prototype.getSelection=Y.prototype.getSelection;Y.prototype.getSelectionLocal=Y.prototype.qc;Y.prototype.clearHighlights=Y.prototype.mc;
Y.prototype.getTextWithContext=Y.prototype.dh;Y.prototype.updateSelection=Y.prototype.xm;Y.prototype.startSpeechRecognition=Y.prototype.Xc;Y.prototype.stopSpeechRecognition=Y.prototype.Zc;Y.prototype.getParserName=Y.prototype.Cb;Y.prototype.getBarConfigFromParser=Y.prototype.Ab;Y.prototype.getPredictionPosition=Y.prototype.ya;Y.prototype.getSentenceText=Y.prototype.jd;z.Of("GDocsParser");})(__textHelp__);
//@ sourceURL=chrome-extension://inoeonmfapjbbkmdafoankkfajkcphgd/textHelp_GDocsParser.js